-- Run once in the Supabase SQL Editor for the Basement project.
-- Dates and times are local to Greece; stored instants are UTC timestamptz.
create table if not exists public.basement_slots (
  id bigint generated by default as identity primary key,
  service text not null check (service in ('Cross Training','EMS Training','EMS Sculpting','Vacu Power')),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  capacity integer not null check (capacity between 1 and 30),
  enabled boolean not null default true,
  unique (service, starts_at),
  check (ends_at > starts_at)
);

create table if not exists public.basement_bookings (
  id bigint generated by default as identity primary key,
  slot_id bigint not null references public.basement_slots(id),
  member_id uuid not null references auth.users(id),
  status text not null default 'booked' check (status in ('booked','cancelled')),
  created_at timestamptz not null default now(),
  cancelled_at timestamptz
);
create unique index if not exists basement_one_active_booking_per_slot
  on public.basement_bookings(slot_id, member_id) where status = 'booked';
create index if not exists basement_slots_start_idx on public.basement_slots(starts_at);
create index if not exists basement_bookings_member_idx on public.basement_bookings(member_id, status);

alter table public.basement_slots enable row level security;
alter table public.basement_bookings enable row level security;

drop policy if exists basement_slots_read on public.basement_slots;
create policy basement_slots_read on public.basement_slots for select to authenticated using (true);
drop policy if exists basement_bookings_read on public.basement_bookings;
create policy basement_bookings_read on public.basement_bookings for select to authenticated
  using (member_id = (select auth.uid()) or exists (
    select 1 from public.profiles p where p.id = (select auth.uid()) and p.role in ('owner','admin')
  ));

-- Only the owner changes availability; members reserve through the locking function below.
drop policy if exists basement_slots_owner_update on public.basement_slots;
create policy basement_slots_owner_update on public.basement_slots for update to authenticated
  using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role in ('owner','admin')))
  with check (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role in ('owner','admin')));

-- Aggregate availability without exposing other members' identities.
create or replace function public.basement_availability()
returns table(id bigint,service text,starts_at timestamptz,ends_at timestamptz,capacity integer,enabled boolean,reserved bigint)
language sql security definer set search_path = public, pg_temp as $$
  select s.id,s.service,s.starts_at,s.ends_at,s.capacity,s.enabled,
    (select count(*) from public.basement_bookings b where b.slot_id=s.id and b.status='booked')
  from public.basement_slots s
  where auth.uid() is not null and s.starts_at > now() and s.starts_at < now()+interval '14 days'
  order by s.starts_at,s.service;
$$;
revoke all on function public.basement_availability() from public,anon;
grant execute on function public.basement_availability() to authenticated;
revoke all on public.basement_slots,public.basement_bookings from anon,authenticated;

create or replace function public.basement_book(p_slot_id bigint, p_member_id uuid default null)
returns bigint language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_actor uuid := auth.uid();
  v_role text;
  v_target uuid;
  v_slot public.basement_slots%rowtype;
  v_count integer;
  v_id bigint;
begin
  if v_actor is null then raise exception 'Απαιτείται σύνδεση.'; end if;
  select role into v_role from public.profiles where id = v_actor;
  v_target := coalesce(p_member_id, v_actor);
  if v_target <> v_actor and coalesce(v_role,'') not in ('owner','admin') then
    raise exception 'Δεν επιτρέπεται κράτηση για άλλο μέλος.';
  end if;
  if not exists (select 1 from public.profiles where id = v_target and role = 'member') then
    raise exception 'Δεν βρέθηκε ενεργό μέλος.';
  end if;
  select * into v_slot from public.basement_slots where id = p_slot_id for update;
  if not found or not v_slot.enabled or v_slot.starts_at <= now() then
    raise exception 'Η ώρα δεν είναι διαθέσιμη.';
  end if;
  if exists (select 1 from public.basement_bookings where slot_id = p_slot_id and member_id = v_target and status = 'booked') then
    raise exception 'Το μέλος έχει ήδη κράτηση σε αυτή την ώρα.';
  end if;
  select count(*) into v_count from public.basement_bookings where slot_id = p_slot_id and status = 'booked';
  if v_count >= v_slot.capacity then raise exception 'Οι θέσεις εξαντλήθηκαν.'; end if;
  insert into public.basement_bookings(slot_id, member_id) values (p_slot_id, v_target) returning id into v_id;
  return v_id;
end $$;

create or replace function public.basement_cancel(p_booking_id bigint)
returns void language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_booking public.basement_bookings%rowtype;
  v_start timestamptz;
begin
  if auth.uid() is null then raise exception 'Απαιτείται σύνδεση.'; end if;
  select * into v_booking from public.basement_bookings where id = p_booking_id for update;
  if not found or v_booking.status <> 'booked' then raise exception 'Η κράτηση δεν βρέθηκε.'; end if;
  if v_booking.member_id <> auth.uid() and not exists (
    select 1 from public.profiles where id = auth.uid() and role in ('owner','admin')
  ) then raise exception 'Δεν επιτρέπεται η ακύρωση.'; end if;
  select starts_at into v_start from public.basement_slots where id = v_booking.slot_id;
  if v_start <= now() then raise exception 'Η προπόνηση έχει ήδη ξεκινήσει.'; end if;
  update public.basement_bookings set status = 'cancelled', cancelled_at = now() where id = p_booking_id;
end $$;

revoke all on function public.basement_book(bigint,uuid) from public, anon;
revoke all on function public.basement_cancel(bigint) from public, anon;
grant execute on function public.basement_book(bigint,uuid) to authenticated;
grant execute on function public.basement_cancel(bigint) to authenticated;
grant select on public.basement_slots, public.basement_bookings to authenticated;
grant update(enabled,capacity) on public.basement_slots to authenticated;

-- Schedule through 31 July 2027. Re-running does not duplicate slots.
with days as (
  select d::date as day from generate_series(date '2026-09-21', date '2027-07-31', interval '1 day') d
  where extract(isodow from d) between 1 and 6
), timetable as (
  select day, 'Cross Training'::text as service, t, 60 as duration_min, 6 as capacity from days
  cross join lateral unnest(case when extract(isodow from day)=6
    then array['10:00','11:00'] else array['09:00','11:00','16:00','17:00','18:00','19:00','20:00','21:00'] end) t
  union all
  select day, 'EMS Training', to_char(t,'HH24:MI'), 40, 3 from days
  cross join lateral generate_series(day + case when extract(isodow from day)=6 then time '10:00' else time '09:00' end,
    day + case when extract(isodow from day)=6 then time '12:00' else time '12:20' end,
    interval '40 minutes') t
  union all
  select day, 'EMS Training', to_char(t,'HH24:MI'), 40, 3 from days
  cross join lateral generate_series(day + time '16:00', day + time '21:20', interval '40 minutes') t
  where extract(isodow from day) between 1 and 5
  union all
  select day, service, t, 60, 1 from days
  cross join (values ('EMS Sculpting'),('Vacu Power')) s(service)
  cross join lateral unnest(case when extract(isodow from day)=6
    then array['10:00','11:00','12:00']
    else array['09:00','10:00','11:00','12:00','16:00','17:00','18:00','19:00','20:00','21:00'] end) t
)
insert into public.basement_slots(service,starts_at,ends_at,capacity)
select service, (day + t::time) at time zone 'Europe/Athens',
  (day + t::time + make_interval(mins => duration_min)) at time zone 'Europe/Athens', capacity
from timetable on conflict (service,starts_at) do nothing;
