alter table public.members
  add column if not exists date_of_birth date,
  add column if not exists debt numeric(10,2) not null default 0;

alter table public.member_packages
  add column if not exists frozen_until date;

create table if not exists public.manual_session_adjustments (
  id bigint generated by default as identity primary key,
  member_package_id uuid not null references public.member_packages(id) on delete cascade,
  change integer not null check (change <> 0),
  reason text,
  actor_id uuid references auth.users(id),
  created_at timestamptz not null default now()
);
alter table public.manual_session_adjustments enable row level security;
drop policy if exists "staff_manage_manual_session_adjustments" on public.manual_session_adjustments;
create policy "staff_manage_manual_session_adjustments" on public.manual_session_adjustments
for all to authenticated using (public.is_staff()) with check (public.is_staff());

create or replace function public.basement_adjust_sessions(p_member_package_id uuid, p_change integer, p_reason text default null)
returns integer language plpgsql security definer set search_path='public','pg_temp' as $$
declare v_role text; v_remaining integer;
begin
  select role into v_role from public.profiles where id=auth.uid();
  if coalesce(v_role,'') not in ('owner','admin','reception') then raise exception 'Δεν επιτρέπεται η αλλαγή συνεδριών.'; end if;
  if p_change=0 then raise exception 'Η μεταβολή πρέπει να είναι διαφορετική από μηδέν.'; end if;
  update public.member_packages
     set sessions_remaining=greatest(0,coalesce(sessions_remaining,0)+p_change)
   where id=p_member_package_id
   returning sessions_remaining into v_remaining;
  if not found then raise exception 'Το πακέτο δεν βρέθηκε.'; end if;
  insert into public.manual_session_adjustments(member_package_id,change,reason,actor_id)
  values(p_member_package_id,p_change,p_reason,auth.uid());
  return v_remaining;
end $$;
revoke all on function public.basement_adjust_sessions(uuid,integer,text) from public;
grant execute on function public.basement_adjust_sessions(uuid,integer,text) to authenticated;
revoke execute on function public.basement_adjust_sessions(uuid,integer,text) from anon;

create or replace function public.basement_admin_booking_action(p_booking_id bigint,p_action text)
returns void language plpgsql security definer set search_path='public','pg_temp' as $$
declare v_role text; v_booking public.basement_bookings%rowtype; v_member uuid; v_package uuid; v_used integer;
begin
  select role into v_role from public.profiles where id=auth.uid();
  if coalesce(v_role,'') not in ('owner','admin','reception') then raise exception 'Δεν επιτρέπεται αυτή η ενέργεια.'; end if;
  select * into v_booking from public.basement_bookings where id=p_booking_id for update;
  if not found then raise exception 'Η κράτηση δεν βρέθηκε.'; end if;
  select id into v_member from public.members where auth_user_id=v_booking.member_id;

  if p_action in ('complete','no_show') then
    update public.basement_bookings set status=case when p_action='complete' then 'completed' else 'no_show' end,
      completed_at=now(), checked_in_at=case when p_action='complete' then coalesce(checked_in_at,now()) else checked_in_at end
    where id=p_booking_id;
    if p_action='complete' and v_member is not null then
      insert into public.gym_checkins(member_id,booking_id,method,notes)
      values(v_member,p_booking_id,'automatic','Ολοκλήρωση από διαχειριστή') on conflict (booking_id) do nothing;
    end if;
    if v_member is not null and not exists(select 1 from public.basement_session_usage where booking_id=p_booking_id) then
      select id into v_package from public.member_packages
       where member_id=v_member and status='active' and starts_on<=current_date and expires_on>=current_date
         and (frozen_until is null or frozen_until<current_date) and coalesce(sessions_remaining,0)>0
       order by expires_on,id limit 1 for update;
      if v_package is not null then
        update public.member_packages set sessions_remaining=sessions_remaining-1 where id=v_package;
        insert into public.basement_session_usage(booking_id,member_package_id,change) values(p_booking_id,v_package,-1);
      end if;
    end if;
  elsif p_action='undo' then
    select coalesce(sum(change),0),min(member_package_id) into v_used,v_package from public.basement_session_usage where booking_id=p_booking_id;
    if v_package is not null and v_used<0 then update public.member_packages set sessions_remaining=sessions_remaining-v_used where id=v_package; end if;
    delete from public.basement_session_usage where booking_id=p_booking_id;
    delete from public.gym_checkins where booking_id=p_booking_id;
    update public.basement_bookings set status='booked',completed_at=null,checked_in_at=null where id=p_booking_id;
  else raise exception 'Άγνωστη ενέργεια.';
  end if;
end $$;
revoke all on function public.basement_admin_booking_action(bigint,text) from public;
grant execute on function public.basement_admin_booking_action(bigint,text) to authenticated;
revoke execute on function public.basement_admin_booking_action(bigint,text) from anon;

create or replace function public.basement_promote_waiting(p_slot_id bigint)
returns bigint language plpgsql security definer set search_path='public','pg_temp' as $$
declare v_wait public.basement_waiting_list%rowtype; v_id bigint; v_capacity integer; v_count integer;
begin
  select capacity into v_capacity from public.basement_slots where id=p_slot_id for update;
  select count(*) into v_count from public.basement_bookings where slot_id=p_slot_id and status='booked';
  if v_count>=coalesce(v_capacity,0) then return null; end if;
  select * into v_wait from public.basement_waiting_list where slot_id=p_slot_id and status='waiting' order by created_at,id limit 1 for update skip locked;
  if not found then return null; end if;
  insert into public.basement_bookings(slot_id,member_id,status) values(p_slot_id,v_wait.member_id,'booked') returning id into v_id;
  update public.basement_waiting_list set status='promoted' where id=v_wait.id;
  return v_id;
end $$;
revoke all on function public.basement_promote_waiting(bigint) from public;
grant execute on function public.basement_promote_waiting(bigint) to authenticated;
revoke execute on function public.basement_promote_waiting(bigint) from public,anon,authenticated;

create or replace function public.basement_audit_changes()
returns trigger language plpgsql security definer set search_path='public','pg_temp' as $$
declare v_old jsonb; v_new jsonb; v_id text;
begin
  v_old:=case when tg_op='INSERT' then null else to_jsonb(old) end;
  v_new:=case when tg_op='DELETE' then null else to_jsonb(new) end;
  v_id:=coalesce(v_new->>'id',v_old->>'id');
  insert into public.audit_log(actor_id,action,table_name,record_id,old_value,new_value)
  values(auth.uid(),lower(tg_op),tg_table_name,v_id,v_old,v_new);
  return coalesce(new,old);
end $$;
revoke execute on function public.basement_audit_changes() from public,anon,authenticated;
do $$ declare t text; begin
  foreach t in array array['members','member_packages','basement_bookings','financial_entries'] loop
    execute format('drop trigger if exists audit_changes on public.%I',t);
    execute format('create trigger audit_changes after insert or update or delete on public.%I for each row execute function public.basement_audit_changes()',t);
  end loop;
end $$;

create or replace function public.basement_cancel(p_booking_id bigint)
returns void language plpgsql security definer set search_path='public','pg_temp' as $$
declare v_booking public.basement_bookings%rowtype; v_start timestamptz; v_role text; v_cfg jsonb:='{}'::jsonb; v_is_admin boolean;
begin
  if auth.uid() is null then raise exception 'Απαιτείται σύνδεση.'; end if;
  select role into v_role from public.profiles where id=auth.uid();
  v_is_admin:=coalesce(v_role,'') in ('owner','admin','reception');
  select * into v_booking from public.basement_bookings where id=p_booking_id for update;
  if not found or v_booking.status<>'booked' then raise exception 'Η κράτηση δεν βρέθηκε.'; end if;
  if v_booking.member_id<>auth.uid() and not v_is_admin then raise exception 'Δεν επιτρέπεται η ακύρωση.'; end if;
  select starts_at into v_start from public.basement_slots where id=v_booking.slot_id;
  if v_start<=now() then raise exception 'Η προπόνηση έχει ήδη ξεκινήσει.'; end if;
  select value into v_cfg from public.app_settings where key='control_center_settings';
  if not v_is_admin and v_start < now()+make_interval(mins=>coalesce((v_cfg->>'cancelMinMinutes')::integer,0)) then raise exception 'Έληξε η προθεσμία ακύρωσης.'; end if;
  update public.basement_bookings set status='cancelled',cancelled_at=now() where id=p_booking_id;
  perform public.basement_promote_waiting(v_booking.slot_id);
end $$;

create index if not exists manual_session_adjustments_package_idx on public.manual_session_adjustments(member_package_id);
create index if not exists manual_session_adjustments_actor_idx on public.manual_session_adjustments(actor_id);
create index if not exists basement_waiting_member_idx on public.basement_waiting_list(member_id);
create index if not exists basement_session_usage_package_idx on public.basement_session_usage(member_package_id);
