-- Historical BookUp data lives apart from the live booking/session trigger path.
create table if not exists public.bookup_import_rows (
  external_booking_id text primary key,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  service text not null,
  source_status text not null,
  customer_name text not null,
  customer_phone text,
  customer_email text,
  phone_key text,
  email_key text,
  name_key text,
  content_key text not null,
  source_notes text,
  payment_status text,
  raw_data jsonb not null,
  member_id uuid references public.members(id),
  import_status text not null default 'pending' check (import_status in ('pending','ready','imported','needs_review','skipped')),
  review_reason text,
  imported_at timestamptz
);
create index if not exists bookup_import_rows_contact_idx on public.bookup_import_rows(phone_key,email_key,name_key);
create index if not exists bookup_import_rows_content_idx on public.bookup_import_rows(content_key);

create table if not exists public.bookup_bookings (
  id bigint generated by default as identity primary key,
  external_booking_id text not null unique references public.bookup_import_rows(external_booking_id),
  member_id uuid not null references public.members(id),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  service text not null,
  source_status text not null,
  trainer_name text,
  checked_in_at timestamptz,
  cancellation_reason text,
  notes text,
  payment_status text,
  recurring_group_id text,
  created_at timestamptz not null default now()
);
create index if not exists bookup_bookings_member_time_idx on public.bookup_bookings(member_id,starts_at desc);
create index if not exists bookup_bookings_time_idx on public.bookup_bookings(starts_at);

alter table public.bookup_import_rows enable row level security;
alter table public.bookup_bookings enable row level security;
create policy bookup_rows_staff_read on public.bookup_import_rows for select to authenticated using(public.is_staff());
create policy bookup_bookings_staff_read on public.bookup_bookings for select to authenticated using(public.is_staff());
create policy bookup_bookings_member_read on public.bookup_bookings for select to authenticated
 using(exists(select 1 from public.members m where m.id=member_id and m.auth_user_id=(select auth.uid())));
grant select on public.bookup_import_rows,public.bookup_bookings to authenticated;

comment on table public.bookup_bookings is 'Read-only archive of BookUp bookings. No session-deduction triggers or live-slot writes.';

create or replace function public.bookup_name_key(s text) returns text language sql immutable set search_path='public','pg_temp' as $$
 select coalesce(string_agg(part,' ' order by part collate "C"),'') from regexp_split_to_table(
 regexp_replace(translate(lower(coalesce(s,'')),'άέήίόύώϊϋΐΰ','αεηιουωιυιυ'),'[^[:alnum:]]+',' ','g'),'\s+') part where part<>''
$$;
revoke execute on function public.bookup_name_key(text) from public,anon,authenticated;
