-- AI nutrition planner, configurable macro rules, generation audit and progress history.
alter table public.member_measurements
  add column if not exists height_cm numeric(5,2),
  add column if not exists muscle_mass_kg numeric(5,2),
  add column if not exists visceral_fat numeric(5,2),
  add column if not exists metabolic_age integer,
  add column if not exists bmr_kcal integer;

alter table public.member_measurements
  add constraint member_measurements_height_range check (height_cm is null or height_cm between 80 and 260),
  add constraint member_measurements_muscle_range check (muscle_mass_kg is null or muscle_mass_kg between 0 and 250),
  add constraint member_measurements_visceral_range check (visceral_fat is null or visceral_fat between 0 and 100),
  add constraint member_measurements_metabolic_age_range check (metabolic_age is null or metabolic_age between 1 and 130),
  add constraint member_measurements_bmr_range check (bmr_kcal is null or bmr_kcal between 500 and 6000);
grant usage,select on sequence public.member_measurements_id_seq to authenticated;

create table public.nutrition_ai_settings (
  id boolean primary key default true check (id),
  rules jsonb not null,
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now()
);

insert into public.nutrition_ai_settings(id,rules) values (true, jsonb_build_object(
  'activityMultipliers',jsonb_build_object('sedentary',1.2,'light',1.375,'moderate',1.55,'high',1.725,'athlete',1.9),
  'goalAdjustments',jsonb_build_object('fat_loss',-0.18,'muscle_gain',0.1,'lean_bulk',0.08,'definition',-0.12,'maintenance',0,'recomposition',-0.05,'performance',0.05),
  'proteinPerKg',jsonb_build_object('fat_loss',2.0,'muscle_gain',2.0,'lean_bulk',1.9,'definition',2.2,'maintenance',1.7,'recomposition',2.1,'performance',1.8),
  'fatPerKg',0.8,'minimumCaloriesFemale',1200,'minimumCaloriesMale',1500,'targetTolerancePercent',5,'maxGenerationsPerDay',20
));

alter table public.nutrition_ai_settings enable row level security;
revoke all on public.nutrition_ai_settings from anon,authenticated;
grant select,update(rules) on public.nutrition_ai_settings to authenticated;
create policy nutrition_ai_settings_owner_read on public.nutrition_ai_settings for select to authenticated using (
  exists(select 1 from public.profiles where id=(select auth.uid()) and active and role::text in ('owner','admin'))
);
create policy nutrition_ai_settings_owner_update on public.nutrition_ai_settings for update to authenticated using (
  exists(select 1 from public.profiles where id=(select auth.uid()) and active and role::text in ('owner','admin'))
) with check (
  exists(select 1 from public.profiles where id=(select auth.uid()) and active and role::text in ('owner','admin'))
);

create table public.nutrition_ai_generations (
  id uuid primary key default gen_random_uuid(),
  member_id uuid not null references public.members(id) on delete restrict,
  created_by uuid not null default auth.uid() references auth.users(id),
  measurement_id bigint references public.member_measurements(id) on delete set null,
  request_kind text not null check(request_kind in ('create','revise')),
  instruction text,
  input_snapshot jsonb not null,
  rules_snapshot jsonb not null,
  targets_snapshot jsonb not null,
  result_snapshot jsonb,
  model text not null,
  input_tokens integer,
  output_tokens integer,
  status text not null check(status in ('completed','failed')),
  error_code text,
  created_at timestamptz not null default now()
);
create index nutrition_ai_generations_creator_day on public.nutrition_ai_generations(created_by,created_at desc);
create index nutrition_ai_generations_member on public.nutrition_ai_generations(member_id,created_at desc);
alter table public.nutrition_ai_generations enable row level security;
revoke all on public.nutrition_ai_generations from anon,authenticated;
grant select,insert(member_id,measurement_id,request_kind,instruction,input_snapshot,rules_snapshot,targets_snapshot,result_snapshot,model,input_tokens,output_tokens,status,error_code) on public.nutrition_ai_generations to authenticated;
create policy nutrition_ai_generation_owner_read on public.nutrition_ai_generations for select to authenticated using (
  exists(select 1 from public.profiles where id=(select auth.uid()) and active and role::text in ('owner','admin'))
);
create policy nutrition_ai_generation_owner_insert on public.nutrition_ai_generations for insert to authenticated with check (
  created_by=(select auth.uid()) and exists(select 1 from public.profiles where id=(select auth.uid()) and active and role::text in ('owner','admin'))
);

create table public.nutrition_plan_versions (
  id bigint generated by default as identity primary key,
  plan_id uuid not null references public.nutrition_plans(id) on delete cascade,
  member_id uuid not null references public.members(id) on delete restrict,
  revision integer not null,
  title text not null,
  starts_on date not null,
  ends_on date,
  status text not null,
  content jsonb not null,
  changed_by uuid default auth.uid() references auth.users(id),
  created_at timestamptz not null default now()
);
create index nutrition_plan_versions_plan on public.nutrition_plan_versions(plan_id,revision desc);
alter table public.nutrition_plan_versions enable row level security;
revoke all on public.nutrition_plan_versions from anon,authenticated;
grant select,insert(plan_id,member_id,revision,title,starts_on,ends_on,status,content) on public.nutrition_plan_versions to authenticated;
grant usage,select on sequence public.nutrition_plan_versions_id_seq to authenticated;
create policy nutrition_plan_versions_owner_read on public.nutrition_plan_versions for select to authenticated using (
  exists(select 1 from public.profiles where id=(select auth.uid()) and active and role::text in ('owner','admin'))
);
create policy nutrition_plan_versions_owner_insert on public.nutrition_plan_versions for insert to authenticated with check (
  changed_by=(select auth.uid()) and exists(select 1 from public.profiles where id=(select auth.uid()) and active and role::text in ('owner','admin'))
);

create function basement_private.archive_nutrition_plan_version() returns trigger language plpgsql security invoker set search_path=pg_catalog as $$
begin
  if old.content is distinct from new.content or old.status is distinct from new.status or old.title is distinct from new.title then
    insert into public.nutrition_plan_versions(plan_id,member_id,revision,title,starts_on,ends_on,status,content)
    values(old.id,old.member_id,old.revision,old.title,old.starts_on,old.ends_on,old.status,old.content);
  end if;
  return new;
end $$;
revoke all on function basement_private.archive_nutrition_plan_version() from public,anon,authenticated;
create trigger nutrition_plan_archive_version before update on public.nutrition_plans for each row execute function basement_private.archive_nutrition_plan_version();
