-- V43 SETTINGS COMPLETE
-- Makes previously presentation-only settings affect booking, portal and operations behavior.
-- Additive/non-destructive: existing members, packages, bookings and history are preserved.

alter table public.basement_slots add column if not exists trainer_id uuid references public.profiles(id) on delete set null;
alter table public.basement_bookings add column if not exists position_no integer;
alter table public.basement_bookings add column if not exists waitlist_source_id bigint references public.basement_waiting_list(id) on delete set null;
alter table public.basement_waiting_list add column if not exists reason text not null default 'capacity';
alter table public.basement_waiting_list drop constraint if exists basement_waiting_list_status_check;
alter table public.basement_waiting_list add constraint basement_waiting_list_status_check check(status in('waiting','promoted','accepted','expired','cancelled'));

create table if not exists public.member_consents(
  id bigint generated by default as identity primary key,
  member_id uuid not null references public.members(id) on delete cascade,
  consent_key text not null,
  accepted_at timestamptz not null default now(),
  unique(member_id,consent_key)
);
alter table public.member_consents enable row level security;
drop policy if exists member_consents_own on public.member_consents;
create policy member_consents_own on public.member_consents for all to authenticated
using(exists(select 1 from public.members m where m.id=member_id and m.auth_user_id=(select auth.uid())))
with check(exists(select 1 from public.members m where m.id=member_id and m.auth_user_id=(select auth.uid())));
drop policy if exists member_consents_staff on public.member_consents;
create policy member_consents_staff on public.member_consents for select to authenticated using(public.is_staff());
grant select,insert,update on public.member_consents to authenticated;

create table if not exists public.member_no_show_unlocks(
  id bigint generated by default as identity primary key,
  member_id uuid not null references public.members(id) on delete cascade,
  no_show_count integer not null,
  cost integer not null default 0,
  member_package_id uuid references public.member_packages(id) on delete set null,
  created_at timestamptz not null default now()
);
alter table public.member_no_show_unlocks enable row level security;
drop policy if exists no_show_unlock_staff on public.member_no_show_unlocks;
create policy no_show_unlock_staff on public.member_no_show_unlocks for all to authenticated using(public.is_staff()) with check(public.is_staff());
grant select,insert on public.member_no_show_unlocks to authenticated;

create table if not exists public.booking_restrictions(
  id uuid primary key default gen_random_uuid(),
  member_id uuid not null references public.members(id) on delete cascade,
  service_id uuid references public.services(id) on delete cascade,
  weekday smallint check(weekday between 1 and 7),
  start_time time,
  end_time time,
  reason text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.booking_restrictions enable row level security;
drop policy if exists booking_restrictions_staff on public.booking_restrictions;
create policy booking_restrictions_staff on public.booking_restrictions for all to authenticated using(public.is_staff()) with check(public.is_staff());
grant select,insert,update,delete on public.booking_restrictions to authenticated;

create index if not exists basement_slots_trainer_idx on public.basement_slots(trainer_id);
create index if not exists basement_bookings_waitlist_source_idx on public.basement_bookings(waitlist_source_id);
create index if not exists member_no_show_unlocks_member_idx on public.member_no_show_unlocks(member_id);
create index if not exists member_no_show_unlocks_package_idx on public.member_no_show_unlocks(member_package_id);
create index if not exists booking_restrictions_member_active_idx on public.booking_restrictions(member_id,active);
create index if not exists booking_restrictions_service_idx on public.booking_restrictions(service_id);

create or replace function basement_private.package_covers_service(p_template uuid,p_service text)
returns boolean language sql stable security definer set search_path='' as $$
 select not coalesce((select (value->>'serviceSubscriptionDates')::boolean from public.app_settings where key='control_center_settings'),true)
   or not exists(select 1 from public.package_template_services pts where pts.package_template_id=p_template)
   or exists(select 1 from public.package_template_services pts join public.services s on s.id=pts.service_id
             where pts.package_template_id=p_template and lower(s.name)=lower(p_service));
$$;
revoke all on function basement_private.package_covers_service(uuid,text) from public,anon,authenticated;

create or replace function basement_private.booking_counts_for_limit(p_status text,p_moved_at timestamptz,p_cfg jsonb)
returns boolean language sql immutable set search_path='' as $$
 select (
   p_status in('pending','booked','completed','no_show')
   or (not coalesce((p_cfg->>'ignoreCancelledInLimit')::boolean,true) and p_status in('cancelled','late_cancel'))
 ) and (not coalesce((p_cfg->>'ignoreMovedInLimit')::boolean,true) or p_moved_at is null);
$$;
revoke all on function basement_private.booking_counts_for_limit(text,timestamptz,jsonb) from public,anon,authenticated;

create or replace function basement_private.member_is_restricted(p_member uuid,p_service text,p_starts timestamptz)
returns boolean language sql stable security definer set search_path='' as $$
 select coalesce((select (value->>'restrictedCustomers')::boolean from public.app_settings where key='control_center_settings'),false)
 and exists(
   select 1 from public.booking_restrictions r
   left join public.services s on s.id=r.service_id
   where r.active and r.member_id=p_member
     and (r.service_id is null or lower(s.name)=lower(p_service))
     and (r.weekday is null or r.weekday=extract(isodow from p_starts at time zone 'Europe/Athens'))
     and (r.start_time is null or (p_starts at time zone 'Europe/Athens')::time>=r.start_time)
     and (r.end_time is null or (p_starts at time zone 'Europe/Athens')::time<r.end_time)
 );
$$;
revoke all on function basement_private.member_is_restricted(uuid,text,timestamptz) from public,anon,authenticated;

create or replace function basement_private.next_booking_position(p_slot bigint,p_capacity integer)
returns integer language plpgsql security definer set search_path='' as $$
declare i integer; v_cfg jsonb;
begin
  select coalesce(value,'{}') into v_cfg from public.app_settings where key='control_center_settings';
  if not coalesce((v_cfg->>'fixedPositions')::boolean,false) then return null; end if;
  perform pg_advisory_xact_lock(p_slot);
  for i in 1..greatest(1,p_capacity) loop
    if not exists(select 1 from public.basement_bookings b where b.slot_id=p_slot and b.position_no=i and b.status in('pending','booked')) then return i; end if;
  end loop;
  if coalesce((v_cfg->>'fixedPositionsAffectCapacity')::boolean,false) then return null; end if;
  select coalesce(max(position_no),p_capacity,0)+1 into i from public.basement_bookings where slot_id=p_slot and status in('pending','booked');
  return i;
end $$;
revoke all on function basement_private.next_booking_position(bigint,integer) from public,anon,authenticated;

create or replace function basement_private.assign_booking_position()
returns trigger language plpgsql security definer set search_path='' as $$
declare v_cfg jsonb; v_capacity integer; v_pos integer;
begin
  select coalesce(value,'{}') into v_cfg from public.app_settings where key='control_center_settings';
  if not coalesce((v_cfg->>'fixedPositions')::boolean,false) then new.position_no:=null; return new; end if;
  if new.status not in('pending','booked') then return new; end if;
  if tg_op='INSERT' then
    select capacity into v_capacity from public.basement_slots where id=new.slot_id;
    v_pos:=basement_private.next_booking_position(new.slot_id,coalesce(v_capacity,1));
    if v_pos is null then raise exception 'Δεν υπάρχει ελεύθερη σταθερή θέση.'; end if;
    new.position_no:=v_pos;
  elsif new.slot_id is distinct from old.slot_id or old.status not in('pending','booked') then
    select capacity into v_capacity from public.basement_slots where id=new.slot_id;
    v_pos:=basement_private.next_booking_position(new.slot_id,coalesce(v_capacity,1));
    if v_pos is null then raise exception 'Δεν υπάρχει ελεύθερη σταθερή θέση.'; end if;
    new.position_no:=v_pos;
  end if;
  return new;
end $$;
revoke all on function basement_private.assign_booking_position() from public,anon,authenticated;
drop trigger if exists assign_booking_position on public.basement_bookings;
create trigger assign_booking_position before insert or update of slot_id,status on public.basement_bookings
for each row execute function basement_private.assign_booking_position();


create or replace function basement_private.sync_fixed_positions()
returns void language plpgsql security definer set search_path='' as $$
declare v_cfg jsonb;
begin
  select coalesce(value,'{}') into v_cfg from public.app_settings where key='control_center_settings';
  if not coalesce((v_cfg->>'fixedPositions')::boolean,false) then return; end if;
  with ranked as(
    select b.id,row_number() over(partition by b.slot_id order by b.created_at,b.id)::integer as pos
    from public.basement_bookings b join public.basement_slots s on s.id=b.slot_id
    where b.status in('pending','booked') and s.ends_at>now()
  )
  update public.basement_bookings b set position_no=r.pos from ranked r where b.id=r.id and b.position_no is distinct from r.pos;
end $$;
revoke all on function basement_private.sync_fixed_positions() from public,anon,authenticated;

create or replace function basement_private.settings_position_sync()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  if new.key='control_center_settings' then perform basement_private.sync_fixed_positions(); end if;
  return new;
end $$;
revoke all on function basement_private.settings_position_sync() from public,anon,authenticated;
drop trigger if exists v43_settings_position_sync on public.app_settings;
create trigger v43_settings_position_sync after insert or update of value on public.app_settings
for each row execute function basement_private.settings_position_sync();

create or replace function basement_private.queue_waiting(p_slot bigint,p_member_auth uuid,p_reason text default 'capacity')
returns bigint language plpgsql security definer set search_path='' as $$
declare v_id bigint; v_cfg jsonb; v_member uuid; v_wait_count integer; v_service text; v_start timestamptz; v_body text;
begin
  select coalesce(value,'{}') into v_cfg from public.app_settings where key='control_center_settings';
  if not coalesce((v_cfg->>'waitlistEnabled')::boolean,false) then raise exception 'Η λίστα αναμονής είναι απενεργοποιημένη.'; end if;
  select id into v_member from public.members where auth_user_id=p_member_auth;
  if v_member is null then raise exception 'Δεν βρέθηκε καρτέλα μέλους.'; end if;
  select count(*) into v_wait_count from public.basement_waiting_list where member_id=p_member_auth and status='waiting';
  if v_wait_count>=coalesce((v_cfg->>'waitlistLimit')::integer,2) then raise exception 'Συμπληρώθηκε το όριο λίστας αναμονής.'; end if;
  insert into public.basement_waiting_list(slot_id,member_id,status,reason)
  values(p_slot,p_member_auth,'waiting',coalesce(nullif(p_reason,''),'capacity'))
  on conflict(slot_id,member_id,status) do update set created_at=excluded.created_at,reason=excluded.reason returning id into v_id;
  if coalesce((v_cfg->>'waitlistUpdateLink')::boolean,false) then
    select service,starts_at into v_service,v_start from public.basement_slots where id=p_slot;
    v_body:='Μπήκες στη λίστα αναμονής για '||coalesce(v_service,'προπόνηση')||'. Άνοιξε το Member Portal για ενημέρωση της θέσης σου.';
    insert into public.outbound_notifications(member_id,channel,title,body,status,scheduled_at,template_key)
    values(v_member,'push','Λίστα αναμονής',v_body,'queued',now(),'waitlist_joined');
  end if;
  return -v_id;
end $$;
revoke all on function basement_private.queue_waiting(bigint,uuid,text) from public,anon,authenticated;

create or replace function public.basement_record_consent(p_key text default 'booking_gdpr')
returns void language plpgsql security definer set search_path='public','pg_temp' as $$
declare v_member uuid;
begin
  if auth.uid() is null then raise exception 'Απαιτείται σύνδεση.'; end if;
  select id into v_member from members where auth_user_id=auth.uid() and active;
  if v_member is null then raise exception 'Δεν βρέθηκε ενεργή καρτέλα μέλους.'; end if;
  insert into member_consents(member_id,consent_key,accepted_at) values(v_member,coalesce(nullif(p_key,''),'booking_gdpr'),now())
  on conflict(member_id,consent_key) do update set accepted_at=excluded.accepted_at;
end $$;
revoke all on function public.basement_record_consent(text) from public,anon;
grant execute on function public.basement_record_consent(text) to authenticated;

create or replace function public.basement_member_save_health(p_data jsonb)
returns void language plpgsql security definer set search_path='public','pg_temp' as $$
declare v_member uuid; v_cfg jsonb;
begin
  if auth.uid() is null then raise exception 'Απαιτείται σύνδεση.'; end if;
  select coalesce(value,'{}') into v_cfg from app_settings where key='control_center_settings';
  if not coalesce((v_cfg->>'questionnaires')::boolean,false) then raise exception 'Το ερωτηματολόγιο είναι απενεργοποιημένο.'; end if;
  select id into v_member from members where auth_user_id=auth.uid() and active;
  if v_member is null then raise exception 'Δεν βρέθηκε ενεργή καρτέλα μέλους.'; end if;
  insert into member_health_profiles(member_id,emergency_contact,conditions,injuries,medications,ems_consent,consent_at,notes,updated_by,updated_at)
  values(v_member,left(coalesce(p_data->>'emergency_contact',''),500),left(coalesce(p_data->>'conditions',''),2000),left(coalesce(p_data->>'injuries',''),2000),left(coalesce(p_data->>'medications',''),2000),coalesce((p_data->>'ems_consent')::boolean,false),case when coalesce((p_data->>'ems_consent')::boolean,false) then now() else null end,left(coalesce(p_data->>'notes',''),2000),auth.uid(),now())
  on conflict(member_id) do update set emergency_contact=excluded.emergency_contact,conditions=excluded.conditions,injuries=excluded.injuries,medications=excluded.medications,ems_consent=excluded.ems_consent,consent_at=excluded.consent_at,notes=excluded.notes,updated_by=auth.uid(),updated_at=now();
end $$;
revoke all on function public.basement_member_save_health(jsonb) from public,anon;
grant execute on function public.basement_member_save_health(jsonb) to authenticated;

create or replace function public.basement_public_site_settings()
returns jsonb language sql stable security definer set search_path='public','pg_temp' as $$
 select jsonb_build_object(
  'businessName',coalesce(value->>'businessName','BASEMENT HEALTH CLUB'),
  'businessEmail',coalesce(value->>'businessEmail',''),
  'businessPhone',coalesce(value->>'businessPhone',''),
  'guestBooking',coalesce((value->>'guestBooking')::boolean,false)
 ) from app_settings where key='control_center_settings';
$$;
revoke all on function public.basement_public_site_settings() from public;
grant execute on function public.basement_public_site_settings() to anon,authenticated;

create or replace function public.basement_guest_request(p_name text,p_phone text,p_email text default '',p_service text default '',p_preferred text default '')
returns uuid language plpgsql security definer set search_path='public','pg_temp' as $$
declare v_cfg jsonb; v_id uuid;
begin
  select coalesce(value,'{}') into v_cfg from app_settings where key='control_center_settings';
  if not coalesce((v_cfg->>'guestBooking')::boolean,false) then raise exception 'Τα αιτήματα χωρίς λογαριασμό είναι απενεργοποιημένα.'; end if;
  if length(trim(coalesce(p_name,'')))<2 or length(trim(coalesce(p_phone,'')))<6 then raise exception 'Συμπλήρωσε όνομα και τηλέφωνο.'; end if;
  insert into basement_leads(name,phone,email,service,source,stage,notes)
  values(left(trim(p_name),120),left(trim(p_phone),60),left(trim(coalesce(p_email,'')),160),left(trim(coalesce(p_service,'')),120),'Website','New Lead',left('Αίτημα δοκιμαστικού/κράτησης χωρίς λογαριασμό. Προτίμηση: '||coalesce(p_preferred,''),1500))
  returning id into v_id;
  return v_id;
end $$;
revoke all on function public.basement_guest_request(text,text,text,text,text) from public;
grant execute on function public.basement_guest_request(text,text,text,text,text) to anon,authenticated;

create or replace function basement_private.member_service_allowed(p_service text,p_day date)
returns boolean language sql stable security definer set search_path='' as $$
 with cfg as(select coalesce(value,'{}') v from public.app_settings where key='control_center_settings'), me as(
  select m.id member_id, m.active, not exists(select 1 from public.member_packages x where x.member_id=m.id) is_new
  from public.profiles pr join public.members m on m.auth_user_id=pr.id
  where pr.id=auth.uid() and pr.active and pr.role='customer'
 )
 select exists(select 1 from public.services sv where lower(sv.name)=lower(p_service) and sv.active and sv.online_booking_enabled)
 and exists(select 1 from me where active or not coalesce((select (v->>'activeCustomersOnly')::boolean from cfg),true))
 and (
  not coalesce((select (v->>'creditsRequired')::boolean from cfg),true)
  or exists(select 1 from me where is_new and coalesce((select (v->>'newCustomerBooking')::boolean from cfg),false)
      and (coalesce((select (v->>'newCustomerOutsideSubscription')::boolean from cfg),false) or coalesce((select (v->>'skipNewCustomerChecks')::boolean from cfg),false)))
  or exists(
    select 1 from me join public.member_packages mp on mp.member_id=me.member_id
    join public.package_templates pt on pt.id=mp.package_template_id
    where mp.status::text in('active','scheduled') and mp.starts_on<=p_day
      and (mp.expires_on>=p_day or not coalesce((select (v->>'blockAfterExpiry')::boolean from cfg),true)
        or mp.expires_on+coalesce((select (v->>'maxAutoExtendDays')::integer from cfg),0)>=p_day)
      and (mp.frozen_until is null or mp.frozen_until<p_day) and pt.online_booking_enabled
      and basement_private.package_covers_service(mp.package_template_id,p_service)
  )
 );
$$;
revoke all on function basement_private.member_service_allowed(text,date) from public,anon,authenticated;

create or replace function basement_private.charge_booking(p_booking_id bigint,p_strict boolean default true)
returns boolean language plpgsql security definer set search_path='' as $$
declare b public.basement_bookings%rowtype; s public.basement_slots%rowtype;
  u public.basement_session_usage%rowtype; mp public.member_packages%rowtype;
  v_member uuid; v_day date; v_cfg jsonb; v_change integer;
begin
  select * into b from public.basement_bookings where id=p_booking_id for update;
  if not found then raise exception 'Η κράτηση δεν βρέθηκε.'; end if;
  select * into s from public.basement_slots where id=b.slot_id;
  v_day := (s.starts_at at time zone 'Europe/Athens')::date;
  select id into v_member from public.members where auth_user_id=b.member_id and active for update;
  select * into u from public.basement_session_usage where booking_id=b.id for update;
  if found and u.refunded_at is null then return true; end if;
  select coalesce(value,'{}') into v_cfg from public.app_settings where key='control_center_settings';
  select p.* into mp from public.member_packages p
  where p.member_id=v_member and (auth.uid() is null or public.is_staff() or exists(select 1 from public.package_templates pt where pt.id=p.package_template_id and pt.online_booking_enabled))
    and p.status::text in ('active','scheduled') and p.starts_on<=v_day
    and (not coalesce((v_cfg->>'blockAfterExpiry')::boolean,true) or p.expires_on+coalesce((v_cfg->>'maxAutoExtendDays')::integer,0)>=v_day)
    and (p.frozen_until is null or p.frozen_until<v_day)
    and (p.sessions_remaining is null or p.sessions_remaining>0)
    and basement_private.package_covers_service(p.package_template_id,s.service)
  order by p.expires_on,p.created_at,p.id limit 1 for update;
  if not found then
    if p_strict then raise exception using errcode='PBC01', message='Χρειάζεται διαθέσιμη συνεδρία σε πακέτο που καλύπτει την υπηρεσία και την ημερομηνία.'; end if;
    return false;
  end if;
  v_change:=case when mp.sessions_remaining is null then 0 else -1 end;
  update public.member_packages set sessions_remaining=sessions_remaining+v_change where id=mp.id;
  insert into public.basement_session_usage(booking_id,member_package_id,change,charged_at,refunded_at)
  values(b.id,mp.id,v_change,now(),null)
  on conflict(booking_id) do update set member_package_id=excluded.member_package_id,change=excluded.change,charged_at=excluded.charged_at,refunded_at=null;
  return true;
end $$;
revoke all on function basement_private.charge_booking(bigint,boolean) from public,anon,authenticated;

create or replace function basement_private.sync_booking_credit()
returns trigger language plpgsql security definer set search_path='' as $$
declare v_start timestamptz; v_service text; v_day date; v_cfg jsonb; v_package uuid; v_absences integer; v_free integer;
begin
  if tg_op='UPDATE' and new.status=old.status and new.slot_id=old.slot_id and new.credit_policy=old.credit_policy then return new; end if;
  select starts_at,service into v_start,v_service from public.basement_slots where id=new.slot_id;
  v_day:=(v_start at time zone 'Europe/Athens')::date;
  select coalesce(value,'{}') into v_cfg from public.app_settings where key='control_center_settings';
  if tg_op='INSERT' and new.credit_policy='booking' and v_start<=now() then raise exception using errcode='PBC01',message='Η ώρα έχει ήδη ξεκινήσει.'; end if;
  if tg_op='UPDATE' and new.slot_id<>old.slot_id then
    select member_package_id into v_package from public.basement_session_usage where booking_id=new.id and refunded_at is null;
    if v_package is not null and not exists(
      select 1 from public.member_packages p where p.id=v_package and p.status::text in('active','scheduled','completed') and p.starts_on<=v_day
      and (not coalesce((v_cfg->>'blockAfterExpiry')::boolean,true) or p.expires_on+coalesce((v_cfg->>'maxAutoExtendDays')::integer,0)>=v_day)
      and (p.frozen_until is null or p.frozen_until<v_day) and basement_private.package_covers_service(p.package_template_id,v_service)
    ) then raise exception using errcode='PBC01',message='Το πακέτο της κράτησης δεν καλύπτει τη νέα ώρα ή υπηρεσία.'; end if;
  end if;

  if new.status in('pending','booked') and new.credit_policy='booking' then
    perform basement_private.charge_booking(new.id,true);
  elsif new.status='completed' then
    perform basement_private.charge_booking(new.id,new.credit_policy='booking');
  elsif new.status='no_show' then
    v_free:=coalesce((v_cfg->>'freeAbsences')::integer,0);
    select count(*) into v_absences from public.basement_bookings where member_id=new.member_id and status in('no_show','late_cancel');
    if v_absences<=v_free then perform basement_private.refund_booking(new.id);
    else perform basement_private.charge_booking(new.id,false); end if;
  elsif new.status='late_cancel' then
    v_free:=coalesce((v_cfg->>'freeAbsences')::integer,0);
    select count(*) into v_absences from public.basement_bookings where member_id=new.member_id and status in('no_show','late_cancel');
    if not coalesce((v_cfg->>'lateCancelNoCredit')::boolean,false) or v_absences<=v_free then
      perform basement_private.refund_booking(new.id);
    else
      perform basement_private.charge_booking(new.id,false);
    end if;
  elsif new.status='cancelled' then
    perform basement_private.refund_booking(new.id);
  end if;
  return new;
end $$;
revoke all on function basement_private.sync_booking_credit() from public,anon,authenticated;

create or replace function public.basement_book(p_slot_id bigint,p_member_id uuid default null::uuid)
returns bigint language plpgsql security definer set search_path='public','pg_temp' as $$
declare
  v_actor uuid:=auth.uid(); v_role text; v_target uuid; v_slot public.basement_slots%rowtype;
  v_cfg jsonb:='{}'; v_is_admin boolean; v_member uuid; v_member_active boolean; v_is_new boolean; v_skip_new boolean;
  v_service public.services%rowtype; v_count integer; v_id bigint; v_status text; v_over_limit boolean:=false; v_limit_message text:='';
  v_package public.member_packages%rowtype; v_template public.package_templates%rowtype;
  v_local_start timestamp; v_now_local timestamp:=now() at time zone 'Europe/Athens';
  v_no_show_count integer; v_limit integer; v_unlock_cost integer; v_last_unlock integer; v_active_limit integer; v_enforce_limits boolean;
begin
  if v_actor is null then raise exception 'Απαιτείται σύνδεση.'; end if;
  select role::text into v_role from profiles where id=v_actor and active;
  if v_role is null then raise exception 'Απαιτείται ενεργή σύνδεση.'; end if;
  v_is_admin:=coalesce(v_role,'') in('owner','admin','reception'); v_target:=coalesce(p_member_id,v_actor);
  if v_target<>v_actor and not v_is_admin then raise exception 'Δεν επιτρέπεται κράτηση για άλλο μέλος.'; end if;
  if not exists(select 1 from profiles where id=v_target and role='customer' and active) then raise exception 'Δεν βρέθηκε ενεργό μέλος.'; end if;
  select coalesce(value,'{}') into v_cfg from app_settings where key='control_center_settings';
  v_enforce_limits:=not v_is_admin or not coalesce((v_cfg->>'adminExceedsLimits')::boolean,true);
  if not v_is_admin and coalesce((v_cfg->>'pauseBookings')::boolean,false) then raise exception 'Οι νέες κρατήσεις είναι προσωρινά κλειστές.'; end if;

  select * into v_slot from basement_slots where id=p_slot_id for update;
  if not found or not v_slot.enabled then raise exception 'Η ώρα δεν είναι διαθέσιμη.'; end if;
  v_local_start:=v_slot.starts_at at time zone 'Europe/Athens';
  if v_slot.starts_at<=now() then raise exception 'Η ώρα έχει ήδη ξεκινήσει.'; end if;
  if not v_is_admin and v_slot.starts_at<now()+make_interval(secs=>(coalesce((v_cfg->>'bookingMinHours')::numeric,0)*3600)::integer) then raise exception 'Η κράτηση πρέπει να γίνει νωρίτερα σύμφωνα με την πολιτική κρατήσεων.'; end if;
  if not v_is_admin and v_slot.starts_at>now()+make_interval(days=>coalesce((v_cfg->>'bookingMaxDays')::integer,14)) then raise exception 'Η ημερομηνία είναι έξω από το επιτρεπόμενο διάστημα κρατήσεων.'; end if;
  if nullif(v_cfg->>'maxAvailableDate','') is not null and v_local_start::date>(v_cfg->>'maxAvailableDate')::date then raise exception 'Η ημερομηνία δεν είναι διαθέσιμη.'; end if;
  if not v_is_admin and v_local_start::date=v_now_local::date+1 and v_now_local::time>coalesce(nullif(v_cfg->>'previousDayDeadline','')::time,'23:59') then raise exception 'Έληξε η προθεσμία κράτησης για την επόμενη ημέρα.'; end if;
  if v_local_start::time<coalesce(nullif(v_cfg->>'openingTime','')::time,'00:00') or v_local_start::time>coalesce(nullif(v_cfg->>'closingTime','')::time,'23:59') then raise exception 'Η ώρα είναι εκτός ωραρίου λειτουργίας.'; end if;

  select * into v_service from services where lower(name)=lower(v_slot.service) limit 1;
  if found and not v_is_admin and (not v_service.active or not v_service.online_booking_enabled) then raise exception 'Η υπηρεσία δεν δέχεται online κρατήσεις.'; end if;
  if coalesce((v_cfg->>'holidayRestrictions')::boolean,true) and exists(select 1 from closures c where c.closure_date=v_local_start::date and(c.service_id is null or c.service_id=v_service.id) and(c.starts_at is null or v_local_start::time>=c.starts_at) and(c.ends_at is null or v_local_start::time<c.ends_at)) then raise exception 'Η επιλεγμένη ώρα είναι κλειστή λόγω αργίας ή ειδικού ωραρίου.'; end if;

  select id,active into v_member,v_member_active from members where auth_user_id=v_target;
  if v_member is null then raise exception 'Δεν βρέθηκε καρτέλα μέλους.'; end if;
  v_is_new:=not exists(select 1 from member_packages where member_id=v_member);
  v_skip_new:=v_is_new and coalesce((v_cfg->>'newCustomerBooking')::boolean,false) and coalesce((v_cfg->>'skipNewCustomerChecks')::boolean,false);
  if not v_is_admin and v_is_new and not coalesce((v_cfg->>'newCustomerBooking')::boolean,false) then raise exception 'Οι κρατήσεις νέων μελών είναι απενεργοποιημένες.'; end if;
  if not v_is_admin and not v_is_new and not coalesce((v_cfg->>'existingCustomerBooking')::boolean,true) then raise exception 'Οι online κρατήσεις υπαρχόντων μελών είναι απενεργοποιημένες.'; end if;
  if not v_is_admin and coalesce((v_cfg->>'activeCustomersOnly')::boolean,true) and not coalesce(v_member_active,false) then raise exception 'Απαιτείται ενεργό μέλος.'; end if;
  if not v_is_admin and coalesce((v_cfg->>'gdprConsent')::boolean,false) and not exists(select 1 from member_consents where member_id=v_member and consent_key='booking_gdpr') then raise exception 'Χρειάζεται αποδοχή όρων/GDPR πριν από την κράτηση.'; end if;
  if not v_is_admin and basement_private.member_is_restricted(v_member,v_slot.service,v_slot.starts_at) then raise exception 'Υπάρχει περιορισμός κράτησης για αυτή την υπηρεσία ή ώρα.'; end if;
  if exists(select 1 from basement_bookings where slot_id=p_slot_id and member_id=v_target and status in('pending','booked')) then raise exception 'Το μέλος έχει ήδη κράτηση σε αυτή την ώρα.'; end if;
  if (not v_is_admin and coalesce((v_cfg->>'dependentAvailability')::boolean,false)) or not coalesce((v_cfg->>'allowDoubleBooking')::boolean,false) or not coalesce((v_cfg->>'overlapAvailability')::boolean,true) then
    if exists(select 1 from basement_bookings b join basement_slots s on s.id=b.slot_id where b.member_id=v_target and b.status in('pending','booked') and s.starts_at<v_slot.ends_at and s.ends_at>v_slot.starts_at) then raise exception 'Υπάρχει ήδη κράτηση που επικαλύπτει αυτή την ώρα.'; end if;
  end if;

  select mp.* into v_package from member_packages mp where mp.member_id=v_member and mp.status::text in('active','scheduled') and mp.starts_on<=v_local_start::date
    and (not coalesce((v_cfg->>'blockAfterExpiry')::boolean,true) or mp.expires_on+coalesce((v_cfg->>'maxAutoExtendDays')::integer,0)>=v_local_start::date)
    and (mp.frozen_until is null or mp.frozen_until<v_local_start::date) and (mp.sessions_remaining is null or mp.sessions_remaining>0)
    and basement_private.package_covers_service(mp.package_template_id,v_slot.service)
    order by mp.expires_on,mp.created_at limit 1;

  if not v_is_admin and v_is_new and v_package.id is null and not v_skip_new and not coalesce((v_cfg->>'newCustomerOutsideSubscription')::boolean,false) then raise exception 'Χρειάζεται ενεργή συνδρομή πριν από την πρώτη online κράτηση.'; end if;
  if not v_is_admin and not v_skip_new and coalesce((v_cfg->>'creditsRequired')::boolean,true) and v_package.id is null and not (v_is_new and coalesce((v_cfg->>'newCustomerOutsideSubscription')::boolean,false)) then
    select count(*) into v_count from basement_bookings where member_id=v_target and status in('pending','booked') and created_at>=date_trunc('month',now());
    if v_count>=coalesce((v_cfg->>'bookingsWithoutCredits')::integer,0) then raise exception 'Δεν υπάρχουν διαθέσιμες συνεδρίες ή ενεργό πακέτο.'; end if;
  end if;

  if not v_is_admin and not v_skip_new and not (coalesce((v_cfg->>'subscriptionOnly')::boolean,false) and v_package.id is null) then
    v_limit:=coalesce((v_cfg->>'noShowLimit')::integer,0);
    if v_limit>0 then
      select count(*) into v_no_show_count from basement_bookings where member_id=v_target and status='no_show';
      if v_no_show_count>=v_limit then
        select coalesce(max(no_show_count),0) into v_last_unlock from member_no_show_unlocks where member_id=v_member;
        if v_last_unlock<v_no_show_count then
          v_unlock_cost:=coalesce((v_cfg->>'noShowUnlockCost')::integer,0);
          if v_unlock_cost<=0 then raise exception 'Το όριο απουσιών έχει συμπληρωθεί. Επικοινώνησε με το γυμναστήριο.'; end if;
          if v_package.id is null or (v_package.sessions_remaining is not null and v_package.sessions_remaining<v_unlock_cost) then raise exception 'Χρειάζονται % διαθέσιμες συνεδρίες για ξεκλείδωμα μετά από απουσίες.',v_unlock_cost; end if;
          if v_package.sessions_remaining is not null then update member_packages set sessions_remaining=sessions_remaining-v_unlock_cost where id=v_package.id returning * into v_package; end if;
          insert into member_no_show_unlocks(member_id,no_show_count,cost,member_package_id) values(v_member,v_no_show_count,v_unlock_cost,v_package.id);
        end if;
      end if;
    end if;
  end if;

  if v_enforce_limits and not v_skip_new and not (coalesce((v_cfg->>'subscriptionOnly')::boolean,false) and v_package.id is null) then
    if v_package.id is not null then
      select * into v_template from package_templates where id=v_package.package_template_id;
      if coalesce(v_template.max_bookings_day,0)>0 and (select count(*) from basement_bookings b join basement_slots s on s.id=b.slot_id where b.member_id=v_target and basement_private.booking_counts_for_limit(b.status,b.moved_at,v_cfg) and (s.starts_at at time zone 'Europe/Athens')::date=v_local_start::date and (not coalesce((v_cfg->>'serviceBookingLimits')::boolean,false) or lower(s.service)=lower(v_slot.service)))>=v_template.max_bookings_day then v_over_limit:=true;v_limit_message:='Συμπληρώθηκε το ημερήσιο όριο κρατήσεων.'; end if;
      if not v_over_limit and coalesce(v_template.max_bookings_week,0)>0 and (select count(*) from basement_bookings b join basement_slots s on s.id=b.slot_id where b.member_id=v_target and basement_private.booking_counts_for_limit(b.status,b.moved_at,v_cfg) and date_trunc('week',s.starts_at at time zone 'Europe/Athens')=date_trunc('week',v_local_start) and (not coalesce((v_cfg->>'serviceBookingLimits')::boolean,false) or lower(s.service)=lower(v_slot.service)))>=v_template.max_bookings_week then v_over_limit:=true;v_limit_message:='Συμπληρώθηκε το εβδομαδιαίο όριο κρατήσεων.'; end if;
    end if;
    v_limit:=coalesce((v_cfg->>'maxBookingsPerPeriod')::integer,0);
    if not v_over_limit and v_limit>0 and (select count(*) from basement_bookings b join basement_slots s on s.id=b.slot_id where b.member_id=v_target and basement_private.booking_counts_for_limit(b.status,b.moved_at,v_cfg) and date_trunc('week',s.starts_at at time zone 'Europe/Athens')=date_trunc('week',v_local_start) and (not coalesce((v_cfg->>'serviceBookingLimits')::boolean,false) or lower(s.service)=lower(v_slot.service)))>=v_limit then v_over_limit:=true;v_limit_message:='Συμπληρώθηκε το εβδομαδιαίο όριο κρατήσεων.'; end if;
    v_active_limit:=coalesce((v_cfg->>'maxActiveBookings')::integer,0);
    if not v_over_limit and v_active_limit>0 and (select count(*) from basement_bookings b join basement_slots s on s.id=b.slot_id where b.member_id=v_target and b.status in('pending','booked') and s.ends_at>now())>=v_active_limit then v_over_limit:=true;v_limit_message:='Συμπληρώθηκε το όριο ενεργών κρατήσεων.'; end if;
  end if;
  if v_over_limit then
    if coalesce((v_cfg->>'overLimitToWaitlist')::boolean,false) and coalesce((v_cfg->>'waitlistEnabled')::boolean,false) and coalesce(v_service.waiting_list_enabled,true) then return basement_private.queue_waiting(p_slot_id,v_target,'limit'); end if;
    raise exception '%',v_limit_message;
  end if;

  select count(*) into v_count from basement_bookings where slot_id=p_slot_id and status in('pending','booked');
  if v_count>=v_slot.capacity or (not coalesce((v_cfg->>'autoConfirm')::boolean,true) and coalesce((v_cfg->>'unconfirmedToWaitlist')::boolean,false)) then
    if not coalesce((v_cfg->>'waitlistEnabled')::boolean,false) or (v_service.id is not null and not v_service.waiting_list_enabled) then raise exception 'Οι θέσεις εξαντλήθηκαν.'; end if;
    return basement_private.queue_waiting(p_slot_id,v_target,'capacity');
  end if;
  v_status:=case when coalesce((v_cfg->>'autoConfirm')::boolean,true) or (coalesce((v_cfg->>'autoConfirmExisting')::boolean,false) and v_package.id is not null) then 'booked' else 'pending' end;
  insert into basement_bookings(slot_id,member_id,status,credit_policy) values(p_slot_id,v_target,v_status,case when v_package.id is null then 'legacy' else 'booking' end) returning id into v_id;
  return v_id;
end $$;
revoke all on function public.basement_book(bigint,uuid) from public,anon;
grant execute on function public.basement_book(bigint,uuid) to authenticated;

create or replace function public.basement_cancel(p_booking_id bigint)
returns void language plpgsql security definer set search_path='public','pg_temp' as $$
declare b public.basement_bookings%rowtype; v_role text; v_admin boolean; v_start timestamptz; v_slot bigint; v_cfg jsonb; v_limit integer; v_actions integer; v_late boolean; v_late_count integer;
begin
  select role::text into v_role from profiles where id=auth.uid() and active;
  if v_role is null then raise exception 'Απαιτείται ενεργή σύνδεση.'; end if;
  v_admin:=v_role in('owner','admin','reception');
  select coalesce(value,'{}') into v_cfg from app_settings where key='control_center_settings';
  select * into b from basement_bookings where id=p_booking_id for update;
  if not found then raise exception 'Η κράτηση δεν βρέθηκε.'; end if;
  select starts_at into v_start from basement_slots where id=b.slot_id for update; v_slot:=b.slot_id;
  if b.member_id<>auth.uid() and not v_admin then raise exception 'Δεν επιτρέπεται η ακύρωση.'; end if;
  if b.status in('cancelled','late_cancel') then return; end if;
  if b.status not in('pending','booked') then raise exception 'Η κράτηση δεν είναι ενεργή.'; end if;
  if v_start<=now() and not v_admin then raise exception 'Η προπόνηση έχει ήδη ξεκινήσει.'; end if;

  if not v_admin then
    v_limit:=coalesce((v_cfg->>'cancelMoveLimit')::integer,0);
    if v_limit>0 then
      select (select count(*) from basement_bookings x where x.member_id=b.member_id and x.cancelled_at>=date_trunc('month',now()))+
             (select count(*) from basement_bookings x where x.member_id=b.member_id and x.moved_at>=date_trunc('month',now())) into v_actions;
      if v_actions>=v_limit then raise exception 'Συμπληρώθηκε το όριο ακυρώσεων/μεταφορών για τον μήνα.'; end if;
    end if;
  end if;

  v_late:=v_start<=now() or v_start<now()+make_interval(mins=>coalesce((v_cfg->>'cancelMinMinutes')::integer,0));
  if v_late and not v_admin then
    select count(*) into v_late_count from basement_bookings where member_id=b.member_id and status='late_cancel' and cancelled_at>=date_trunc('month',now());
    if v_late_count>=coalesce((v_cfg->>'lateCancelAllowedCount')::integer,0) then raise exception 'Έληξε η προθεσμία ακύρωσης.'; end if;
  end if;

  update basement_bookings set status=case when v_late then 'late_cancel' else 'cancelled' end,cancelled_at=now() where id=b.id;
  perform public.basement_promote_waiting(v_slot);
end $$;
revoke all on function public.basement_cancel(bigint) from public,anon;
grant execute on function public.basement_cancel(bigint) to authenticated;

create or replace function public.basement_move_booking(p_booking_id bigint,p_new_slot_id bigint)
returns void language plpgsql security definer set search_path='public','pg_temp' as $$
declare b basement_bookings%rowtype; old_s basement_slots%rowtype; new_s basement_slots%rowtype; v_cfg jsonb:='{}'; v_role text; v_admin boolean; v_count integer; v_new_status text; v_limit integer; v_actions integer; v_member uuid;
begin
  if auth.uid() is null then raise exception 'Απαιτείται σύνδεση.'; end if;
  select role::text into v_role from profiles where id=auth.uid() and active; v_admin:=coalesce(v_role,'') in('owner','admin','reception');
  select coalesce(value,'{}') into v_cfg from app_settings where key='control_center_settings';
  if not v_admin and coalesce((v_cfg->>'disableCustomerMove')::boolean,false) then raise exception 'Η μεταφορά από μέλη είναι απενεργοποιημένη.'; end if;
  select * into b from basement_bookings where id=p_booking_id for update; if not found or b.status not in('pending','booked') then raise exception 'Η κράτηση δεν είναι ενεργή.'; end if;
  if b.member_id<>auth.uid() and not v_admin then raise exception 'Δεν επιτρέπεται η μεταφορά.'; end if;
  select * into old_s from basement_slots where id=b.slot_id; select * into new_s from basement_slots where id=p_new_slot_id for update;
  if not found or not new_s.enabled then raise exception 'Η νέα ώρα δεν είναι διαθέσιμη.'; end if;
  if new_s.starts_at<=now() and not(v_admin and coalesce((v_cfg->>'moveToPastAdmin')::boolean,false)) then raise exception 'Δεν επιτρέπεται μεταφορά στο παρελθόν.'; end if;
  if not v_admin and old_s.starts_at<now()+make_interval(secs=>(coalesce((v_cfg->>'moveMinHours')::numeric,0)*3600)::integer) then raise exception 'Έληξε η προθεσμία μεταφοράς.'; end if;
  if not coalesce((v_cfg->>'changeServiceOnMove')::boolean,false) and new_s.service<>old_s.service then raise exception 'Δεν επιτρέπεται αλλαγή υπηρεσίας στη μεταφορά.'; end if;
  select id into v_member from members where auth_user_id=b.member_id;
  if not v_admin and basement_private.member_is_restricted(v_member,new_s.service,new_s.starts_at) then raise exception 'Υπάρχει περιορισμός κράτησης για τη νέα ώρα.'; end if;
  if not v_admin then
    v_limit:=coalesce((v_cfg->>'cancelMoveLimit')::integer,0);
    if v_limit>0 then select (select count(*) from basement_bookings x where x.member_id=b.member_id and x.cancelled_at>=date_trunc('month',now()))+(select count(*) from basement_bookings x where x.member_id=b.member_id and x.moved_at>=date_trunc('month',now())) into v_actions; if v_actions>=v_limit then raise exception 'Συμπληρώθηκε το όριο ακυρώσεων/μεταφορών για τον μήνα.'; end if; end if;
  end if;
  select count(*) into v_count from basement_bookings where slot_id=p_new_slot_id and status in('pending','booked'); if v_count>=new_s.capacity then raise exception 'Η νέα ώρα είναι πλήρης.'; end if;
  if exists(select 1 from basement_bookings where slot_id=p_new_slot_id and member_id=b.member_id and status in('pending','booked') and id<>p_booking_id) then raise exception 'Υπάρχει ήδη κράτηση στη νέα ώρα.'; end if;
  v_new_status:=case when coalesce((v_cfg->>'keepStatusOnMove')::boolean,true) then b.status else 'booked' end;
  update basement_bookings set slot_id=p_new_slot_id,status=v_new_status,moved_at=now(),moved_from_slot_id=b.slot_id where id=p_booking_id;
  perform public.basement_promote_waiting(b.slot_id);
end $$;
revoke all on function public.basement_move_booking(bigint,bigint) from public,anon;
grant execute on function public.basement_move_booking(bigint,bigint) to authenticated;

create or replace function public.basement_confirm_booking(p_booking_id bigint)
returns void language plpgsql security definer set search_path='public','pg_temp' as $$
declare b basement_bookings%rowtype; v_cfg jsonb; v_hours numeric; v_role text;
begin
  if auth.uid() is null then raise exception 'Απαιτείται σύνδεση.'; end if;
  select role::text into v_role from profiles where id=auth.uid() and active;
  select * into b from basement_bookings where id=p_booking_id for update;
  if not found or b.status<>'pending' then raise exception 'Η κράτηση δεν είναι σε αναμονή επιβεβαίωσης.'; end if;
  if b.member_id<>auth.uid() and coalesce(v_role,'') not in('owner','admin','reception') then raise exception 'Δεν επιτρέπεται η επιβεβαίωση.'; end if;
  if b.member_id=auth.uid() and b.waitlist_source_id is null and coalesce(v_role,'')='customer' then raise exception 'Η κράτηση περιμένει επιβεβαίωση από το γυμναστήριο.'; end if;
  select coalesce(value,'{}') into v_cfg from app_settings where key='control_center_settings';
  if b.waitlist_source_id is not null then
    v_hours:=greatest(.25,coalesce((v_cfg->>'waitlistConfirmationHours')::numeric,3));
    if b.created_at<now()-make_interval(secs=>(v_hours*3600)::integer) then
      update basement_bookings set status='cancelled',cancelled_at=now() where id=b.id;
      update basement_waiting_list set status='expired' where id=b.waitlist_source_id;
      perform public.basement_promote_waiting(b.slot_id);
      raise exception 'Η προθεσμία επιβεβαίωσης έληξε και η θέση δόθηκε στον επόμενο.';
    end if;
    update basement_waiting_list set status='accepted' where id=b.waitlist_source_id;
  end if;
  update basement_bookings set status='booked' where id=b.id;
end $$;
revoke all on function public.basement_confirm_booking(bigint) from public,anon;
grant execute on function public.basement_confirm_booking(bigint) to authenticated;

create or replace function public.basement_admin_booking_action(p_booking_id bigint,p_action text)
returns void language plpgsql security definer set search_path='public','pg_temp' as $$
declare v_role text; b public.basement_bookings%rowtype; v_member uuid; v_cfg jsonb; v_slot bigint; v_capacity integer;
begin
  select role::text into v_role from public.profiles where id=auth.uid() and active;
  if coalesce(v_role,'') not in('owner','admin','reception') then raise exception 'Δεν επιτρέπεται αυτή η ενέργεια.'; end if;
  select slot_id into v_slot from public.basement_bookings where id=p_booking_id;
  select capacity into v_capacity from public.basement_slots where id=v_slot for update;
  select * into b from public.basement_bookings where id=p_booking_id for update;
  if not found then raise exception 'Η κράτηση δεν βρέθηκε.'; end if;
  if b.slot_id<>v_slot then raise exception 'Η κράτηση μεταφέρθηκε. Ανανέωσε και δοκίμασε ξανά.'; end if;
  select coalesce(value,'{}') into v_cfg from public.app_settings where key='control_center_settings';
  select id into v_member from public.members where auth_user_id=b.member_id;
  if p_action in('complete','no_show') then
    if b.status not in('pending','booked','completed','no_show') then raise exception 'Κάνε πρώτα αναίρεση της ακύρωσης.'; end if;
    update public.basement_bookings set status=case when p_action='complete' then 'completed' else 'no_show' end,
      completed_at=coalesce(completed_at,now()),checked_in_at=case when p_action='complete' then coalesce(checked_in_at,now()) else null end where id=b.id;
    if p_action='complete' and v_member is not null and coalesce((v_cfg->>'checkIn')::boolean,true) then
      insert into public.gym_checkins(member_id,booking_id,method,notes) values(v_member,b.id,'automatic','Ολοκλήρωση ραντεβού') on conflict do nothing;
    elsif p_action='no_show' then delete from public.gym_checkins where booking_id=b.id; end if;
  elsif p_action='confirm' then update public.basement_bookings set status='booked' where id=b.id and status='pending';
  elsif p_action='pending' then update public.basement_bookings set status='pending' where id=b.id and status='booked';
  elsif p_action='paid' then update public.basement_bookings set payment_status='paid',paid_at=case when coalesce((v_cfg->>'paidDate')::boolean,true) then coalesce(paid_at,now()) else null end where id=b.id;
  elsif p_action='unpaid' then update public.basement_bookings set payment_status='unpaid',paid_at=null where id=b.id;
  elsif p_action='undo' then
    if b.status in('pending','booked') then return; end if;
    if (select count(*) from public.basement_bookings where slot_id=b.slot_id and status in('pending','booked') and id<>b.id)>=v_capacity then raise exception 'Η ώρα είναι πλήρης. Δεν έγινε αναίρεση.'; end if;
    update public.basement_bookings set status='booked',completed_at=null,checked_in_at=null,cancelled_at=null,
      credit_policy=case when (select starts_at>now() from public.basement_slots where id=b.slot_id) then 'booking' else credit_policy end where id=b.id;
    delete from public.gym_checkins where booking_id=b.id;
  else raise exception 'Άγνωστη ενέργεια.'; end if;
end $$;
revoke all on function public.basement_admin_booking_action(bigint,text) from public,anon;
grant execute on function public.basement_admin_booking_action(bigint,text) to authenticated;

create or replace function public.basement_promote_waiting(p_slot_id bigint)
returns bigint language plpgsql security definer set search_path='public','pg_temp' as $$
declare w basement_waiting_list%rowtype; v_id bigint; s basement_slots%rowtype; v_cfg jsonb; v_status text; v_member uuid; v_body text;
begin
  select coalesce(value,'{}') into v_cfg from app_settings where key='control_center_settings';
  if not coalesce((v_cfg->>'waitlistEnabled')::boolean,false) then return null; end if;
  select * into s from basement_slots where id=p_slot_id for update;
  if not found or not s.enabled or s.starts_at<=now() then return null; end if;
  if(select count(*) from basement_bookings where slot_id=s.id and status in('pending','booked'))>=s.capacity then return null; end if;
  v_status:=case when coalesce((v_cfg->>'autoConfirmWaitlist')::boolean,true) then 'booked' else 'pending' end;
  for w in select * from basement_waiting_list where slot_id=s.id and status='waiting' and coalesce(reason,'capacity')='capacity' order by created_at,id for update skip locked loop
    if not exists(select 1 from profiles where id=w.member_id and role='customer' and active) then continue; end if;
    begin
      insert into basement_bookings(slot_id,member_id,status,waitlist_source_id) values(s.id,w.member_id,v_status,w.id) returning id into v_id;
      update basement_waiting_list set status='promoted' where id=w.id;
      if coalesce((v_cfg->>'waitlistUpdateLink')::boolean,false) then
        select id into v_member from members where auth_user_id=w.member_id;
        v_body:=case when v_status='booked' then 'Άνοιξε το Member Portal: βρέθηκε θέση για '||s.service||'.'
          else 'Βρέθηκε θέση για '||s.service||'. Επιβεβαίωσέ την από το Member Portal μέσα σε '||coalesce((v_cfg->>'waitlistConfirmationHours')::integer,3)||' ώρες.' end;
        insert into outbound_notifications(member_id,channel,title,body,status,scheduled_at,template_key,booking_id)
        values(v_member,'push','Βρέθηκε θέση',v_body,'queued',now(),'waitlist_promoted',v_id);
      end if;
      return v_id;
    exception when sqlstate 'PBC01' or unique_violation then continue; end;
  end loop;
  return null;
end $$;
revoke all on function public.basement_promote_waiting(bigint) from public,anon,authenticated;

create or replace function public.basement_expire_waitlist_confirmations()
returns integer language plpgsql security definer set search_path='public','pg_temp' as $$
declare v_cfg jsonb; v_hours numeric; r record; v_count integer:=0;
begin
  if auth.uid() is null then raise exception 'Απαιτείται σύνδεση.'; end if;
  if not public.is_staff() then raise exception 'Δεν επιτρέπεται αυτή η ενέργεια.'; end if;
  select coalesce(value,'{}') into v_cfg from app_settings where key='control_center_settings';
  if coalesce((v_cfg->>'autoConfirmWaitlist')::boolean,true) then return 0; end if;
  v_hours:=greatest(.25,coalesce((v_cfg->>'waitlistConfirmationHours')::numeric,3));
  for r in
    select b.id,b.slot_id,w.id waiting_id
    from basement_bookings b join basement_waiting_list w on w.id=b.waitlist_source_id
    where b.status='pending' and w.status='promoted'
      and b.created_at<now()-make_interval(secs=>(v_hours*3600)::integer)
    order by b.created_at for update of b skip locked
  loop
    update basement_bookings set status='cancelled',cancelled_at=now() where id=r.id;
    update basement_waiting_list set status='expired' where id=r.waiting_id;
    v_count:=v_count+1;
    perform public.basement_promote_waiting(r.slot_id);
  end loop;
  return v_count;
end $$;
revoke all on function public.basement_expire_waitlist_confirmations() from public,anon;
grant execute on function public.basement_expire_waitlist_confirmations() to authenticated;


create or replace function public.basement_availability()
returns table(id bigint,service text,starts_at timestamptz,ends_at timestamptz,capacity integer,enabled boolean,reserved bigint)
language sql stable security definer set search_path='public','pg_temp' as $$
 with cfg as(select coalesce(value,'{}') v from app_settings where key='control_center_settings'),
 me as(
   select m.id,m.active,not exists(select 1 from member_packages x where x.member_id=m.id) is_new
   from profiles pr join members m on m.auth_user_id=pr.id
   where pr.id=auth.uid() and pr.active and pr.role='customer'
 )
 select s.id,s.service,s.starts_at,
 case when (select v->>'slotDurationMode' from cfg) ~ '^[0-9]+' then s.starts_at+make_interval(mins=>substring((select v->>'slotDurationMode' from cfg) from '^[0-9]+')::integer) else s.ends_at end,
 s.capacity,
 s.enabled
 and not(coalesce(((select v->>'holidayRestrictions' from cfg))::boolean,true) and exists(select 1 from closures c left join services sv2 on sv2.id=c.service_id where c.closure_date=(s.starts_at at time zone 'Europe/Athens')::date and(c.service_id is null or lower(sv2.name)=lower(s.service)) and(c.starts_at is null or(s.starts_at at time zone 'Europe/Athens')::time>=c.starts_at) and(c.ends_at is null or(s.starts_at at time zone 'Europe/Athens')::time<c.ends_at)))
 and (public.is_staff() or not coalesce((select (v->>'dependentAvailability')::boolean from cfg),false) or not exists(select 1 from basement_bookings b join basement_slots x on x.id=b.slot_id where b.member_id=auth.uid() and b.status in('pending','booked') and x.starts_at<s.ends_at and x.ends_at>s.starts_at))
 and (public.is_staff() or not exists(select 1 from me where basement_private.member_is_restricted(me.id,s.service,s.starts_at))),
 (select count(*) from basement_bookings b where b.slot_id=s.id and b.status in('pending','booked'))
 from basement_slots s left join services sv on lower(sv.name)=lower(s.service)
 where auth.uid() is not null
 and s.starts_at>=case when public.is_staff() then(now()-make_interval(days=>coalesce(((select v->>'adminVisibilityDays' from cfg))::integer,730))) else now() end
 and s.starts_at<case when nullif((select v->>'maxAvailableDate' from cfg),'') is not null then(((select v->>'maxAvailableDate' from cfg))::date+1)::timestamp at time zone 'Europe/Athens' else now()+make_interval(days=>coalesce(((select v->>'bookingMaxDays' from cfg))::integer,14)) end
 and(s.starts_at at time zone 'Europe/Athens')::time>=coalesce(nullif((select v->>'openingTime' from cfg),'')::time,'00:00')
 and(s.starts_at at time zone 'Europe/Athens')::time<=coalesce(nullif((select v->>'closingTime' from cfg),'')::time,'23:59')
 and(public.is_staff() or(
   sv.active and sv.online_booking_enabled
   and basement_private.member_service_allowed(s.service,(s.starts_at at time zone 'Europe/Athens')::date)
   and not coalesce((select (v->>'pauseBookings')::boolean from cfg),false)
   and (
     exists(select 1 from me where is_new and coalesce((select (v->>'newCustomerBooking')::boolean from cfg),false))
     or exists(select 1 from me where not is_new and coalesce((select (v->>'existingCustomerBooking')::boolean from cfg),true))
   )
   and s.starts_at>=now()+make_interval(secs=>(coalesce((select (v->>'bookingMinHours')::numeric from cfg),0)*3600)::integer)
   and s.starts_at<=now()+make_interval(days=>coalesce((select (v->>'bookingMaxDays')::integer from cfg),14))
   and not((s.starts_at at time zone 'Europe/Athens')::date=(now() at time zone 'Europe/Athens')::date+1 and(now() at time zone 'Europe/Athens')::time>coalesce(nullif((select v->>'previousDayDeadline' from cfg),'')::time,'23:59'))
 ))
 order by s.starts_at,s.service;
$$;
revoke all on function public.basement_availability() from public,anon;
grant execute on function public.basement_availability() to authenticated;

create or replace function public.basement_member_portal()
returns jsonb language plpgsql stable security definer set search_path='public','pg_temp' as $$
declare v_member uuid; v_cfg jsonb; v_today date:=(now() at time zone 'Europe/Athens')::date; v_health jsonb;
begin
 if not exists(select 1 from profiles where id=auth.uid() and active and role='customer') then raise exception 'Απαιτείται ενεργός λογαριασμός μέλους.'; end if;
 select id into v_member from members where auth_user_id=auth.uid() and active; if v_member is null then raise exception 'Δεν βρέθηκε ενεργή καρτέλα μέλους.'; end if;
 select coalesce(value,'{}') into v_cfg from app_settings where key='control_center_settings';
 if coalesce((v_cfg->>'questionnaires')::boolean,false) then select to_jsonb(h)-'member_id'-'updated_by' into v_health from member_health_profiles h where h.member_id=v_member; end if;
 return jsonb_build_object(
  'packages',coalesce((select jsonb_agg(jsonb_build_object('id',mp.id,'name',pt.name,'status',mp.status,'starts_on',mp.starts_on,'expires_on',mp.expires_on,'sessions_remaining',mp.sessions_remaining,'frozen_until',mp.frozen_until,'services',coalesce((select jsonb_agg(s.name order by s.name) from services s where s.active and s.online_booking_enabled and pt.online_booking_enabled and basement_private.package_covers_service(pt.id,s.name)),'[]'::jsonb)) order by mp.expires_on,mp.id) from member_packages mp join package_templates pt on pt.id=mp.package_template_id where mp.member_id=v_member),'[]'::jsonb),
  'services',coalesce((select jsonb_agg(s.name order by s.name) from services s where s.active and s.online_booking_enabled and basement_private.member_service_allowed(s.name,v_today)),'[]'::jsonb),
  'bookings',coalesce((select jsonb_agg(jsonb_build_object('id',b.id,'slot_id',s.id,'service',s.service,'starts_at',s.starts_at,'ends_at',s.ends_at,'status',b.status,'paid_at',case when coalesce((v_cfg->>'paidDate')::boolean,true) then b.paid_at else null end,'position_no',b.position_no,'waitlist_source_id',b.waitlist_source_id) order by s.starts_at,b.id) from basement_bookings b join basement_slots s on s.id=b.slot_id where b.member_id=auth.uid() and s.starts_at>=now()-interval '24 months'),'[]'::jsonb),
  'block_after_expiry',coalesce((v_cfg->>'blockAfterExpiry')::boolean,true),'grace_days',coalesce((v_cfg->>'maxAutoExtendDays')::integer,0),
  'completed_count',(select count(*) from basement_bookings where member_id=auth.uid() and status='completed'),
  'next_payment_on',(select next_payment_on from members where id=v_member),'last_payment_on',(select max(occurred_on) from financial_entries where member_id=v_member and kind='income' and occurred_on<=v_today),
  'terms_required',coalesce((v_cfg->>'termsPage')::boolean,false),'gdpr_required',coalesce((v_cfg->>'gdprConsent')::boolean,false),'gdpr_accepted',exists(select 1 from member_consents where member_id=v_member and consent_key='booking_gdpr'),
  'booking_paused',coalesce((v_cfg->>'pauseBookings')::boolean,false) or case when exists(select 1 from member_packages p where p.member_id=v_member) then not coalesce((v_cfg->>'existingCustomerBooking')::boolean,true) else not coalesce((v_cfg->>'newCustomerBooking')::boolean,false) end,
  'show_available_spots',coalesce((v_cfg->>'showAvailableSpots')::boolean,true),'fixed_positions',coalesce((v_cfg->>'fixedPositions')::boolean,false),'hide_fixed_positions',coalesce((v_cfg->>'hideFixedPositions')::boolean,false),
  'allow_without_package',not coalesce((v_cfg->>'creditsRequired')::boolean,true) or coalesce((v_cfg->>'bookingsWithoutCredits')::integer,0)>0 or (not exists(select 1 from member_packages x where x.member_id=v_member) and coalesce((v_cfg->>'newCustomerBooking')::boolean,false) and (coalesce((v_cfg->>'newCustomerOutsideSubscription')::boolean,false) or coalesce((v_cfg->>'skipNewCustomerChecks')::boolean,false))),
  'questionnaire_enabled',coalesce((v_cfg->>'questionnaires')::boolean,false),'health',coalesce(v_health,'{}'::jsonb),
  'business_email',coalesce(v_cfg->>'businessEmail',''),'business_phone',coalesce(v_cfg->>'businessPhone',''),'time_format',coalesce(v_cfg->>'timeFormat','24 ώρες'),'package_unit',coalesce(v_cfg->>'currency','Συνεδρίες')
 );
end $$;
revoke all on function public.basement_member_portal() from public,anon;
grant execute on function public.basement_member_portal() to authenticated;


create or replace function public.basement_member_portal_extras()
returns jsonb
language plpgsql
stable
security definer
set search_path='public','pg_temp'
as $$
declare
  v_member uuid;
  v_cfg jsonb;
  v_health jsonb:='{}'::jsonb;
  v_today date:=(now() at time zone 'Europe/Athens')::date;
  v_is_new boolean;
begin
  if not exists(select 1 from profiles where id=auth.uid() and active and role='customer') then
    raise exception 'Απαιτείται ενεργός λογαριασμός μέλους.';
  end if;
  select id into v_member from members where auth_user_id=auth.uid() and active;
  if v_member is null then raise exception 'Δεν βρέθηκε ενεργή καρτέλα μέλους.'; end if;
  select coalesce(value,'{}') into v_cfg from app_settings where key='control_center_settings';
  v_is_new:=not exists(select 1 from member_packages where member_id=v_member);

  if coalesce((v_cfg->>'questionnaires')::boolean,false) then
    select coalesce(to_jsonb(h)-'member_id'-'updated_by','{}'::jsonb)
      into v_health
    from member_health_profiles h
    where h.member_id=v_member;
  end if;

  return jsonb_build_object(
    'services',coalesce((
      select jsonb_agg(s.name order by s.name)
      from services s
      where s.active and s.online_booking_enabled
        and basement_private.member_service_allowed(s.name,v_today)
    ),'[]'::jsonb),
    'booking_meta',coalesce((
      select jsonb_agg(jsonb_build_object(
        'id',b.id,
        'position_no',b.position_no,
        'waitlist_source_id',b.waitlist_source_id
      ))
      from basement_bookings b
      where b.member_id=auth.uid()
    ),'[]'::jsonb),
    'booking_paused',
      coalesce((v_cfg->>'pauseBookings')::boolean,false)
      or case when v_is_new
        then not coalesce((v_cfg->>'newCustomerBooking')::boolean,false)
        else not coalesce((v_cfg->>'existingCustomerBooking')::boolean,true)
      end,
    'allow_without_package',
      not coalesce((v_cfg->>'creditsRequired')::boolean,true)
      or coalesce((v_cfg->>'bookingsWithoutCredits')::integer,0)>0
      or (v_is_new
          and coalesce((v_cfg->>'newCustomerBooking')::boolean,false)
          and (coalesce((v_cfg->>'newCustomerOutsideSubscription')::boolean,false)
               or coalesce((v_cfg->>'skipNewCustomerChecks')::boolean,false))),
    'gdpr_required',coalesce((v_cfg->>'gdprConsent')::boolean,false),
    'gdpr_accepted',exists(select 1 from member_consents where member_id=v_member and consent_key='booking_gdpr'),
    'fixed_positions',coalesce((v_cfg->>'fixedPositions')::boolean,false),
    'hide_fixed_positions',coalesce((v_cfg->>'hideFixedPositions')::boolean,false),
    'paid_date',coalesce((v_cfg->>'paidDate')::boolean,true),
    'service_subscription_dates',coalesce((v_cfg->>'serviceSubscriptionDates')::boolean,true),
    'questionnaire_enabled',coalesce((v_cfg->>'questionnaires')::boolean,false),
    'health',coalesce(v_health,'{}'::jsonb),
    'business_email',coalesce(v_cfg->>'businessEmail',''),
    'business_phone',coalesce(v_cfg->>'businessPhone',''),
    'time_format',coalesce(v_cfg->>'timeFormat','24 ώρες'),
    'package_unit',coalesce(v_cfg->>'currency','Συνεδρίες')
  );
end $$;
revoke all on function public.basement_member_portal_extras() from public,anon;
grant execute on function public.basement_member_portal_extras() to authenticated;

notify pgrst,'reload schema';
