"use client";
import {useEffect,useState} from "react";
import {api} from "../../lib/supabase-rest";
import {accessToken} from "../../lib/session";
import {activityOptions,budgetOptions,defaultNutritionRules,GeneratedNutritionPlan,goalOptions,NutritionIntake,NutritionRules,nutritionRulesSchema,trainingOptions,NutritionTargets} from "../../lib/nutrition-ai";

type Member={id:string;full_name:string;auth_user_id:string|null};
type Measurement={id:number;measured_on:string;weight_kg:number|null;body_fat_percent:number|null;muscle_mass_kg:number|null;height_cm:number|null;visceral_fat:number|null;metabolic_age:number|null;bmr_kcal:number|null};
type Props={members:Member[];onClose:()=>void;onUse:(memberId:string,plan:GeneratedNutritionPlan,intake:NutritionIntake,targets:NutritionTargets)=>void};
const today=()=>new Date().toLocaleDateString("en-CA",{timeZone:"Europe/Athens"});
const numberOrNull=(value:FormDataEntryValue|null)=>String(value||"").trim()===""?null:Number(value);
async function responseJson(response:Response){const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.message||"Η ενέργεια δεν ολοκληρώθηκε.");return data}

export default function AiNutritionPlanner({members,onClose,onUse}:Props){
 const [memberId,setMemberId]=useState(""),[measurements,setMeasurements]=useState<Measurement[]>([]),[plan,setPlan]=useState<GeneratedNutritionPlan|null>(null),[targets,setTargets]=useState<NutritionTargets|null>(null),[intake,setIntake]=useState<NutritionIntake|null>(null),[measurementId,setMeasurementId]=useState<number|undefined>(),[instruction,setInstruction]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const selected=members.find(m=>m.id===memberId);
 useEffect(()=>{setPlan(null);setTargets(null);setIntake(null);setMeasurementId(undefined);if(!memberId){setMeasurements([]);return}void api(`/rest/v1/member_measurements?member_id=eq.${memberId}&select=id,measured_on,weight_kg,body_fat_percent,muscle_mass_kg,height_cm,visceral_fat,metabolic_age,bmr_kcal&order=measured_on.desc&limit=30`,localStorage.getItem("basement_access_token")||"").then(async r=>{if(r.ok)setMeasurements(await r.json())})},[memberId]);
 const latest=measurements[0];
 async function generate(form:HTMLFormElement,revision=false){
  setBusy(true);setError("");setNotice("");
  try{
   let nextIntake=intake;
   if(!revision){const fd=new FormData(form),times=String(fd.get("mealTimes")||"").split(/[,\s]+/).map(x=>x.trim()).filter(Boolean);nextIntake={memberId:String(fd.get("memberId")),name:String(fd.get("name")||""),sex:String(fd.get("sex")) as NutritionIntake["sex"],age:Number(fd.get("age")),heightCm:Number(fd.get("heightCm")),weightKg:Number(fd.get("weightKg")),bodyFatPercent:numberOrNull(fd.get("bodyFatPercent")),muscleMassKg:numberOrNull(fd.get("muscleMassKg")),visceralFat:numberOrNull(fd.get("visceralFat")),metabolicAge:numberOrNull(fd.get("metabolicAge")),bmrKcal:numberOrNull(fd.get("bmrKcal")),goal:String(fd.get("goal")) as NutritionIntake["goal"],activity:String(fd.get("activity")) as NutritionIntake["activity"],training:String(fd.get("training")) as NutritionIntake["training"],trainingDays:Number(fd.get("trainingDays")),allergies:String(fd.get("allergies")||""),excludedFoods:String(fd.get("excludedFoods")||""),preferredFoods:String(fd.get("preferredFoods")||""),medicalNotes:String(fd.get("medicalNotes")||""),mealsPerDay:Number(fd.get("mealsPerDay")),mealTimes:times,budget:String(fd.get("budget")) as NutritionIntake["budget"],measuredOn:String(fd.get("measuredOn"))};}
   if(!nextIntake)throw Error("Συμπλήρωσε πρώτα τη φόρμα.");
   if(revision&&!instruction.trim())throw Error("Γράψε τι θέλεις να αλλάξει.");
   const token=await accessToken();
   const data=await responseJson(await fetch("/api/nutrition/generate",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({intake:nextIntake,instruction:revision?instruction.trim():undefined,previousPlan:revision?plan:undefined,measurementId})}));
   setPlan(data.plan);setTargets(data.targets);setIntake(nextIntake);setMeasurementId(data.measurementId);setInstruction("");setNotice(revision?"Το πλάνο αναδημιουργήθηκε με τις αλλαγές σου.":"Το AI δημιούργησε προσχέδιο. Έλεγξέ το πριν το αποθηκεύσεις.");
  }catch(e){setError(e instanceof Error?e.message:"Δεν δημιουργήθηκε το πλάνο.")}finally{setBusy(false)}
 }
 return <div className="ai-planner-shell"><div className="nutrition-actions"><button onClick={onClose}>‹ Πίσω στα πλάνα</button><span className="ai-badge">AI Nutrition Planner</span></div>{error&&<p className="nutrition-error" role="alert">{error}</p>}{notice&&<p className="nutrition-success" role="status">{notice}</p>}
 {!plan?<form className="ai-intake" onSubmit={e=>{e.preventDefault();void generate(e.currentTarget)}}><section className="ai-form-section"><div><small>1 · ΠΕΛΑΤΗΣ</small><h2>Στοιχεία & μετρήσεις</h2></div><div className="ai-form-grid" key={`${memberId}-${latest?.id||0}`}><label>Μέλος<select name="memberId" required value={memberId} onChange={e=>setMemberId(e.target.value)}><option value="">Επίλεξε μέλος</option>{members.map(m=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select></label><label>Όνομα<input name="name" required defaultValue={selected?.full_name||""} key={selected?.id||"name"}/></label><label>Φύλο<select name="sex" defaultValue="male"><option value="male">Άνδρας</option><option value="female">Γυναίκα</option><option value="other">Άλλο / δεν δηλώνεται</option></select></label><label>Ηλικία<input name="age" type="number" min="14" max="100" required/></label><label>Ύψος (cm)<input name="heightCm" type="number" min="100" max="240" step="0.1" required defaultValue={latest?.height_cm??""}/></label><label>Βάρος (kg)<input name="weightKg" type="number" min="30" max="350" step="0.1" required defaultValue={latest?.weight_kg??""}/></label><label>Λίπος (%)<input name="bodyFatPercent" type="number" min="2" max="70" step="0.1" defaultValue={latest?.body_fat_percent??""}/></label><label>Μυϊκή μάζα (kg)<input name="muscleMassKg" type="number" min="0" max="250" step="0.1" defaultValue={latest?.muscle_mass_kg??""}/></label><label>Σπλαχνικό λίπος<input name="visceralFat" type="number" min="0" max="100" step="0.1" defaultValue={latest?.visceral_fat??""}/></label><label>Μεταβολική ηλικία<input name="metabolicAge" type="number" min="1" max="130" defaultValue={latest?.metabolic_age??""}/></label><label>BMR (προαιρετικό)<input name="bmrKcal" type="number" min="500" max="6000" defaultValue={latest?.bmr_kcal??""}/></label><label>Ημερομηνία μέτρησης<input name="measuredOn" type="date" required defaultValue={today()}/></label></div>{measurements.length>0&&<MeasurementProgress rows={measurements}/>}</section>
 <section className="ai-form-section"><div><small>2 · ΣΤΟΧΟΣ</small><h2>Στόχος & προπόνηση</h2></div><div className="ai-form-grid"><label>Στόχος<select name="goal" defaultValue="fat_loss">{Object.entries(goalOptions).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Δραστηριότητα<select name="activity" defaultValue="moderate">{Object.entries(activityOptions).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Τύπος προπόνησης<select name="training" defaultValue="EMS">{trainingOptions.map(value=><option key={value}>{value}</option>)}</select></label><label>Προπονήσεις / εβδομάδα<input name="trainingDays" type="number" min="0" max="14" defaultValue="3" required/></label></div></section>
 <section className="ai-form-section"><div><small>3 · ΠΡΟΤΙΜΗΣΕΙΣ</small><h2>Διατροφή & καθημερινότητα</h2></div><div className="ai-form-grid"><label>Αλλεργίες / δυσανεξίες<textarea name="allergies" placeholder="π.χ. λακτόζη, ξηροί καρποί"/></label><label>Τρόφιμα που δεν τρώει<textarea name="excludedFoods" placeholder="π.χ. κοτόπουλο"/></label><label>Τρόφιμα που προτιμά<textarea name="preferredFoods"/></label><label>Ιατρικές παρατηρήσεις<textarea name="medicalNotes" placeholder="Προαιρετικό · για έλεγχο από επαγγελματία"/></label><label>Γεύματα ανά ημέρα<input name="mealsPerDay" type="number" min="2" max="8" defaultValue="4" required/></label><label>Ώρες γευμάτων<input name="mealTimes" defaultValue="08:00, 12:30, 17:00, 21:00" placeholder="08:00, 12:30, 17:00, 21:00" required/></label><label>Budget<select name="budget" defaultValue="standard">{Object.entries(budgetOptions).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div></section><p className="ai-review-note">Το αποτέλεσμα δημιουργείται ως προσχέδιο και χρειάζεται έλεγχο πριν δημοσιευτεί στο μέλος.</p><button className="primary ai-generate" disabled={busy||!memberId}>{busy?"Το AI δημιουργεί το πλάνο…":"✦ Δημιουργία με AI"}</button></form>:
 <section className="ai-result"><header><div><small>AI ΠΡΟΣΧΕΔΙΟ</small><h2>{plan.title}</h2><p>{plan.summary}</p></div><button onClick={()=>{setPlan(null);setTargets(null)}}>Νέα φόρμα</button></header>{targets&&<div className="ai-macro-grid"><article><small>Θερμίδες</small><strong>{targets.calories}</strong><span>kcal / ημέρα</span></article><article><small>Πρωτεΐνη</small><strong>{targets.protein}g</strong><span>/ ημέρα</span></article><article><small>Υδατάνθρακες</small><strong>{targets.carbs}g</strong><span>/ ημέρα</span></article><article><small>Λιπαρά</small><strong>{targets.fat}g</strong><span>/ ημέρα</span></article></div>}<div className="ai-week-preview">{plan.days.map(day=><details key={day.day}><summary><b>{day.day}</b><span>{Math.round(day.totalKcal)} kcal · Π {Math.round(day.totalProtein)}g · Υ {Math.round(day.totalCarbs)}g · Λ {Math.round(day.totalFat)}g</span></summary>{day.trainingNote&&<p>{day.trainingNote}</p>}{day.meals.map((meal,index)=><article key={index}><div><b>{meal.time} · {meal.name}</b>{meal.timing!=="regular"&&<em>{meal.timing==="pre_workout"?"Pre-workout":"Post-workout"}</em>}</div><p>{meal.items.map(item=>`${item.food} ${item.grams}g`).join(" · ")}</p><small>{Math.round(meal.kcal)} kcal · Π {Math.round(meal.protein)}g · Υ {Math.round(meal.carbs)}g · Λ {Math.round(meal.fat)}g</small>{meal.alternatives.length>0&&<details><summary>Εναλλακτικές</summary>{meal.alternatives.map((a,i)=><p key={i}><b>{a.label}:</b> {a.items.map(x=>`${x.food} ${x.grams}g`).join(", ")}</p>)}</details>}</article>)}</details>)}</div><ShoppingList plan={plan}/><form className="ai-revision" onSubmit={e=>{e.preventDefault();void generate(e.currentTarget,true)}}><label>Τι θέλεις να αλλάξει;<textarea value={instruction} onChange={e=>setInstruction(e.target.value)} placeholder="π.χ. βγάλε το κοτόπουλο, κάνε το πιο οικονομικό, δώσε περισσότερη πρωτεΐνη…" maxLength={1200}/></label><button disabled={busy||!instruction.trim()}>{busy?"Αναδημιουργία…":"✦ Αναδημιουργία με AI"}</button></form><div className="nutrition-actions"><button className="primary" onClick={()=>intake&&targets&&onUse(intake.memberId,plan,intake,targets)}>Μεταφορά στον επεξεργαστή & τελικός έλεγχος</button><button onClick={()=>window.print()}>Εκτύπωση προσχεδίου</button></div></section>}
 <NutritionAiSettings/>
 </div>
}

function ShoppingList({plan}:{plan:GeneratedNutritionPlan}){return <section className="ai-shopping"><h3>Λίστα αγορών εβδομάδας</h3><div>{plan.shoppingList.map(group=><article key={group.category}><b>{group.category}</b>{group.items.map((item,i)=><span key={i}>{item.name} · {item.quantity}</span>)}</article>)}</div></section>}
function MeasurementProgress({rows}:{rows:Measurement[]}){const data=[...rows].reverse().slice(-12);const path=(key:"weight_kg"|"body_fat_percent"|"muscle_mass_kg")=>{const values=data.map(x=>Number(x[key])).filter(Number.isFinite);if(values.length<2)return "";const min=Math.min(...values),max=Math.max(...values),span=max-min||1;return data.map((x,i)=>`${i?"L":"M"} ${i/(data.length-1)*280} ${70-(Number(x[key])-min)/span*60}`).join(" ")};return <div className="measurement-progress"><div><b>Εξέλιξη μετρήσεων</b><small>{rows.length} καταχωρήσεις</small></div><svg viewBox="0 0 280 80" role="img" aria-label="Εξέλιξη βάρους, λίπους και μυϊκής μάζας"><path d={path("weight_kg")} className="weight"/><path d={path("body_fat_percent")} className="fat"/><path d={path("muscle_mass_kg")} className="muscle"/></svg><p><span>● Βάρος</span><span>● Λίπος</span><span>● Μυϊκή μάζα</span></p></div>}

function NutritionAiSettings(){const [open,setOpen]=useState(false),[rules,setRules]=useState<NutritionRules>(defaultNutritionRules),[busy,setBusy]=useState(false),[message,setMessage]=useState("");useEffect(()=>{if(!open)return;void api("/rest/v1/nutrition_ai_settings?id=eq.true&select=rules",localStorage.getItem("basement_access_token")||"").then(async r=>{if(r.ok){const row=(await r.json())[0];const parsed=nutritionRulesSchema.safeParse(row?.rules);if(parsed.success)setRules(parsed.data)}})},[open]);const goals=Object.keys(goalOptions) as Array<keyof typeof goalOptions>;async function save(){setMessage("");const parsed=nutritionRulesSchema.safeParse(rules);if(!parsed.success){setMessage("Έλεγξε τις τιμές των κανόνων.");return}setBusy(true);const response=await api("/rest/v1/nutrition_ai_settings?id=eq.true",localStorage.getItem("basement_access_token")||"",{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({rules:parsed.data})});setBusy(false);setMessage(response.ok?"Οι κανόνες αποθηκεύτηκαν και θα ισχύσουν στην επόμενη δημιουργία.":"Δεν αποθηκεύτηκαν οι κανόνες.")}return <details className="ai-settings" open={open} onToggle={e=>setOpen((e.currentTarget as HTMLDetailsElement).open)}><summary>⚙ Ρυθμίσεις AI θερμίδων & macros</summary>{open&&<div><p>Οι τιμές αυτές εφαρμόζονται πριν κληθεί το AI.</p><div className="ai-rules-grid"><label>Λίπος (g/kg)<input type="number" step="0.1" value={rules.fatPerKg} onChange={e=>setRules({...rules,fatPerKg:Number(e.target.value)})}/></label><label>Ελάχιστες kcal γυναίκας<input type="number" value={rules.minimumCaloriesFemale} onChange={e=>setRules({...rules,minimumCaloriesFemale:Number(e.target.value)})}/></label><label>Ελάχιστες kcal άνδρα<input type="number" value={rules.minimumCaloriesMale} onChange={e=>setRules({...rules,minimumCaloriesMale:Number(e.target.value)})}/></label><label>Απόκλιση στόχου ± %<input type="number" value={rules.targetTolerancePercent} onChange={e=>setRules({...rules,targetTolerancePercent:Number(e.target.value)})}/></label>{goals.map(goal=><fieldset key={goal}><legend>{goalOptions[goal]}</legend><label>Μεταβολή θερμίδων %<input type="number" step="1" value={Math.round((rules.goalAdjustments[goal]||0)*100)} onChange={e=>setRules({...rules,goalAdjustments:{...rules.goalAdjustments,[goal]:Number(e.target.value)/100}})}/></label><label>Πρωτεΐνη g/kg<input type="number" step="0.1" value={rules.proteinPerKg[goal]||1.8} onChange={e=>setRules({...rules,proteinPerKg:{...rules.proteinPerKg,[goal]:Number(e.target.value)}})}/></label></fieldset>)}</div><button disabled={busy} onClick={()=>void save()}>{busy?"Αποθήκευση…":"Αποθήκευση κανόνων"}</button>{message&&<p>{message}</p>}</div>}</details>}
