"use client";
import {useEffect,useRef,useState} from "react";
import {api} from "../../lib/supabase-rest";
import {athensDay} from "../../lib/reference-calendar";
type Slot={id:number;service:string;starts_at:string;ends_at:string;capacity:number;enabled:boolean;reserved:number};
type Service={id:string;name:string;duration_minutes:number};
export default function AppointmentLauncher({seed,mode,day,slots,services,onClose,onChoose,onOpened,getBookingState}:{seed:{service?:string;time?:string};mode:"book"|"slot";day:string;slots:Slot[];services:Service[];onClose:()=>void;onChoose:(s:Slot)=>void;onOpened:()=>Promise<void>;getBookingState?:(slot:Slot)=>{disabled:boolean;label:string;description:string}}){
 const dialog=useRef<HTMLDialogElement>(null),[service,setService]=useState(services.find(s=>s.name===seed.service)?.id||services[0]?.id||""),[date,setDate]=useState(day||athensDay()),[time,setTime]=useState(seed.time||"09:00"),[duration,setDuration]=useState(services.find(s=>s.name===seed.service)?.duration_minutes||services[0]?.duration_minutes||60),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{dialog.current?.showModal()},[]);
 useEffect(()=>{if(services.length&&!services.some(item=>item.id===service)){setService(services[0].id);setDuration(services[0].duration_minutes)}},[services,service]);
 const selected=services.find(s=>s.id===service),fmt=new Intl.DateTimeFormat("el-GR",{timeZone:"Europe/Athens",hour:"2-digit",minute:"2-digit",hourCycle:"h23"});
 const options=slots.filter(s=>s.service===selected?.name&&s.enabled&&new Date(s.starts_at)>new Date()&&new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Athens"}).format(new Date(s.starts_at))===date);
 async function open(){setBusy(true);setError("");try{const r=await api("/rest/v1/rpc/basement_open_slot",localStorage.getItem("basement_access_token")||"",{method:"POST",body:JSON.stringify({p_service:service,p_day:date,p_time:time,p_duration:duration})});if(!r.ok){const d=await r.json();throw Error(d.message)}await onOpened();onClose()}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <dialog ref={dialog} className="quick-booking-dialog reference-launcher" onCancel={e=>{e.preventDefault();if(!busy)onClose()}}><header><h2>{mode==="slot"?"Άνοιγμα ώρας για κρατήσεις":"Νέο ραντεβού"}</h2><button aria-label="Κλείσιμο" disabled={busy} onClick={onClose}>×</button></header><p>{mode==="slot"?"Τα μέλη θα βλέπουν αυτή την ώρα ως διαθέσιμη.":"Επίλεξε υπηρεσία και ώρα. Στη συνέχεια διάλεξε το μέλος."}</p><label>Υπηρεσία<select value={service} onChange={e=>{setService(e.target.value);setDuration(services.find(s=>s.id===e.target.value)?.duration_minutes||60)}}>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Ημερομηνία<input type="date" min={athensDay()} value={date} onChange={e=>setDate(e.target.value)}/></label>{mode==="slot"?<><label>Ώρα<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><label>Διάρκεια (λεπτά)<input type="number" min="5" max="240" value={duration} onChange={e=>setDuration(+e.target.value)}/></label><button disabled={busy||!service||!date||!time} className="primary" onClick={()=>void open()}>{busy?"Αποθήκευση…":"Άνοιγμα ώρας"}</button></>:<div className="quick-booking-results">{options.length?options.map(s=>{const state=getBookingState?.(s);return <button type="button" key={s.id} disabled={state?.disabled} title={state?.description} onClick={()=>onChoose(s)}><b>{fmt.format(new Date(s.starts_at))}–{fmt.format(new Date(s.ends_at))}</b><span>{state?.description||`${Math.max(0,s.capacity-s.reserved)} διαθέσιμες θέσεις`}</span></button>}):<p>Δεν υπάρχουν ανοικτές ώρες αυτή την ημέρα.</p>}</div>}{error&&<p role="alert" className="booking-error">{error}</p>}</dialog>
}
