"use client";
import {useEffect,useState} from "react";
import {api} from "../../lib/supabase-rest";
import {athensDay,shiftDay} from "../../lib/reference-calendar";
import type {ServiceConfig} from "./reference-settings";
type Rule={id:string;service_id:string;weekday:number;start_time:string;duration_minutes:number;valid_from:string;valid_until:string;active:boolean};
type Closure={id:string;closure_date:string;closure_type:string;reason:string;service_id:string|null};
const days=[[1,"Δευ"],[2,"Τρι"],[3,"Τετ"],[4,"Πεμ"],[5,"Παρ"],[6,"Σαβ"],[7,"Κυρ"]] as const;
export default function AvailabilitySettings({services}:{services:ServiceConfig[]}){
 const [rules,setRules]=useState<Rule[]>([]),[closures,setClosures]=useState<Closure[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[filter,setFilter]=useState("");
 const [draft,setDraft]=useState({service_id:services[0]?.id||"",weekdays:[1,2,3,4,5],start_time:"09:00",duration_minutes:60,valid_from:athensDay(),valid_until:shiftDay(athensDay(),365)});
 const [closure,setClosure]=useState({closure_date:"",closure_type:"closed_day",reason:"",service_id:""});
 const token=()=>localStorage.getItem("basement_access_token")||"";
 async function load(){try{const [a,b]=await Promise.all([api("/rest/v1/availability_rules?select=*&order=service_id,weekday,start_time",token()),api("/rest/v1/closures?select=*&order=closure_date.desc",token())]);if(!a.ok||!b.ok)throw Error("Δεν φορτώθηκε το ωράριο.");setRules(await a.json());setClosures(await b.json())}catch(e){setMessage(String(e))}}
 useEffect(()=>{void load()},[]);
 async function save(body:object){setBusy(true);setMessage("");try{const r=await api("/rest/v1/rpc/basement_save_availability",token(),{method:"POST",body:JSON.stringify(body)});if(!r.ok){const d=await r.json();throw Error(d.message)}await load();setMessage("Η διαθεσιμότητα αποθηκεύτηκε και το ημερολόγιο ενημερώθηκε. Οι κρατήσεις διατηρήθηκαν.");window.dispatchEvent(new Event("basement-settings-changed"))}catch(e){setMessage(e instanceof Error?e.message:"Δεν αποθηκεύτηκε το ωράριο.")}finally{setBusy(false)}}
 function edit(id:string,key:keyof Rule,value:unknown){setRules(all=>all.map(r=>r.id===id?{...r,[key]:value}:r))}
 return <section className="reference-panel reference-settings-card"><h2>Επαναλαμβανόμενη διαθεσιμότητα</h2><p>Ανοίγει αυτόματα τις ώρες σε Admin και Member Portal. Οι υπάρχουσες κρατήσεις δεν διαγράφονται.</p>{message&&<p className="notice" role="status">{message}</p>}<form onSubmit={e=>{e.preventDefault();void save({p_rule:draft})}}><div className="reference-availability-create"><label>Υπηρεσία<select value={draft.service_id} onChange={e=>setDraft({...draft,service_id:e.target.value,duration_minutes:services.find(s=>s.id===e.target.value)?.duration_minutes||60})}>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Ώρα<input type="time" required value={draft.start_time} onChange={e=>setDraft({...draft,start_time:e.target.value})}/></label><label>Διάρκεια (λεπτά)<input type="number" min="5" max="240" required value={draft.duration_minutes} onChange={e=>setDraft({...draft,duration_minutes:+e.target.value})}/></label><label>Από<input type="date" required value={draft.valid_from} onChange={e=>setDraft({...draft,valid_from:e.target.value})}/></label><label>Έως<input type="date" required min={draft.valid_from} value={draft.valid_until} onChange={e=>setDraft({...draft,valid_until:e.target.value})}/></label><button disabled={busy||!draft.weekdays.length}>＋ Κανόνας</button></div><div className="weekday-picks">{days.map(([n,label])=><label className="reference-check" key={n}><input type="checkbox" checked={draft.weekdays.includes(n)} onChange={e=>setDraft({...draft,weekdays:e.target.checked?[...draft.weekdays,n]:draft.weekdays.filter(v=>v!==n)})}/>{label}</label>)}</div></form>
 <label>Φίλτρο υπηρεσίας<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Όλες οι υπηρεσίες</option>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="reference-availability-rules">{rules.filter(r=>!filter||r.service_id===filter).map(r=><div className={`reference-availability-rule ${r.active?"":"inactive"}`} key={r.id}><select aria-label="Υπηρεσία" value={r.service_id} onChange={e=>edit(r.id,"service_id",e.target.value)}>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select aria-label="Ημέρα" value={r.weekday} onChange={e=>edit(r.id,"weekday",+e.target.value)}>{days.map(([n,l])=><option value={n} key={n}>{l}</option>)}</select><input aria-label="Ώρα" type="time" value={r.start_time} onChange={e=>edit(r.id,"start_time",e.target.value)}/><input aria-label="Διάρκεια" type="number" min="5" max="240" value={r.duration_minutes} onChange={e=>edit(r.id,"duration_minutes",+e.target.value)}/><input aria-label="Από" type="date" value={r.valid_from} onChange={e=>edit(r.id,"valid_from",e.target.value)}/><input aria-label="Έως" type="date" value={r.valid_until||""} onChange={e=>edit(r.id,"valid_until",e.target.value)}/><label className="reference-check"><input type="checkbox" checked={r.active} onChange={e=>edit(r.id,"active",e.target.checked)}/> Ενεργό</label><button disabled={busy} onClick={()=>void save({p_rule:r})}>Αποθήκευση</button></div>)}</div>
 <h2>Κλειστές ημέρες & αργίες</h2><form className="reference-availability-create" onSubmit={e=>{e.preventDefault();void save({p_closure:closure})}}><label>Ημερομηνία<input type="date" required value={closure.closure_date} onChange={e=>setClosure({...closure,closure_date:e.target.value})}/></label><label>Τύπος<select value={closure.closure_type} onChange={e=>setClosure({...closure,closure_type:e.target.value})}><option value="closed_day">Κλειστή ημέρα</option><option value="holiday">Αργία</option><option value="special_closure">Ειδικό κλείσιμο</option></select></label><label>Υπηρεσία<select value={closure.service_id} onChange={e=>setClosure({...closure,service_id:e.target.value})}><option value="">Όλες</option>{services.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Σημείωση<input value={closure.reason} onChange={e=>setClosure({...closure,reason:e.target.value})}/></label><button disabled={busy}>＋ Κλειστή ημέρα</button></form>{closures.map(c=><div className="reference-list-row" key={c.id}><b>{c.closure_date.split("-").reverse().join("/")}</b><span>{c.reason||c.closure_type}</span><button disabled={busy} onClick={()=>void save({p_delete:c.id,p_delete_kind:"closure"})}>Αφαίρεση</button></div>)}</section>
}
