"use client";
import {useEffect,useState} from "react";
import {api} from "../../lib/supabase-rest";
import PackagesPanel from "./packages-panel";
type Lead={id?:string;name:string;phone:string;email:string;service:string;source:string;stage:string;notes:string;follow_up:string|null};
type Staff={id:string;full_name:string;email:string;phone:string;role:string;active:boolean};
type Location={id?:string;name:string;address:string;active:boolean};
const stages=['New Lead','Contacted','Trial Booked','Trial Completed','Member','Renewal','Lost'],sources=['Instagram','Facebook','TikTok','Website','Referral','Walk-in','Other'];
const blank:Lead={name:"",phone:"",email:"",service:"",source:"Other",stage:"New Lead",notes:"",follow_up:null};
export default function BusinessCenter({owner,userId}:{owner:boolean;userId:string}){
 const [tab,setTab]=useState("packages"),[leads,setLeads]=useState<Lead[]>([]),[staff,setStaff]=useState<Staff[]>([]),[locations,setLocations]=useState<Location[]>([]),[logs,setLogs]=useState<{id:number;action:string;table_name:string;created_at:string;record_id:string}[]>([]),[lead,setLead]=useState<Lead>(blank),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const token=()=>localStorage.getItem("basement_access_token")||"";
 async function request(path:string,body?:object,method=body?"POST":"GET"){const r=await api("/rest/v1/"+path,token(),{method,...(body?{body:JSON.stringify(body)}:{})});if(!r.ok){const d=await r.json().catch(()=>({}));throw Error(d.message||"Η ενέργεια δεν ολοκληρώθηκε.")}return r.status===204?null:r.json().catch(()=>null)}
 async function load(){try{if(tab==="crm")setLeads(await request("basement_leads?select=*&order=updated_at.desc"));if(tab==="audit")setLogs(await request("audit_log?select=id,action,table_name,created_at,record_id&order=created_at.desc&limit=300"));if(tab==="access"){const [s,l]=await Promise.all([request("rpc/basement_staff_directory",{}),request("locations?select=id,name,address,active&order=name")]);setStaff(s);setLocations(l)}}catch(e){setMessage(String(e))}}
 useEffect(()=>{void load()},[tab]);
 async function run(action:()=>Promise<unknown>,success="Αποθηκεύτηκε."){setBusy(true);setMessage("");try{await action();await load();setMessage(success)}catch(e){setMessage(e instanceof Error?e.message:"Δεν ολοκληρώθηκε η ενέργεια.")}finally{setBusy(false)}}
 async function backup(){await run(async()=>{const d=await request("rpc/basement_business_export",{}),url=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:"application/json"})),a=document.createElement("a");a.href=url;a.download=`basement-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)},"Το αντίγραφο δεδομένων κατέβηκε.")}
 const nav=owner?[["packages","Πακέτα"],["crm","CRM"],["access","Πρόσβαση & χώροι"],["audit","Audit log"]]:[["packages","Πακέτα"],["crm","CRM"]];
 return <section><div className="reference-heading"><div><div className="eyebrow">ΔΙΑΧΕΙΡΙΣΗ CLUB</div><h1>Πακέτα & CRM<span>.</span></h1></div>{owner&&<button disabled={busy} onClick={()=>void backup()}>Λήψη backup JSON</button>}</div><nav className="reference-subnav">{nav.map(([key,label])=><button className={tab===key?"active":""} key={key} onClick={()=>{setTab(key);setMessage("")}}>{label}</button>)}</nav>{message&&<p className="notice" role="status">{message}</p>}
 {tab==="packages"&&<PackagesPanel owner userId={userId}/>}
 {tab==="crm"&&<div className="reference-settings-grid"><form className="reference-panel reference-settings-card" onSubmit={e=>{e.preventDefault();void run(async()=>{const payload={...lead,follow_up:lead.follow_up||null,updated_at:new Date().toISOString()};delete payload.id;await request(lead.id?`basement_leads?id=eq.${lead.id}`:"basement_leads",payload,lead.id?"PATCH":"POST");setLead(blank)})}}><h2>{lead.id?"Επεξεργασία επαφής":"Νέα επαφή / Lead"}</h2>{([["name","Όνομα"],["phone","Τηλέφωνο"],["email","Email"],["service","Υπηρεσία ενδιαφέροντος"]] as const).map(([key,label])=><label key={key}>{label}<input required={key==="name"} type={key==="email"?"email":"text"} value={lead[key]} onChange={e=>setLead({...lead,[key]:e.target.value})}/></label>)}<div className="reference-mini-grid"><label>Πηγή<select value={lead.source} onChange={e=>setLead({...lead,source:e.target.value})}>{sources.map(s=><option key={s}>{s}</option>)}</select></label><label>Στάδιο<select value={lead.stage} onChange={e=>setLead({...lead,stage:e.target.value})}>{stages.map(s=><option key={s}>{s}</option>)}</select></label></div><label>Επόμενη επικοινωνία<input type="date" value={lead.follow_up||""} onChange={e=>setLead({...lead,follow_up:e.target.value})}/></label><label>Σημειώσεις<textarea value={lead.notes} onChange={e=>setLead({...lead,notes:e.target.value})}/></label><button className="primary" disabled={busy}>Αποθήκευση επαφής</button>{lead.id&&<button type="button" onClick={()=>setLead(blank)}>Νέα επαφή</button>}</form><section className="reference-panel reference-settings-card"><h2>Επαφές & επόμενες ενέργειες</h2>{stages.map(stage=>{const rows=leads.filter(l=>l.stage===stage);return rows.length?<section className="reference-lead-stage" key={stage}><h3>{stage} · {rows.length}</h3>{rows.map(l=><button className="reference-lead" key={l.id} onClick={()=>setLead(l)}><b>{l.name}</b><span>{l.phone} · {l.service}</span><small>{l.follow_up?`Επικοινωνία: ${l.follow_up.split("-").reverse().join("/")}`:l.source}</small></button>)}</section>:null})}{!leads.length&&<p>Δεν υπάρχουν επαφές ακόμη.</p>}</section></div>}
 {tab==="access"&&owner&&<div className="reference-settings-grid"><section className="reference-panel reference-settings-card"><h2>Πρόσβαση προσωπικού & γυμναστών</h2><p>Δώσε email υπάρχοντος λογαριασμού. Οι αλλαγές εφαρμόζονται στην επόμενη ανανέωση της εφαρμογής του.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>request("rpc/basement_save_staff",{p_email:f.get("email"),p_name:f.get("name"),p_role:f.get("role"),p_active:true}))}}><label>Όνομα<input name="name" required/></label><label>Email<input type="email" name="email" required/></label><label>Ρόλος<select name="role"><option value="reception">Υποδοχή</option><option value="trainer">Γυμναστής</option><option value="admin">Διαχειριστής</option><option value="owner">Ιδιοκτήτης</option></select></label><button disabled={busy}>Αποθήκευση πρόσβασης</button></form>{staff.map(s=><div className="reference-list-row" key={s.id}><span><b>{s.full_name}</b><small>{s.email} · {s.role}</small></span><button disabled={busy||s.id===userId} onClick={()=>void run(()=>request("rpc/basement_save_staff",{p_email:s.email,p_name:s.full_name,p_role:s.role,p_active:!s.active}))}>{s.active?"Απενεργοποίηση":"Ενεργοποίηση"}</button></div>)}</section><section className="reference-panel reference-settings-card"><h2>Χώροι</h2><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>request("locations",{name:f.get("name"),address:f.get("address"),timezone:"Europe/Athens",active:true}))}}><label>Όνομα χώρου<input name="name" required/></label><label>Διεύθυνση<input name="address"/></label><button disabled={busy}>＋ Χώρος</button></form>{locations.map(l=><div className="reference-list-row" key={l.id}><span><b>{l.name}</b><small>{l.address}</small></span></div>)}</section></div>}
 {tab==="audit"&&owner&&<section className="reference-panel reference-settings-card"><h2>Ιστορικό αλλαγών</h2><p>Οι 300 πιο πρόσφατες καταχωρίσεις.</p>{logs.map(l=><div className="reference-list-row" key={l.id}><span>{new Date(l.created_at).toLocaleString("el-GR",{timeZone:"Europe/Athens"})}</span><b>{l.action} · {l.table_name}</b><small>{l.record_id}</small></div>)}</section>}</section>
}
