"use client";
import {useEffect,useState} from "react";
import {api} from "../../lib/supabase-rest";
type Row={id:string;service_id:string;specific_date:string|null;weekday:number|null;start_time:string|null;capacity:number;active:boolean};
export default function CapacitySettings({services}:{services:{id:string;name:string}[]}){
 const [rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const token=()=>localStorage.getItem("basement_access_token")||"";
 async function load(){const r=await api("/rest/v1/capacity_overrides?select=*&order=specific_date.desc.nullslast",token());if(r.ok)setRows(await r.json());else setMessage("Δεν φορτώθηκαν οι ειδικές χωρητικότητες.")}
 useEffect(()=>{void load()},[]);
 async function save(data:object){setBusy(true);setMessage("");try{const r=await api("/rest/v1/rpc/basement_save_capacity",token(),{method:"POST",body:JSON.stringify({p_data:data})});if(!r.ok){const d=await r.json();throw Error(d.message)}await load();setMessage("Η χωρητικότητα ενημερώθηκε στο ημερολόγιο.")}catch(e){setMessage(String(e))}finally{setBusy(false)}}
 return <section className="reference-panel reference-settings-card"><h2>Ειδική χωρητικότητα ανά ημέρα / ώρα</h2><p>Η συγκεκριμένη ημερομηνία υπερισχύει του εβδομαδιαίου κανόνα. Οι ήδη καταχωρισμένες κρατήσεις διατηρούνται.</p>{message&&<p className="notice" role="status">{message}</p>}<form className="reference-availability-create" onSubmit={e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));void save({...d,capacity:Number(d.capacity)})}}><label>Υπηρεσία<select name="service_id" required>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Ημερομηνία<input type="date" name="specific_date"/></label><label>Ημέρα<select name="weekday"><option value="">Όλες</option>{['Δευ','Τρι','Τετ','Πεμ','Παρ','Σαβ','Κυρ'].map((d,i)=><option value={i+1} key={d}>{d}</option>)}</select></label><label>Ώρα<input type="time" name="start_time"/></label><label>Θέσεις<input type="number" min="1" max="30" name="capacity" defaultValue="1" required/></label><button disabled={busy}>Αποθήκευση</button></form>{rows.filter(r=>r.active).map(r=><div className="reference-list-row" key={r.id}><b>{services.find(s=>s.id===r.service_id)?.name}</b><span>{r.specific_date||(['Δευ','Τρι','Τετ','Πεμ','Παρ','Σαβ','Κυρ'][Number(r.weekday)-1]||'Όλες οι ημέρες')} · {r.start_time||'Όλες οι ώρες'} · {r.capacity} θέσεις</span><button disabled={busy} onClick={()=>void save({...r,active:false})}>Απενεργοποίηση</button></div>)}</section>
}
