"use client";
import {FormEvent,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import Image from "next/image";
import {api} from "../../lib/supabase-rest";
type Profile={id:string;full_name:string|null;role:string};
export default function DashboardClient(){const router=useRouter(),[profile,setProfile]=useState<Profile|null>(null),[members,setMembers]=useState<Profile[]>([]),[tab,setTab]=useState("overview"),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
const token=()=>localStorage.getItem("basement_access_token")||"";
useEffect(()=>{(async()=>{const u=await api("/auth/v1/user",token());if(!u.ok){logout();return}const user=await u.json();const p=await api(`/rest/v1/profiles?id=eq.${user.id}&select=id,full_name,role`,token());const rows=await p.json();const me=rows[0];if(!me){logout();return}setProfile(me);if(["owner","admin"].includes(me.role)){const m=await api("/rest/v1/profiles?role=eq.member&select=id,full_name,role&order=full_name",token());if(m.ok)setMembers(await m.json())}})()},[]);
function logout(){localStorage.removeItem("basement_access_token");localStorage.removeItem("basement_refresh_token");router.replace("/login")}
async function createMember(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setNotice("");const form=new FormData(e.currentTarget);const r=await fetch("/api/admin/create-member",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token()}`},body:JSON.stringify(Object.fromEntries(form))});const data=await r.json();setBusy(false);setNotice(r.ok?"Το μέλος δημιουργήθηκε επιτυχώς.":data.error||"Δεν ολοκληρώθηκε η εγγραφή.");if(r.ok){e.currentTarget.reset();setMembers(x=>[...x,{id:data.id,full_name:data.full_name,role:"member"}])}}
if(!profile)return <main className="loading-page">Φόρτωση Control Center…</main>;const owner=["owner","admin"].includes(profile.role);
return <main className="control"><header><div className="brand"><Image src="/basement-logo.jpeg" width={52} height={52} alt=""/><span><b>BASEMENT</b><small>CONTROL CENTER</small></span></div><button onClick={logout}>Αποσύνδεση</button></header><div className="control-body"><aside>{[["overview","Επισκόπηση"],["calendar","Ημερολόγιο"],["members","Μέλη"],["packages","Πακέτα"],["settings","Ρυθμίσεις"]].filter(x=>owner||["overview","calendar","packages"].includes(x[0])).map(x=><button key={x[0]} className={tab===x[0]?"active":""} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</aside><section><div className="dashboard-title"><div><h1>Καλώς ήρθες, {profile.full_name||"μέλος"}</h1><p>{owner?"Owner Dashboard · Basement Health Club":"Member Portal · Προσωπικές κρατήσεις"}</p></div><span>{profile.role}</span></div>{tab==="overview"&&<div className="dash-grid"><article><small>Ενεργά μέλη</small><strong>{owner?members.length:"—"}</strong></article><article><small>Σημερινές κρατήσεις</small><strong>—</strong></article><article><small>Υπόλοιπο συνεδριών</small><strong>—</strong></article><article><small>Κατάσταση</small><strong className="online">ONLINE</strong></article></div>}{tab==="members"&&owner&&<><div className="panel-title"><div><h2>Μέλη</h2><p>Μόνο ο ιδιοκτήτης δημιουργεί νέους λογαριασμούς.</p></div></div><div className="two-col"><form className="admin-form" onSubmit={createMember}><h3>Νέο μέλος</h3><label>Ονοματεπώνυμο<input name="full_name" required/></label><label>Email<input name="email" type="email" required/></label><label>Προσωρινός κωδικός<input name="password" type="password" minLength={8} required/></label><label>Τηλέφωνο<input name="phone" inputMode="tel"/></label><button disabled={busy}>{busy?"Δημιουργία…":"Δημιουργία μέλους"}</button>{notice&&<p className="notice">{notice}</p>}</form><div className="member-list"><h3>Λίστα μελών</h3>{members.length?members.map(m=><div key={m.id}><b>{m.full_name||"Χωρίς όνομα"}</b><span>Ενεργό μέλος</span></div>):<p>Δεν υπάρχουν ακόμη μέλη.</p>}</div></div></>}{!["overview","members"].includes(tab)&&<div className="coming-panel"><h2>{tab==="calendar"?"Ημερολόγιο κρατήσεων":tab==="packages"?"Πακέτα και συνεδρίες":"Ρυθμίσεις"}</h2><p>Η ενότητα συνδέεται με το πρόγραμμα και τη βάση δεδομένων του Basement.</p></div>}</section></div></main>}
