"use client";
import {useEffect,useState} from "react";
import {api} from "../../lib/supabase-rest";
type Member={id:string;full_name:string;email:string|null;phone:string|null;qr_token:string;active:boolean};
type Measurement={id:number;measured_on:string;weight_kg:number|null;body_fat_percent:number|null;waist_cm:number|null};
export default function MemberProfilePanel({userId}:{userId:string}){
 const [member,setMember]=useState<Member|null>(null),[measurements,setMeasurements]=useState<Measurement[]>([]),[checkins,setCheckins]=useState(0),[messages,setMessages]=useState<{id:number;title:string;body:string;created_at:string}[]>([]),[error,setError]=useState("");
 const token=()=>localStorage.getItem("basement_access_token")||"";
 useEffect(()=>{void(async()=>{try{const m=await api(`/rest/v1/members?auth_user_id=eq.${userId}&select=id,full_name,email,phone,qr_token,active`,token());const rows=await m.json(),me=rows[0];if(!me)throw 0;setMember(me);const [x,c,n]=await Promise.all([api(`/rest/v1/member_measurements?member_id=eq.${me.id}&select=id,measured_on,weight_kg,body_fat_percent,waist_cm&order=measured_on.desc`,token()),api(`/rest/v1/gym_checkins?member_id=eq.${me.id}&select=id`,token(),{method:"HEAD",headers:{Prefer:"count=exact"}}),api(`/rest/v1/outbound_notifications?member_id=eq.${me.id}&select=id,title,body,created_at&status=eq.sent&order=created_at.desc`,token())]);if(x.ok)setMeasurements(await x.json());if(c.ok)setCheckins(Number(c.headers.get("content-range")?.split("/")[1]||0));if(n.ok)setMessages(await n.json())}catch{setError("Δεν φορτώθηκε το προφίλ μέλους.")}})()},[userId]);
 if(error)return <p className="booking-error">{error}</p>;if(!member)return <p>Φόρτωση προφίλ…</p>;
 const latest=measurements[0];return <div className="member-portal"><div className="panel-title"><div><span className="kicker">ΠΡΟΦΙΛ ΜΕΛΟΥΣ</span><h2>{member.full_name}</h2><p>{member.active?"Ενεργό μέλος":"Ανενεργό μέλος"}</p></div></div><div className="dash-grid"><article><small>Check-ins</small><strong>{checkins}</strong></article><article><small>Βάρος</small><strong>{latest?.weight_kg??"—"}<small> kg</small></strong></article><article><small>Λίπος</small><strong>{latest?.body_fat_percent??"—"}<small>%</small></strong></article><article><small>Μέση</small><strong>{latest?.waist_cm??"—"}<small> cm</small></strong></article></div><div className="ops-grid"><section className="qr-card"><span>ΠΡΟΣΩΠΙΚΟ CHECK-IN</span><h3>QR / Κωδικός μέλους</h3><div className="qr-pattern" aria-hidden="true">▦</div><code>{member.qr_token}</code><p>Δείξε αυτόν τον κωδικό στην υποδοχή.</p></section><section className="ops-list"><h3>Μετρήσεις</h3>{measurements.length?measurements.map(x=><article key={x.id}><b>{x.measured_on}</b><span>{x.weight_kg??"—"} kg · {x.body_fat_percent??"—"}% · {x.waist_cm??"—"} cm</span></article>):<p>Δεν υπάρχουν ακόμη μετρήσεις.</p>}</section></div>{messages.length>0&&<section className="ops-list"><h3>Ειδοποιήσεις</h3>{messages.map(m=><article key={m.id}><b>{m.title}</b><span>{m.body}</span></article>)}</section>}</div>;
}
