"use client";
import {useEffect,useState} from "react";
import {api} from "../../lib/supabase-rest";
type Template={id:string;name:string;sessions_total:number|null;validity_days:number;active:boolean;package_template_services?:{services:{name:string}|null}[]};
type Package={id:string;package_template_id:string;starts_on:string;expires_on:string;sessions_total:number|null;sessions_remaining:number|null;status:string};
export default function MemberPackageEditor({memberId,onSaved}:{memberId:string;onSaved:()=>void}){
 const [templates,setTemplates]=useState<Template[]>([]),[packages,setPackages]=useState<Package[]>([]),[selected,setSelected]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const token=()=>localStorage.getItem("basement_access_token")||"";
 async function load(){const [a,b]=await Promise.all([api("/rest/v1/package_templates?select=id,name,sessions_total,validity_days,active,package_template_services(services(name))&order=name",token()),api(`/rest/v1/member_packages?member_id=eq.${memberId}&select=id,package_template_id,starts_on,expires_on,sessions_total,sessions_remaining,status&order=created_at.desc`,token())]);if(a.ok)setTemplates(await a.json());if(b.ok)setPackages(await b.json())}
 useEffect(()=>{void load()},[memberId]);
 const template=templates.find(t=>t.id===selected);
 async function add(){if(!template)return;const starts_on=new Date().toISOString().slice(0,10),expires_on=new Date(Date.now()+template.validity_days*86400000).toISOString().slice(0,10);setBusy(true);const r=await api("/rest/v1/member_packages",token(),{method:"POST",body:JSON.stringify({member_id:memberId,package_template_id:template.id,starts_on,expires_on,sessions_total:template.sessions_total,sessions_remaining:template.sessions_total,status:"active"})});setBusy(false);if(!r.ok){setError("Δεν προστέθηκε το πακέτο.");return}setError("");await load();onSaved()}
 async function save(e:React.FormEvent<HTMLFormElement>,id:string){e.preventDefault();const fd=new FormData(e.currentTarget);const total=fd.get("sessions_total")===""?null:Number(fd.get("sessions_total"));const current=packages.find(p=>p.id===id);if(total!==null&&current?.sessions_remaining!==null&&current?.sessions_remaining!==undefined&&total<current.sessions_remaining){setError("Το σύνολο δεν μπορεί να είναι μικρότερο από το υπόλοιπο.");return}setBusy(true);const r=await api(`/rest/v1/member_packages?id=eq.${id}`,token(),{method:"PATCH",body:JSON.stringify({starts_on:String(fd.get("starts_on")),expires_on:String(fd.get("expires_on")),sessions_total:total,status:String(fd.get("status"))})});setBusy(false);if(!r.ok){setError("Δεν αποθηκεύτηκε το πακέτο.");return}setError("");await load();onSaved()}
 return <article className="member-detail-card"><h3>Διαχείριση πακέτου</h3>{error&&<p role="alert">{error}</p>}<div className="detail-line"><select aria-label="Νέο πακέτο" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Επιλογή πακέτου</option>{templates.filter(t=>t.active).map(t=><option key={t.id} value={t.id}>{t.name} · {t.sessions_total??"∞"} συνεδρίες</option>)}</select><button disabled={!template||busy} onClick={()=>void add()}>Προσθήκη</button></div>{template&&<p>Υπηρεσίες: {template.package_template_services?.map(x=>x.services?.name).filter(Boolean).join(", ")||"Σύμφωνα με το πακέτο"}</p>}{packages.map(p=><form key={p.id} className="member-package-edit" onSubmit={e=>void save(e,p.id)}><b>{templates.find(t=>t.id===p.package_template_id)?.name||"Πακέτο"}</b><p>Υπηρεσίες: {templates.find(t=>t.id===p.package_template_id)?.package_template_services?.map(x=>x.services?.name).filter(Boolean).join(", ")||"Σύμφωνα με το πακέτο"} · Έγιναν: {p.sessions_total===null||p.sessions_remaining===null?"Απεριόριστες":Math.max(0,p.sessions_total-p.sessions_remaining)} · Απομένουν: {p.sessions_remaining??"∞"}{p.status==="active"&&((p.sessions_remaining!==null&&p.sessions_remaining<=2)||new Date(p.expires_on).getTime()-Date.now()<=7*86400000)?" · ⚠ Ανανέωση σύντομα":""}</p><label>Έναρξη<input type="date" name="starts_on" defaultValue={p.starts_on} required/></label><label>Λήξη<input type="date" name="expires_on" defaultValue={p.expires_on} required/></label><label>Σύνολο συνεδριών<input type="number" min="0" name="sessions_total" defaultValue={p.sessions_total??""} placeholder="Απεριόριστο"/></label><label>Κατάσταση<select name="status" defaultValue={p.status}><option value="active">Ενεργό</option><option value="scheduled">Προγραμματισμένο</option><option value="completed">Ολοκληρώθηκε</option><option value="expired">Έληξε</option><option value="cancelled">Ακυρώθηκε</option></select></label><button disabled={busy}>Αποθήκευση πακέτου</button></form>)}</article>
}
