"use client";
import {useCallback,useEffect,useState} from "react";
import {api} from "../../lib/supabase-rest";

type Subscription={id:string;name:string;status:string;starts_on:string;expires_on:string;sessions_remaining:number|null;frozen_until:string|null;services:string[]};
type Appointment={id:number;slot_id:number;service:string;starts_at:string;ends_at:string;status:string;paid_at:string|null;position_no:number|null;waitlist_source_id?:number|null};
type Slot={id:number;service:string;starts_at:string;ends_at:string;capacity:number;reserved:number;enabled:boolean};
type Health={emergency_contact?:string;conditions?:string;injuries?:string;medications?:string;notes?:string;ems_consent?:boolean};
type Portal={packages:Subscription[];bookings:Appointment[];services:string[];completed_count:number;block_after_expiry:boolean;grace_days:number;next_payment_on:string|null;last_payment_on:string|null;terms_required:boolean;gdpr_required:boolean;gdpr_accepted:boolean;booking_paused:boolean;show_available_spots:boolean;fixed_positions:boolean;hide_fixed_positions:boolean;allow_without_package:boolean;questionnaire_enabled:boolean;health:Health;business_email:string;business_phone:string;time_format?:string;paid_date?:boolean;service_subscription_dates?:boolean;package_unit?:string};
type PortalExtras=Partial<Portal>&{booking_meta?:{id:number;position_no:number|null;waitlist_source_id:number|null}[]};
const zone="Europe/Athens";
const dateKey=(d=new Date())=>{const p=Object.fromEntries(new Intl.DateTimeFormat("en-GB",{timeZone:zone,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(d).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}`};
const date=(v:string)=>new Date(v.length===10?`${v}T12:00:00+03:00`:v).toLocaleDateString("el-GR",{timeZone:zone,day:"numeric",month:"long",year:"numeric"});
const time=(v:string,hour12=false)=>new Date(v).toLocaleTimeString("el-GR",{timeZone:zone,hour:"2-digit",minute:"2-digit",hour12});
const labels:Record<string,string>={booked:"Επιβεβαιωμένο",pending:"Αναμονή επιβεβαίωσης",completed:"Ολοκληρωμένο · Check-in",cancelled:"Ακυρωμένο",late_cancel:"Εκπρόθεσμη ακύρωση",no_show:"Απουσία"};

export default function MemberPortal({mode,onCalendar}:{mode:"overview"|"calendar"|"packages";onCalendar:()=>void}){
 const [data,setData]=useState<Portal|null>(null),[slots,setSlots]=useState<Slot[]>([]),[day,setDay]=useState(()=>dateKey()),[service,setService]=useState("");
 const [error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[accepted,setAccepted]=useState(false),[historyLimit,setHistoryLimit]=useState(20);
 const [health,setHealth]=useState<Health>({});
 const [confirm,setConfirm]=useState<{kind:"book"|"cancel"|"confirm";id:number;title:string}|null>(null);
 const token=()=>localStorage.getItem("basement_access_token")||"";
 const refresh=useCallback(async()=>{
  try{
   const [response,extrasResponse]=await Promise.all([
    api("/rest/v1/rpc/basement_member_portal",token()),
    api("/rest/v1/rpc/basement_member_portal_extras",token())
   ]);
   if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.message||"Δεν φορτώθηκε η προσωπική σου καρτέλα.")}
   const base:Portal=await response.json();
   const extras:PortalExtras=extrasResponse.ok?await extrasResponse.json():{};
   const meta=new Map((extras.booking_meta||[]).map(item=>[item.id,item]));
   const next:Portal={...base,...extras,services:extras.services||base.services,bookings:base.bookings.map(b=>{const m=meta.get(b.id);return {...b,position_no:m?.position_no??b.position_no??null,waitlist_source_id:m?.waitlist_source_id??b.waitlist_source_id??null,paid_at:extras.paid_date===false?null:b.paid_at}})};
   const available:Slot[]=[];
   for(let offset=0;;offset+=1000){
    const r=await api(`/rest/v1/rpc/basement_availability?limit=1000&offset=${offset}`,token());
    if(!r.ok)throw new Error("Δεν φορτώθηκαν οι διαθέσιμες ώρες. Δοκίμασε ανανέωση.");
    const page:Slot[]=await r.json();available.push(...page);if(page.length<1000)break;
   }
   setData(next);setSlots(available);setHealth(next.health||{});setError("");
   setService(current=>next.services.includes(current)?current:next.services[0]||"");return true;
  }catch(e){setError(e instanceof Error?e.message:"Δεν φορτώθηκαν τα στοιχεία σου.");return false}
 },[]);
 useEffect(()=>{void refresh();const id=window.setInterval(()=>void refresh(),60000);return()=>clearInterval(id)},[refresh]);
 async function submit(){
  if(!confirm)return;setBusy(true);setError("");setNotice("");
  try{
   if(confirm.kind==="book"&&data?.gdpr_required&&!data.gdpr_accepted){const c=await api("/rest/v1/rpc/basement_record_consent",token(),{method:"POST",body:JSON.stringify({p_key:"booking_gdpr"})});if(!c.ok){const d=await c.json().catch(()=>({}));throw new Error(d.message||"Δεν αποθηκεύτηκε η συγκατάθεση GDPR.")}}
   const rpcName=confirm.kind==="book"?"basement_book":confirm.kind==="confirm"?"basement_confirm_booking":"basement_cancel";
   const r=await api(`/rest/v1/rpc/${rpcName}`,token(),{method:"POST",body:JSON.stringify(confirm.kind==="book"?{p_slot_id:confirm.id}:{p_booking_id:confirm.id})});
   const result=await r.json().catch(()=>null);if(!r.ok)throw new Error(result?.message||"Δεν ολοκληρώθηκε η ενέργεια.");
   setNotice(confirm.kind==="cancel"?"Η κράτηση ακυρώθηκε. Αν είχε χρεωθεί συνεδρία, επιστράφηκε στο πακέτο σου.":confirm.kind==="confirm"?"Η θέση επιβεβαιώθηκε.":typeof result==="number"&&result<0?"Μπήκες στη λίστα αναμονής. Θα ενημερωθείς όταν ανοίξει θέση.":"Η κράτηση καταχωρίστηκε και δεσμεύτηκε μία συνεδρία.");
   setConfirm(null);setAccepted(false);await refresh();
  }catch(e){setError(e instanceof Error?e.message:"Δεν ολοκληρώθηκε η ενέργεια.")}finally{setBusy(false)}
 }
 async function saveHealth(){setBusy(true);setError("");setNotice("");try{const r=await api("/rest/v1/rpc/basement_member_save_health",token(),{method:"POST",body:JSON.stringify({p_data:health})});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.message||"Δεν αποθηκεύτηκε το ερωτηματολόγιο.");setNotice("Το ερωτηματολόγιο υγείας αποθηκεύτηκε.");await refresh()}catch(e){setError(e instanceof Error?e.message:"Δεν αποθηκεύτηκε το ερωτηματολόγιο.")}finally{setBusy(false)}}
 const today=dateKey(),now=Date.now();
 const showTime=(v:string)=>time(v,data?.time_format==="12 ώρες");
 const coversDate=(p:Subscription,on:string)=>!data?.block_after_expiry||new Date(`${p.expires_on}T12:00:00Z`).getTime()+(data?.grace_days||0)*86400000>=new Date(`${on}T12:00:00Z`).getTime();
 const active=data?.packages.filter(p=>["active","scheduled"].includes(p.status)&&coversDate(p,today))||[];
 const upcoming=data?.bookings.filter(b=>["booked","pending"].includes(b.status)&&new Date(b.ends_at).getTime()>now)||[];
 const history=data?.bookings.filter(b=>!upcoming.some(u=>u.id===b.id)).slice().reverse()||[];
 const days=[...new Set([today,day,...slots.map(s=>dateKey(new Date(s.starts_at)))])].sort();
 const shown=slots.filter(s=>s.service===service&&dateKey(new Date(s.starts_at))===day&&s.enabled&&new Date(s.starts_at).getTime()>now&&Number(s.reserved)<s.capacity);
 const hasCredit=(s:Slot)=>!!data?.allow_without_package||active.some(p=>p.services.includes(s.service)&&p.starts_on<=dateKey(new Date(s.starts_at))&&coversDate(p,dateKey(new Date(s.starts_at)))&&(!p.frozen_until||p.frozen_until<dateKey(new Date(s.starts_at)))&&(p.sessions_remaining===null||p.sessions_remaining>0));
 function changeDay(step:number){const d=new Date(`${day}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+step);setDay(d.toISOString().slice(0,10))}
 function appointment(b:Appointment){return <article className="member-appointment" key={b.id}><div><strong>{b.service}</strong><p>{date(b.starts_at)} · {showTime(b.starts_at)}–{showTime(b.ends_at)}</p><small>{labels[b.status]||b.status}</small>{data?.fixed_positions&&!data.hide_fixed_positions&&b.position_no&&<small>Θέση {b.position_no}</small>}{b.paid_at&&<small>Πληρωμή ραντεβού: {date(b.paid_at)}</small>}</div><div className="member-appointment-actions">{b.status==="pending"&&b.waitlist_source_id&&new Date(b.starts_at).getTime()>now&&<button disabled={busy} onClick={()=>setConfirm({kind:"confirm",id:b.id,title:`${b.service} · ${date(b.starts_at)} ${showTime(b.starts_at)}`})}>✓ Επιβεβαίωση θέσης</button>}{["booked","pending"].includes(b.status)&&new Date(b.starts_at).getTime()>now&&<button disabled={busy} onClick={()=>setConfirm({kind:"cancel",id:b.id,title:`${b.service} · ${date(b.starts_at)} ${showTime(b.starts_at)}`})}>Ακύρωση</button>}</div></article>}
 return <div className="member-portal" aria-busy={busy}><div className="member-portal-heading"><h2>{mode==="calendar"?"Κλείσε την προπόνησή σου":mode==="packages"?"Οι συνδρομές μου":"Το πρόγραμμά μου"}</h2><button disabled={busy} onClick={()=>void refresh()}>↻ Ανανέωση</button></div>{error&&<p className="booking-error" role="alert">{error}</p>}{notice&&<p className="booking-success" role="status">{notice}</p>}{!data&&!error&&<p>Φόρτωση προσωπικού προγράμματος…</p>}{data&&<>
 {mode!=="calendar"&&<><div className="member-personal-stats"><article><span>Επόμενες κρατήσεις</span><strong>{upcoming.length}</strong></article><article><span>Προπονήσεις που έκανα</span><strong>{data.completed_count}</strong></article>{data.next_payment_on&&<article><span>Επόμενη πληρωμή</span><strong>{date(data.next_payment_on)}</strong></article>}</div><h3>Οι συνδρομές σου</h3><div className="member-subscriptions">{active.length?active.map(p=><article key={p.id}><h3>{p.name}</h3><p>{data.service_subscription_dates===false?"Όλες οι ενεργές υπηρεσίες":p.services.join(" · ")||"Επικοινώνησε για ενεργοποίηση υπηρεσίας"}</p><strong>{p.sessions_remaining===null?"Απεριόριστες συνεδρίες":`${p.sessions_remaining} συνεδρίες διαθέσιμες`}</strong><p>Από {date(p.starts_on)} · Λήξη {date(p.expires_on)}</p>{p.frozen_until&&p.frozen_until>=today&&<p>Σε παύση έως {date(p.frozen_until)}</p>}</article>):<p>Δεν υπάρχει ενεργή συνδρομή. Επικοινώνησε με το Basement για ενεργοποίηση.</p>}</div>{data.last_payment_on&&<p>Τελευταία καταχωρισμένη πληρωμή: {date(data.last_payment_on)}</p>}<button className="member-primary" onClick={onCalendar}>Κλείσε προπόνηση →</button>{data.questionnaire_enabled&&<section className="member-questionnaire"><h3>Ερωτηματολόγιο υγείας & EMS</h3><p>Ενημέρωσε τα βασικά στοιχεία ώστε η ομάδα να έχει την τελευταία εικόνα πριν την προπόνηση.</p><label>Επικοινωνία ανάγκης<textarea value={health.emergency_contact||""} onChange={e=>setHealth(x=>({...x,emergency_contact:e.target.value}))}/></label><label>Παθήσεις / αντενδείξεις<textarea value={health.conditions||""} onChange={e=>setHealth(x=>({...x,conditions:e.target.value}))}/></label><label>Τραυματισμοί<textarea value={health.injuries||""} onChange={e=>setHealth(x=>({...x,injuries:e.target.value}))}/></label><label>Φάρμακα<textarea value={health.medications||""} onChange={e=>setHealth(x=>({...x,medications:e.target.value}))}/></label><label>Σημειώσεις<textarea value={health.notes||""} onChange={e=>setHealth(x=>({...x,notes:e.target.value}))}/></label><label className="member-terms"><input type="checkbox" checked={!!health.ems_consent} onChange={e=>setHealth(x=>({...x,ems_consent:e.target.checked}))}/> Δηλώνω ότι τα στοιχεία είναι σωστά και αποδέχομαι τη συγκατάθεση EMS όπου απαιτείται.</label><button className="member-primary" disabled={busy} onClick={()=>void saveHealth()}>Αποθήκευση ερωτηματολογίου</button></section>}{!active.length&&(data.business_phone||data.business_email)&&<p>Για ενεργοποίηση συνδρομής: {data.business_phone&&<a href={`tel:${data.business_phone.replace(/[^+0-9]/g,"")}`}>{data.business_phone}</a>}{data.business_phone&&data.business_email?" · ":""}{data.business_email&&<a href={`mailto:${data.business_email}`}>{data.business_email}</a>}</p>}</>}
 {mode==="calendar"&&<>{!data.services.length?<p>Δεν έχεις διαθέσιμη υπηρεσία σε ενεργή συνδρομή. Επικοινώνησε με το Basement.</p>:<><div className="member-service-picker" role="group" aria-label="Υπηρεσίες συνδρομής">{data.services.map(s=><button className={service===s?"selected":""} aria-pressed={service===s} key={s} onClick={()=>setService(s)}>{s}</button>)}</div><div className="member-date-picker"><button aria-label="Προηγούμενη ημέρα" disabled={day<=today} onClick={()=>changeDay(-1)}>‹</button><label>Ημερομηνία<input type="date" value={day} min={today} max={days.at(-1)} onChange={e=>{if(e.target.value)setDay(e.target.value)}}/></label><button aria-label="Επόμενη ημέρα" disabled={day>=(days.at(-1)||today)} onClick={()=>changeDay(1)}>›</button><button onClick={()=>setDay(today)}>Σήμερα</button></div><p>Κάθε κράτηση δεσμεύει μία συνεδρία. Ακύρωση πριν από την έναρξη την επιστρέφει.</p>{data.booking_paused?<p>Οι online κρατήσεις είναι προσωρινά κλειστές.</p>:<div className="member-time-grid">{shown.length?shown.map(s=>{const mine=upcoming.some(b=>b.slot_id===s.id),credit=hasCredit(s);return <button key={s.id} className="member-time-tile" disabled={busy||mine||!credit} onClick={()=>setConfirm({kind:"book",id:s.id,title:`${s.service} · ${date(s.starts_at)} · ${showTime(s.starts_at)}–${showTime(s.ends_at)}`})}><strong>{showTime(s.starts_at)}–{showTime(s.ends_at)}</strong><span>{mine?"Έχεις κράτηση":!credit?"Χρειάζεται ανανέωση πακέτου":data.show_available_spots?`${s.capacity-Number(s.reserved)} διαθέσιμες θέσεις`:"Διαθέσιμη ώρα"}</span></button>}):<p>Δεν υπάρχουν διαθέσιμες ώρες για αυτή την ημέρα. Διάλεξε άλλη ημερομηνία.</p>}</div>}</>}</>}
 {mode!=="packages"&&<><h3>Οι επόμενες προπονήσεις μου</h3><div className="member-appointments">{upcoming.length?upcoming.map(appointment):<p>Δεν έχεις επόμενη κράτηση.</p>}</div><details className="member-history"><summary>Το ιστορικό μου · {history.length} ραντεβού</summary>{history.slice(0,historyLimit).map(appointment)}{history.length>historyLimit&&<button onClick={()=>setHistoryLimit(n=>n+20)}>Περισσότερα</button>}</details></>}
 </>}{confirm&&<div className="member-confirm-backdrop" onClick={()=>{if(!busy)setConfirm(null)}}><section role="dialog" aria-modal="true" aria-labelledby="member-confirm-title" className="member-confirm" onClick={e=>e.stopPropagation()}><h3 id="member-confirm-title">{confirm.kind==="book"?"Επιβεβαίωση κράτησης":confirm.kind==="confirm"?"Επιβεβαίωση θέσης":"Ακύρωση προπόνησης"}</h3><p>{confirm.title}</p><p>{confirm.kind==="book"?"Θα αφαιρεθεί μία συνεδρία από το πακέτο σου.":confirm.kind==="confirm"?"Επιβεβαίωσε τη θέση που άνοιξε από τη λίστα αναμονής.":"Η χρεωμένη συνεδρία επιστρέφεται σύμφωνα με την πολιτική ακύρωσης."}</p>{confirm.kind==="book"&&(data?.terms_required||(data?.gdpr_required&&!data.gdpr_accepted))&&<label className="member-terms"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/> Αποδέχομαι την πολιτική κράτησης{data?.gdpr_required&&!data.gdpr_accepted?" και τη συγκατάθεση GDPR":""}.</label>}{error&&<p role="alert">{error}</p>}<div><button disabled={busy||(confirm.kind==="book"&&(data?.terms_required||(data?.gdpr_required&&!data.gdpr_accepted))&&!accepted)} onClick={()=>void submit()}>{busy?"Αποθήκευση…":"Επιβεβαίωση"}</button><button disabled={busy} onClick={()=>setConfirm(null)}>Πίσω</button></div></section></div>}</div>;
}
