"use client";
import {useEffect,useState} from "react";
import {api} from "../../lib/supabase-rest";
import {athensDay} from "../../lib/reference-calendar";
import {Meal,NutritionContent,NutritionPlan,newMeal,newNutrition,nutritionDays,nutritionError,mealTotals} from "../../lib/nutrition";
type Member={id:string;full_name:string;auth_user_id:string|null};
const states={draft:"Πρόχειρο",published:"Δημοσιευμένο",archived:"Αρχειοθετημένο"};
const token=()=>localStorage.getItem("basement_access_token")||"";
const copy=<T,>(value:T):T=>JSON.parse(JSON.stringify(value));
const date=(value:string|null)=>value?value.split("-").reverse().join("/"):"Χωρίς λήξη";
async function read(response:Response){const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.message||"Δεν ολοκληρώθηκε η αποθήκευση. Δοκίμασε ξανά.");return data;}
async function all(path:string){const rows=[];for(let offset=0;;offset+=1000){const page=await read(await api(`${path}&limit=1000&offset=${offset}`,token()));rows.push(...page);if(page.length<1000)return rows;}}
export default function NutritionPanel({owner,userId}:{owner:boolean;userId:string}){
 const [plans,setPlans]=useState<NutritionPlan[]>([]),[members,setMembers]=useState<Member[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const [query,setQuery]=useState(""),[selected,setSelected]=useState<NutritionPlan|null>(null),[editing,setEditing]=useState(false),[dirty,setDirty]=useState(false),[day,setDay]=useState(0),[template,setTemplate]=useState("");
 const [memberId,setMemberId]=useState(""),[title,setTitle]=useState(""),[start,setStart]=useState(athensDay()),[end,setEnd]=useState(""),[content,setContent]=useState<NutritionContent>(newNutrition);
 async function load(){setError("");try{const [p,m]=await Promise.all([all("/rest/v1/nutrition_plans?select=*&order=updated_at.desc,id"),all(`/rest/v1/members?select=id,full_name,auth_user_id&order=full_name,id${owner?"":`&auth_user_id=eq.${encodeURIComponent(userId)}`}`)]);setPlans(p);setMembers(m);setLoaded(true)}catch(e){setError(e instanceof Error?e.message:"Δεν φορτώθηκαν τα πλάνα.")}}
 useEffect(()=>{void load()},[owner,userId]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=""}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[dirty]);
 function changeContent(next:NutritionContent){setContent(next);setDirty(true);setNotice("")}
 function changeMeal(index:number,key:keyof Meal,value:string){const next=copy(content);next.days[day][index][key]=value;changeContent(next)}
 function begin(plan:NutritionPlan|null,duplicate=false){if(dirty&&!window.confirm("Υπάρχουν αλλαγές που δεν αποθηκεύτηκαν. Να συνεχίσεις;"))return;setSelected(duplicate?null:plan);setMemberId(plan?.member_id||"");setTitle(plan?`${plan.title}${duplicate?" · Αντίγραφο":""}`:"Νέο πλάνο διατροφής");setStart(duplicate?athensDay():plan?.starts_on||athensDay());setEnd(duplicate?"":plan?.ends_on||"");setContent(plan?copy(plan.content):newNutrition());setEditing(true);setDay(0);setDirty(false);setNotice("");setError("")}
 function close(){if(dirty&&!window.confirm("Να κλείσεις χωρίς αποθήκευση;"))return;setEditing(false);setSelected(null);setDirty(false);setError("")}
 async function save(status:NutritionPlan["status"]){if(busy)return;setError("");setNotice("");const validation=nutritionError(title,start,end,content,status==="published");if(!memberId||validation){setError(validation||"Επίλεξε μέλος.");return}setBusy(true);try{const payload={member_id:memberId,title:title.trim(),starts_on:start,ends_on:end||null,status,content};const path=selected?`/rest/v1/nutrition_plans?id=eq.${selected.id}&revision=eq.${selected.revision}`:"/rest/v1/nutrition_plans";
 const rows=await read(await api(path,token(),{method:selected?"PATCH":"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(payload)}));if(!rows[0])throw Error("Το πλάνο άλλαξε σε άλλη συσκευή. Κλείσε και άνοιξέ το ξανά πριν αποθηκεύσεις.");const saved=rows[0] as NutritionPlan;setSelected(saved);setPlans(current=>[saved,...current.filter(p=>p.id!==saved.id)]);setDirty(false);setNotice(status==="published"?"Αποθηκεύτηκε. Το μέλος μπορεί να δει το πλάνο στη Διατροφή του.":status==="archived"?"Αρχειοθετήθηκε. Διατηρείται στο ιστορικό σου.":"Το πρόχειρο αποθηκεύτηκε.")
 }catch(e){setError(e instanceof Error?e.message:"Δεν αποθηκεύτηκε το πλάνο.")}finally{setBusy(false)}}
 function open(plan:NutritionPlan){setSelected(plan);setEditing(false);setError("");setNotice("")}
 const memberName=(id:string)=>members.find(m=>m.id===id)?.full_name||"Μέλος";
 const visible=plans.filter(p=>`${memberName(p.member_id)} ${p.title}`.toLocaleLowerCase("el").includes(query.toLocaleLowerCase("el")));
 return <section className="nutrition-panel"><div className="nutrition-heading"><div><h1>{owner?"Διατροφή μελών":"Η διατροφή μου"}</h1><p>{owner?"Φτιάξε και αποθήκευσε εβδομαδιαία πλάνα ανά μέλος.":"Τα πλάνα που έχουν δημοσιευτεί για εσένα."}</p></div><div className="nutrition-actions">{owner&&!editing&&<button className="primary" onClick={()=>begin(null)}>＋ Νέο πλάνο</button>}{!editing&&<button onClick={()=>void load()}>Ανανέωση</button>}</div></div>
 {error&&<p role="alert" className="nutrition-error">{error}</p>}{notice&&<p role="status" className="nutrition-success">{notice}</p>}
 {editing&&owner?<><div className="nutrition-actions"><button disabled={busy} onClick={close}>‹ Επιστροφή</button><span>{dirty?"Μη αποθηκευμένες αλλαγές":selected?states[selected.status]:"Νέο πλάνο"}</span></div><fieldset disabled={busy} style={{border:0,padding:0,margin:0}}><div className="nutrition-meta"><label>Μέλος<select aria-label="Μέλος" value={memberId} onChange={e=>{setMemberId(e.target.value);setDirty(true)}}><option value="">Επίλεξε μέλος</option>{members.map(m=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select></label><label>Τίτλος<input maxLength={160} value={title} onChange={e=>{setTitle(e.target.value);setDirty(true)}}/></label><label>Έναρξη<input type="date" value={start} onChange={e=>{setStart(e.target.value);setDirty(true)}}/></label><label>Λήξη (προαιρετική)<input type="date" min={start} value={end} onChange={e=>{setEnd(e.target.value);setDirty(true)}}/></label><label>Στόχος<input maxLength={2000} value={content.goal} onChange={e=>changeContent({...content,goal:e.target.value})} placeholder="Γράψε τον στόχο του πλάνου"/></label><label>Προτιμήσεις / αλλεργίες<textarea aria-label="Προτιμήσεις / αλλεργίες" maxLength={4000} value={content.preferences} onChange={e=>changeContent({...content,preferences:e.target.value})}/></label><label className="nutrition-wide">Οδηγίες προς το μέλος<textarea aria-label="Οδηγίες προς το μέλος" maxLength={8000} value={content.notes} onChange={e=>changeContent({...content,notes:e.target.value})}/></label>{!selected&&plans.length>0&&<div className="nutrition-wide nutrition-actions"><select aria-label="Πλάνο για αντιγραφή" value={template} onChange={e=>setTemplate(e.target.value)} style={{maxWidth:450}}><option value="">Αντιγραφή γευμάτων από υπάρχον πλάνο</option>{plans.map(p=><option key={p.id} value={p.id}>{memberName(p.member_id)} · {p.title}</option>)}</select><button type="button" disabled={!template} onClick={()=>{const p=plans.find(p=>p.id===template);if(p)changeContent(copy(p.content))}}>Χρήση πλάνου</button></div>}</div>
 <div className="nutrition-day-tabs" role="tablist" aria-label="Ημέρα πλάνου">{nutritionDays.map((name,index)=><button type="button" role="tab" aria-selected={index===day} aria-controls="nutrition-day-editor" id={`nutrition-tab-${index}`} key={name} onClick={()=>setDay(index)}>{name}</button>)}</div><div id="nutrition-day-editor" role="tabpanel" aria-labelledby={`nutrition-tab-${day}`}><div className="nutrition-actions"><h2>{nutritionDays[day]}</h2><button type="button" onClick={()=>{if(window.confirm("Να αντικατασταθούν τα γεύματα των άλλων ημερών με αυτά της επιλεγμένης ημέρας;"))changeContent({...content,days:content.days.map(()=>copy(content.days[day]))})}}>Αντιγραφή ημέρας σε όλη την εβδομάδα</button></div>
 {content.days[day].map((meal,index)=><article key={index} className="nutrition-meal"><div className="nutrition-meal-head"><strong>Γεύμα {index+1}</strong><button type="button" aria-label={`Αφαίρεση γεύματος ${index+1}`} onClick={()=>{const next=copy(content);next.days[day].splice(index,1);changeContent(next)}}>Αφαίρεση</button></div><div className="nutrition-meal-fields"><label>Όνομα γεύματος<input maxLength={120} value={meal.name} onChange={e=>changeMeal(index,"name",e.target.value)}/></label><label>Ώρα<input type="time" value={meal.time} onChange={e=>changeMeal(index,"time",e.target.value)}/></label><label>Τρόφιμα<textarea aria-label="Τρόφιμα" maxLength={4000} value={meal.food} onChange={e=>changeMeal(index,"food",e.target.value)} placeholder="Γράψε τα τρόφιμα του γεύματος"/></label><label>Ποσότητες<textarea aria-label="Ποσότητες" maxLength={2000} value={meal.quantity} onChange={e=>changeMeal(index,"quantity",e.target.value)} placeholder="π.χ. γραμμάρια ή τεμάχια"/></label><label className="nutrition-wide">Εναλλακτική επιλογή<input maxLength={2000} value={meal.alternative} onChange={e=>changeMeal(index,"alternative",e.target.value)}/></label><div className="nutrition-macros">{(["kcal","protein","carbs","fat"] as const).map((key,i)=><label key={key}>{["Θερμίδες (kcal)","Πρωτεΐνη (g)","Υδατάνθρακες (g)","Λίπος (g)"][i]}<input type="number" min="0" max="100000" step="0.1" value={meal[key]} onChange={e=>changeMeal(index,key,e.target.value)}/></label>)}</div></div></article>)}<button type="button" disabled={content.days[day].length>=20} onClick={()=>{const next=copy(content);next.days[day].push(newMeal());changeContent(next)}}>＋ Προσθήκη γεύματος</button><Totals meals={content.days[day]}/><p>Τα σύνολα αθροίζουν τις τιμές που συμπληρώνεις στα γεύματα.</p></div></fieldset><div className="nutrition-actions"><button disabled={busy} onClick={()=>void save("draft")}>Αποθήκευση προχείρου</button><button disabled={busy} className="primary" onClick={()=>void save("published")}>{busy?"Αποθήκευση…":"Αποθήκευση & δημοσίευση"}</button>{selected&&<button disabled={busy} onClick={()=>{if(window.confirm("Να αρχειοθετηθεί το πλάνο και να αφαιρεθεί από την προβολή του μέλους;"))void save("archived")}}>Αρχειοθέτηση</button>}</div></>:
 selected?<><div className="nutrition-actions"><button onClick={()=>setSelected(null)}>‹ Όλα τα πλάνα</button><button onClick={()=>window.print()}>Εκτύπωση / PDF</button>{owner&&<><button onClick={()=>begin(selected)}>Επεξεργασία</button><button onClick={()=>begin(selected,true)}>Αντίγραφο ως νέο πλάνο</button></>}</div><div className="nutrition-print"><h2>{selected.title}</h2><h3>{memberName(selected.member_id)}</h3><p>{date(selected.starts_on)} — {date(selected.ends_on)} · {states[selected.status]}</p>{selected.content.goal&&<p><b>Στόχος: </b>{selected.content.goal}</p>}{selected.content.preferences&&<p style={{whiteSpace:"pre-wrap"}}><b>Προτιμήσεις / αλλεργίες: </b>{selected.content.preferences}</p>}{selected.content.notes&&<p style={{whiteSpace:"pre-wrap"}}><b>Οδηγίες: </b>{selected.content.notes}</p>}{selected.content.days.map((meals,index)=><section key={index} className="nutrition-read-day"><h3>{nutritionDays[index]}</h3>{meals.filter(m=>m.food.trim()||m.quantity.trim()).map((meal,i)=><div key={i} className="nutrition-read-meal"><b>{meal.name} {meal.time}</b><div><p>{meal.food}</p>{meal.quantity&&<p><b>Ποσότητες: </b>{meal.quantity}</p>}{meal.alternative&&<p><b>Εναλλακτική: </b>{meal.alternative}</p>}</div></div>)}<Totals meals={meals}/></section>)}</div></>:
 <><input aria-label="Αναζήτηση πλάνων" placeholder={owner?"Αναζήτηση μέλους ή πλάνου…":"Αναζήτηση πλάνου…"} value={query} onChange={e=>setQuery(e.target.value)}/>{!loaded&&!error&&<p role="status">Φόρτωση πλάνων…</p>}<div className="nutrition-plan-list">{visible.map(p=><article key={p.id}><span className="nutrition-state">{states[p.status]}</span><h2>{p.title}</h2><b>{memberName(p.member_id)}</b><p>{date(p.starts_on)} — {date(p.ends_on)}</p><button onClick={()=>open(p)}>Άνοιγμα πλάνου</button></article>)}</div>{loaded&&!visible.length&&<p className="nutrition-empty">{owner?"Δεν υπάρχουν πλάνα. Πάτησε «Νέο πλάνο» για να ξεκινήσεις.":"Δεν έχει δημοσιευτεί πλάνο διατροφής για εσένα ακόμη."}</p>}</>}
 </section>;
}
function Totals({meals}:{meals:Meal[]}){const sums=mealTotals(meals);return <div className="nutrition-totals" aria-label="Σύνολα ημέρας">{["kcal","g πρωτεΐνης","g υδατανθράκων","g λίπους"].map((label,index)=><span key={label}><b>{Number(sums[index].toFixed(1))}</b> {label}</span>)}</div>}
