"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {api} from "../../lib/supabase-rest";

type Member={id:string;auth_user_id:string;full_name:string;email:string|null;phone:string|null;qr_token:string;active:boolean};
type Checkin={id:number;member_id:string;checked_in_at:string;method:string;notes:string|null};
type Finance={id:number;member_id:string|null;kind:"income"|"expense";category:string;amount:number;occurred_on:string;notes:string|null};
type Measurement={id:number;member_id:string;measured_on:string;weight_kg:number|null;body_fat_percent:number|null;waist_cm:number|null;notes:string|null};
type Notification={id:number;member_id:string|null;channel:string;title:string;body:string;status:string;created_at:string};
const today=()=>new Date().toISOString().slice(0,10);

export default function OperationsPanel(){
 const [tab,setTab]=useState("checkin"),[members,setMembers]=useState<Member[]>([]),[checkins,setCheckins]=useState<Checkin[]>([]),[finances,setFinances]=useState<Finance[]>([]),[measurements,setMeasurements]=useState<Measurement[]>([]),[notifications,setNotifications]=useState<Notification[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const token=()=>localStorage.getItem("basement_access_token")||"";
 const load=useCallback(async()=>{try{const [m,c,f,x,n]=await Promise.all([
  api("/rest/v1/members?select=id,auth_user_id,full_name,email,phone,qr_token,active&order=full_name",token()),
  api("/rest/v1/gym_checkins?select=*&order=checked_in_at.desc&limit=50",token()),
  api("/rest/v1/financial_entries?select=*&order=occurred_on.desc,created_at.desc&limit=100",token()),
  api("/rest/v1/member_measurements?select=*&order=measured_on.desc&limit=100",token()),
  api("/rest/v1/outbound_notifications?select=*&order=created_at.desc&limit=50",token())]);
  if(!m.ok||!c.ok||!f.ok||!x.ok||!n.ok)throw 0;setMembers(await m.json());setCheckins(await c.json());setFinances(await f.json());setMeasurements(await x.json());setNotifications(await n.json())}catch{setMessage("Δεν φορτώθηκαν τα δεδομένα λειτουργίας.")}},[]);
 useEffect(()=>{void load()},[load]);
 const memberName=(id:string|null)=>members.find(m=>m.id===id)?.full_name||"—";
 async function submit(e:FormEvent<HTMLFormElement>,table:string,success:string){e.preventDefault();setBusy(true);setMessage("");const form=e.currentTarget,data:Record<string,string|number|File>=Object.fromEntries(new FormData(form));for(const k of Object.keys(data))if(data[k]==="")delete data[k];for(const k of ["amount","weight_kg","body_fat_percent","waist_cm"])if(data[k]!==undefined)data[k]=Number(data[k]);const r=await api(`/rest/v1/${table}`,token(),{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify(data)});setBusy(false);if(r.ok){form.reset();setMessage(success);await load()}else{const d=await r.json().catch(()=>({}));setMessage(d.message||"Η ενέργεια δεν ολοκληρώθηκε.")}}
 const month=finances.filter(f=>f.occurred_on.slice(0,7)===today().slice(0,7)),income=month.filter(f=>f.kind==="income").reduce((s,f)=>s+Number(f.amount),0),expenses=month.filter(f=>f.kind==="expense").reduce((s,f)=>s+Number(f.amount),0);
 const active=members.filter(m=>m.active).length,checkinsToday=checkins.filter(c=>c.checked_in_at.slice(0,10)===today()).length;
 const nav=[["checkin","Check-in"],["finance","Ταμείο"],["progress","Μετρήσεις"],["health","Υγεία & EMS"],["messages","Ειδοποιήσεις"],["reports","Αναφορές"]];
 const memberSelect=<><option value="">Επίλεξε μέλος</option>{members.map(m=><option value={m.id} key={m.id}>{m.full_name}{m.active?"":" (ανενεργό)"}</option>)}</>;
 return <div className="operations"><div className="panel-title"><div><span className="kicker">ΛΕΙΤΟΥΡΓΙΕΣ</span><h2>Διαχείριση γυμναστηρίου</h2><p>Παρουσίες, ταμείο, πρόοδος, υγεία και επικοινωνία.</p></div></div>{message&&<p className="notice">{message}</p>}<nav className="settings-nav">{nav.map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {tab==="checkin"&&<div className="ops-grid"><form className="admin-form" onSubmit={e=>void submit(e,"gym_checkins","Το check-in καταχωρίστηκε.")}><h3>Νέο check-in</h3><label>Μέλος<select name="member_id" required>{memberSelect}</select></label><label>Τρόπος<select name="method"><option value="manual">Χειροκίνητα</option><option value="qr">QR code</option></select></label><label>Σημείωση<input name="notes"/></label><button disabled={busy}>Καταχώριση παρουσίας</button></form><section className="ops-list"><h3>Τελευταίες παρουσίες</h3>{checkins.map(c=><article key={c.id}><b>{memberName(c.member_id)}</b><span>{new Date(c.checked_in_at).toLocaleString("el-GR")} · {c.method==="qr"?"QR":"Χειροκίνητα"}</span></article>)}</section></div>}
 {tab==="finance"&&<div className="ops-grid"><form className="admin-form" onSubmit={e=>void submit(e,"financial_entries","Η κίνηση καταχωρίστηκε.")}><h3>Νέα κίνηση</h3><label>Τύπος<select name="kind"><option value="income">Έσοδο</option><option value="expense">Έξοδο</option></select></label><label>Κατηγορία<select name="category"><option>Συνδρομή</option><option>Personal Training</option><option>EMS</option><option>Πώληση</option><option>Μισθοδοσία</option><option>Ενοίκιο</option><option>Λογαριασμοί</option><option>Άλλο</option></select></label><label>Ποσό (€)<input name="amount" type="number" min="0" step="0.01" required/></label><label>Ημερομηνία<input name="occurred_on" type="date" defaultValue={today()} required/></label><label>Μέλος (προαιρετικό)<select name="member_id">{memberSelect}</select></label><label>Σημείωση<input name="notes"/></label><button disabled={busy}>Καταχώριση</button></form><section className="ops-list"><h3>Κινήσεις</h3>{finances.map(f=><article key={f.id} className={f.kind}><b>{f.kind==="income"?"+":"−"}{Number(f.amount).toFixed(2)} € · {f.category}</b><span>{f.occurred_on} · {memberName(f.member_id)}</span></article>)}</section></div>}
 {tab==="progress"&&<div className="ops-grid"><form className="admin-form" onSubmit={e=>void submit(e,"member_measurements","Η μέτρηση αποθηκεύτηκε.")}><h3>Νέα μέτρηση</h3><label>Μέλος<select name="member_id" required>{memberSelect}</select></label><label>Ημερομηνία<input name="measured_on" type="date" defaultValue={today()} required/></label><label>Βάρος (kg)<input name="weight_kg" type="number" step="0.1"/></label><label>Λίπος (%)<input name="body_fat_percent" type="number" step="0.1"/></label><label>Μέση (cm)<input name="waist_cm" type="number" step="0.1"/></label><label>Σημειώσεις<input name="notes"/></label><button disabled={busy}>Αποθήκευση μέτρησης</button></form><section className="ops-list"><h3>Ιστορικό προόδου</h3>{measurements.map(x=><article key={x.id}><b>{memberName(x.member_id)}</b><span>{x.measured_on} · {x.weight_kg??"—"} kg · {x.body_fat_percent??"—"}% λίπος · {x.waist_cm??"—"} cm</span></article>)}</section></div>}
 {tab==="health"&&<HealthForm members={members} token={token()} setMessage={setMessage}/>}
 {tab==="messages"&&<div className="ops-grid"><form className="admin-form" onSubmit={e=>void submit(e,"outbound_notifications","Η ειδοποίηση αποθηκεύτηκε ως πρόχειρη.")}><h3>Νέα ειδοποίηση</h3><label>Μέλος<select name="member_id">{memberSelect}</select></label><label>Κανάλι<select name="channel"><option value="email">Email</option><option value="sms">SMS</option><option value="push">Push</option></select></label><label>Τίτλος<input name="title" required/></label><label>Μήνυμα<textarea name="body" required/></label><input type="hidden" name="status" value="draft"/><button disabled={busy}>Αποθήκευση πρόχειρου</button><p className="muted-copy">Για πραγματική αποστολή SMS/email/push θα συνδεθεί ο αντίστοιχος πάροχος.</p></form><section className="ops-list"><h3>Ιστορικό μηνυμάτων</h3>{notifications.map(n=><article key={n.id}><b>{n.channel.toUpperCase()} · {n.title}</b><span>{memberName(n.member_id)} · {n.status}</span></article>)}</section></div>}
 {tab==="reports"&&<><div className="dash-grid ops-stats"><article><small>Ενεργά μέλη</small><strong>{active}</strong></article><article><small>Check-in σήμερα</small><strong>{checkinsToday}</strong></article><article><small>Έσοδα μήνα</small><strong>{income.toFixed(0)}€</strong></article><article><small>Καθαρό μήνα</small><strong>{(income-expenses).toFixed(0)}€</strong></article></div><section className="settings-section"><header><h3>Σύνοψη μήνα</h3><p>Τα στοιχεία ενημερώνονται από τις καταχωρίσεις του ταμείου και των παρουσιών.</p></header><div className="report-bars"><div><span>Έσοδα</span><b>{income.toFixed(2)} €</b></div><div><span>Έξοδα</span><b>{expenses.toFixed(2)} €</b></div><div><span>Υπόλοιπο</span><b>{(income-expenses).toFixed(2)} €</b></div></div></section></>}
 </div>;
}

function HealthForm({members,token,setMessage}:{members:Member[];token:string;setMessage:(s:string)=>void}){
 const [memberId,setMemberId]=useState(""),[data,setData]=useState({emergency_contact:"",conditions:"",injuries:"",medications:"",notes:"",ems_consent:false}),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!memberId){setData({emergency_contact:"",conditions:"",injuries:"",medications:"",notes:"",ems_consent:false});return}void api(`/rest/v1/member_health_profiles?member_id=eq.${memberId}&select=*`,token).then(async r=>{const x=(await r.json())[0];if(x)setData({emergency_contact:x.emergency_contact||"",conditions:x.conditions||"",injuries:x.injuries||"",medications:x.medications||"",notes:x.notes||"",ems_consent:!!x.ems_consent})})},[memberId,token]);
 async function save(){if(!memberId)return;setBusy(true);const r=await api("/rest/v1/member_health_profiles?on_conflict=member_id",token,{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({member_id:memberId,...data,consent_at:data.ems_consent?new Date().toISOString():null,updated_at:new Date().toISOString()})});setBusy(false);setMessage(r.ok?"Τα στοιχεία υγείας αποθηκεύτηκαν.":"Δεν αποθηκεύτηκαν τα στοιχεία υγείας.")}
 return <section className="health-card"><h3>Ιατρικές σημειώσεις & συγκατάθεση EMS</h3><label>Μέλος<select value={memberId} onChange={e=>setMemberId(e.target.value)}><option value="">Επίλεξε μέλος</option>{members.map(m=><option value={m.id} key={m.id}>{m.full_name}</option>)}</select></label>{([['emergency_contact','Επικοινωνία ανάγκης'],['conditions','Παθήσεις / αντενδείξεις'],['injuries','Τραυματισμοί'],['medications','Φάρμακα'],['notes','Εσωτερικές σημειώσεις']] as const).map(([k,l])=><label key={k}>{l}<textarea value={data[k]} onChange={e=>setData(x=>({...x,[k]:e.target.value}))}/></label>)}<label className="health-consent"><input type="checkbox" checked={data.ems_consent} onChange={e=>setData(x=>({...x,ems_consent:e.target.checked}))}/> Υπάρχει υπογεγραμμένη συγκατάθεση EMS</label><button disabled={!memberId||busy} onClick={()=>void save()}>Αποθήκευση στοιχείων</button></section>;
}
