"use client";
import {useEffect,useState} from "react";
import {api} from "../../lib/supabase-rest";
import {athensDay,shiftDay} from "../../lib/reference-calendar";
import {useControlTheme} from "../../lib/control-theme";
import MemberRecordsPanel from "./member-records-panel";
import CreateMemberForm,{type CreatedMember} from "./create-member-form";
type Member={id:string;auth_user_id:string;full_name:string;phone:string;email:string;active:boolean};
type Package={id:string;member_id:string;starts_on:string;expires_on:string;sessions_remaining:number|null;status:string;created_at:string;package_templates:{name:string}|null};
export default function ReferenceMembers({focus,onCreated,onPackages,owner}:{focus:string;onCreated:(m:CreatedMember)=>void;onPackages:()=>void;owner:boolean}){
 const {config}=useControlTheme(),[members,setMembers]=useState<Member[]>([]),[packages,setPackages]=useState<Package[]>([]),[lastVisits,setLastVisits]=useState<Record<string,string>>({}),[filter,setFilter]=useState("all"),[query,setQuery]=useState(""),[detail,setDetail]=useState(focus),[creating,setCreating]=useState(false),[error,setError]=useState(""),[loaded,setLoaded]=useState(false);
 const today=athensDay();
 async function load(){try{const token=localStorage.getItem("basement_access_token")||"";async function all(path:string){const result=[];for(let offset=0;;offset+=1000){const r=await api(path+`&limit=1000&offset=${offset}`,token);if(!r.ok)throw Error("Δεν φορτώθηκαν τα μέλη.");const page=await r.json();result.push(...page);if(page.length<1000)return result;}}
 const [m,p,v]=await Promise.all([all("/rest/v1/members?select=id,auth_user_id,full_name,phone,email,active&order=full_name"),all("/rest/v1/member_packages?select=id,member_id,starts_on,expires_on,sessions_remaining,status,created_at,package_templates(name)&order=expires_on.desc"),all("/rest/v1/gym_checkins?select=member_id,checked_in_at&order=checked_in_at.desc")]);setMembers(m);setPackages(p);const visits:Record<string,string>={};v.forEach(x=>{if(!visits[x.member_id])visits[x.member_id]=x.checked_in_at});setLastVisits(visits);setLoaded(true);setError("")}catch(e){setError(String(e))}}
 useEffect(()=>{void load()},[]);useEffect(()=>{if(focus)setDetail(focus)},[focus]);
 const activePackages=(m:Member)=>packages.filter(p=>p.member_id===m.id&&["active","scheduled"].includes(p.status)&&p.starts_on<=today&&p.expires_on>=today);
 const state=(m:Member)=>{const p=activePackages(m);return p.length?p.some(x=>x.expires_on<=shiftDay(today,config.expiryDays))?"soon":"active":packages.some(x=>x.member_id===m.id&&x.starts_on>today)?"future":"expired"};
 const inactive=(m:Member)=>!m.active||!!lastVisits[m.id]&&lastVisits[m.id].slice(0,10)<shiftDay(today,-config.inactiveDays);
 const visible=members.filter(m=>(filter==="all"||(filter==="active"?activePackages(m).length:filter==="inactive"?inactive(m):state(m)===filter))&&`${m.full_name} ${m.phone||""} ${m.email||""}`.toLocaleLowerCase("el").includes(query.toLocaleLowerCase("el")));
 const labels:Record<string,string>={active:"Ενεργή",soon:"Λήγει σύντομα",expired:"Έχει λήξει",future:"Προγραμματισμένη"};
 if(detail)return <section><button className="reference-back" onClick={()=>setDetail("")}>‹ Επιστροφή στο μητρώο</button><MemberRecordsPanel focusAuthUserId={detail}/></section>;
 return <section><div className="reference-heading"><div><div className="eyebrow">Η ΕΙΚΟΝΑ ΤΟΥ CLUB ΣΟΥ</div><h1>Μέλη & ανανεώσεις<span>.</span></h1><p>{new Intl.DateTimeFormat("el-GR",{dateStyle:"full",timeZone:"Europe/Athens"}).format(new Date())}</p></div>{owner&&<button className="primary" onClick={()=>setCreating(!creating)}>＋ Νέο μέλος</button>}</div>{creating&&<div className="reference-panel reference-settings-card"><CreateMemberForm onCreated={m=>{onCreated(m);setCreating(false);void load();setDetail(m.id)}} onOpenPackages={onPackages}/></div>}
 <div className="reference-stats">{[{id:"all",label:"Σύνολο μελών",value:members.length,sub:"Όλες οι καταχωρίσεις"},{id:"active",label:"Ενεργές συνδρομές",value:members.filter(m=>activePackages(m).length).length,sub:"Σε ισχύ σήμερα"},{id:"soon",label:"Λήγουν σύντομα",value:members.filter(m=>state(m)==="soon").length,sub:`Σήμερα και στις επόμενες ${config.expiryDays} ημέρες`},{id:"expired",label:"Έχουν λήξει",value:members.filter(m=>state(m)==="expired").length,sub:"Χρειάζονται ανανέωση"}].map(s=><button className={filter===s.id?"chosen":""} key={s.id} onClick={()=>setFilter(s.id)}><span>{s.label}</span><strong>{loaded?s.value:"—"}</strong><small>{s.sub}</small></button>)}</div>{error&&<p role="alert" className="notice">{error}</p>}
 <div className="reference-workspace"><section className="reference-panel"><div className="reference-panel-head"><div><h2>Το μητρώο σου</h2><p>{visible.length} μέλη στη λίστα</p></div><div className="reference-member-tools"><input aria-label="Αναζήτηση μελών" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Αναζήτηση ονόματος ή τηλεφώνου"/><select aria-label="Κατάσταση συνδρομής" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Όλα τα μέλη</option><option value="active">Ενεργές συνδρομές</option><option value="soon">Λήγουν σύντομα</option><option value="expired">Έχουν λήξει</option><option value="inactive">Χωρίς πρόσφατη επίσκεψη</option></select></div></div><div className="reference-table-wrap"><table className="reference-member-table"><thead><tr><th>Μέλος</th><th>Συνδρομή</th><th>Λήξη</th><th>Ενέργειες</th></tr></thead><tbody>{visible.map(m=>{const all=packages.filter(p=>p.member_id===m.id),active=activePackages(m),p=active[0]||all[0],st=state(m);return <tr key={m.id}><td><div className="reference-person"><span className="reference-avatar">{m.full_name.split(" ").map(s=>s[0]).slice(0,2).join("")}</span><div><b>{m.full_name}</b><small>{m.phone||"Χωρίς τηλέφωνο"}</small></div></div></td><td>{active.map(x=><span className="reference-badge active" key={x.id}>{x.package_templates?.name} · {x.sessions_remaining??"∞"} συν.</span>)}<span className={`reference-badge ${st}`}>{labels[st]}</span></td><td><b>{p?p.expires_on.split("-").reverse().join("/"):"Χωρίς συνδρομή"}</b>{inactive(m)&&<small>Χωρίς πρόσφατη επίσκεψη</small>}</td><td><button onClick={()=>setDetail(m.auth_user_id)}>Καρτέλα / ανανέωση ↗</button></td></tr>})}</tbody></table>{!visible.length&&<p className="reference-empty">Δεν υπάρχουν μέλη σε αυτή την κατηγορία.</p>}</div></section><aside><div className="reference-note"><h2>Μείνε ένα βήμα μπροστά.</h2><p>Οι συνδρομές που λήγουν σύντομα συγκεντρώνονται εδώ, για να οργανώνεις τις ανανεώσεις σου.</p><button onClick={()=>setFilter("soon")}>Δες τις επόμενες λήξεις ↗</button></div><section className="reference-history"><h2>Τελευταίες ανανεώσεις</h2>{[...packages].sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,6).map(p=><div key={p.id}><b>{members.find(m=>m.id===p.member_id)?.full_name||"Μέλος"}</b><span>{p.package_templates?.name} · έως {p.expires_on.split("-").reverse().join("/")}</span></div>)}</section></aside></div></section>
}
