"use client";
import {useEffect,useState} from "react";
import {api} from "../../lib/supabase-rest";
import {cleanConfig,referenceConfig,useControlTheme,type ControlConfig} from "../../lib/control-theme";
import AvailabilitySettings from "./availability-settings";
import CapacitySettings from "./capacity-settings";
import SettingsPanel from "./settings-panel";
export type ServiceConfig={id:string;name:string;duration_minutes:number;default_capacity:number;color:string;active:boolean;waiting_list_enabled:boolean;overbooking_enabled:boolean;online_booking_enabled:boolean};
const colorLabels={primary:"Κύριο χρώμα",header:"Header",background:"Φόντο",green:"Επιτυχία",orange:"Προειδοποίηση",red:"Ακύρωση",blue:"Διαθέσιμο"};
export default function ReferenceSettings({profile}:{profile:{full_name:string|null;role:string}}){
 const theme=useControlTheme(),[config,setConfig]=useState<ControlConfig>(referenceConfig),[services,setServices]=useState<ServiceConfig[]>([]),[rules,setRules]=useState({openingTime:"08:00",closingTime:"22:00",bookingMinHours:1,bookingMaxDays:365,maxActiveBookings:8}),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[message,setMessage]=useState("");
 const token=()=>localStorage.getItem("basement_access_token")||"";
 async function load(){try{const [a,b,c]=await Promise.all([api("/rest/v1/rpc/basement_brand_config",token(),{method:"POST",body:"{}"}),api("/rest/v1/services?select=*&order=created_at",token()),api("/rest/v1/app_settings?key=eq.control_center_settings&select=value",token())]);if(!a.ok||!b.ok||!c.ok)throw Error("Δεν φορτώθηκαν οι ρυθμίσεις.");setConfig(cleanConfig(await a.json()));setServices(await b.json());const v=(await c.json())[0]?.value||{};setRules(x=>({...x,...Object.fromEntries(Object.keys(x).filter(k=>v[k]!==undefined).map(k=>[k,v[k]]))}));setLoaded(true)}catch(e){setMessage(String(e))}}
 useEffect(()=>{void load()},[]);
 async function save(){setBusy(true);setMessage("");try{const r=await api("/rest/v1/rpc/basement_save_reference_settings",token(),{method:"POST",body:JSON.stringify({p_config:config,p_rules:rules,p_services:services})});if(!r.ok){const d=await r.json();throw Error(d.message||"Δεν αποθηκεύτηκαν οι ρυθμίσεις.")}await load();theme.refresh();window.dispatchEvent(new Event("basement-settings-changed"));setMessage("Οι ρυθμίσεις αποθηκεύτηκαν. Ημερολόγιο και portal ενημερώθηκαν.")}catch(e){setMessage(e instanceof Error?e.message:"Δεν ολοκληρώθηκε η αποθήκευση.")}finally{setBusy(false)}}
 const field=(key:keyof ServiceConfig,i:number,value:unknown)=>setServices(all=>all.map((s,n)=>n===i?{...s,[key]:value}:s));
 return <section className="reference-settings"><div className="reference-heading"><div><div className="eyebrow">ΧΩΡΙΣ ΑΛΛΑΓΗ ΚΩΔΙΚΑ</div><h1>Settings Center<span>.</span></h1><p>Οι αλλαγές εφαρμόζονται σε ημερολόγιο, κρατήσεις και portal.</p></div><button className="primary" disabled={busy||!loaded} onClick={()=>void save()}>{busy?"Αποθήκευση…":"Αποθήκευση όλων"}</button></div>{message&&<p className="notice" role="status">{message}</p>}
 <div className="reference-settings-grid"><section className="reference-panel reference-settings-card"><h2>Branding & χρώματα</h2><label>Όνομα<input value={config.name} onChange={e=>setConfig({...config,name:e.target.value})}/></label><label>Υπότιτλος<input value={config.subtitle} onChange={e=>setConfig({...config,subtitle:e.target.value})}/></label><div className="reference-mini-grid">{(Object.keys(colorLabels) as (keyof typeof colorLabels)[]).map(key=><label key={key}>{colorLabels[key]}<span className="reference-color-input"><input type="color" value={config.colors[key]} onChange={e=>setConfig({...config,colors:{...config.colors,[key]:e.target.value}})}/><input aria-label={colorLabels[key]+" κωδικός"} value={config.colors[key]} pattern="#[0-9a-fA-F]{6}" onChange={e=>setConfig({...config,colors:{...config.colors,[key]:e.target.value}})}/></span></label>)}</div></section>
 <section className="reference-panel reference-settings-card"><h2>Ημερολόγιο</h2><div className="reference-mini-grid"><label>Άνοιγμα<input type="time" value={rules.openingTime} onChange={e=>setRules({...rules,openingTime:e.target.value})}/></label><label>Κλείσιμο<input type="time" value={rules.closingTime} onChange={e=>setRules({...rules,closingTime:e.target.value})}/></label><label>Βήμα λεπτών<select value={config.step} onChange={e=>setConfig({...config,step:Number(e.target.value)})}>{[10,15,20,30,40,60].map(n=><option key={n}>{n}</option>)}</select></label><label>Αρχική προβολή<select value={config.defaultView} onChange={e=>setConfig({...config,defaultView:e.target.value})}><option value="day">Ημέρα</option><option value="week">Εβδομάδα</option></select></label><label>Χρώματα ημερολογίου<select value={config.calendarColorMode} onChange={e=>setConfig({...config,calendarColorMode:e.target.value})}><option value="status">Ανά κατάσταση (Control Center)</option><option value="service">Ανά υπηρεσία</option></select></label></div><h2>Κανόνες κρατήσεων</h2><div className="reference-mini-grid">{([["bookingMinHours","Κράτηση πριν (ώρες)"],["bookingMaxDays","Άνοιγμα προγράμματος (ημέρες)"],["maxActiveBookings","Μέγιστες ενεργές κρατήσεις"]] as const).map(([key,label])=><label key={key}>{label}<input type="number" min="0" value={rules[key]} onChange={e=>setRules({...rules,[key]:Number(e.target.value)})}/></label>)}</div><p className="form-help">Κάθε κράτηση αφαιρεί 1 συνεδρία. Ακύρωση πριν την έναρξη την επιστρέφει. Check-in / No-show δεν χρεώνουν δεύτερη φορά.</p><div className="reference-mini-grid">{([["lowSessions","Alert χαμηλών συνεδριών"],["expiryDays","Alert λήξης (ημέρες)"],["inactiveDays","Ανενεργό μέλος μετά από ημέρες"]] as const).map(([key,label])=><label key={key}>{label}<input type="number" min="0" max="730" value={config[key]} onChange={e=>setConfig({...config,[key]:Number(e.target.value)})}/></label>)}</div></section>
 <section className="reference-panel reference-settings-card reference-wide"><div className="section-row"><div><h2>Υπηρεσίες</h2><p>Όνομα, χωρητικότητα, διάρκεια και χρώμα αλλάζουν εδώ.</p></div><button onClick={()=>setServices(s=>[...s,{id:"",name:"Νέα υπηρεσία",duration_minutes:60,default_capacity:1,color:config.colors.primary,active:true,waiting_list_enabled:true,overbooking_enabled:true,online_booking_enabled:true}])}>＋ Υπηρεσία</button></div><div className="reference-service-settings">{services.map((s,i)=><div className="reference-service-setting" key={s.id||i}><label>Όνομα<input value={s.name} onChange={e=>field("name",i,e.target.value)}/></label><label>Θέσεις<input type="number" min="1" max="30" value={s.default_capacity} onChange={e=>field("default_capacity",i,+e.target.value)}/></label><label>Διάρκεια<input type="number" min="5" max="240" value={s.duration_minutes} onChange={e=>field("duration_minutes",i,+e.target.value)}/></label><label>Χρώμα<input type="color" value={s.color} onChange={e=>field("color",i,e.target.value)}/></label>{([["active","Ενεργή"],["waiting_list_enabled","Waiting List"],["overbooking_enabled","Owner overbooking"],["online_booking_enabled","Online"]] as const).map(([key,label])=><label className="reference-check" key={key}><input type="checkbox" checked={s[key]} onChange={e=>field(key,i,e.target.checked)}/>{label}</label>)}</div>)}</div></section></div>
 {loaded&&<><AvailabilitySettings services={services.filter(s=>s.id)}/><CapacitySettings services={services.filter(s=>s.id)}/></>}
 <details className="reference-panel reference-advanced"><summary>Πρόσθετες ρυθμίσεις · ειδοποιήσεις, αυτοματισμοί & περιορισμοί</summary><SettingsPanel owner profile={profile}/></details></section>;
}
