"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {api} from "../../lib/supabase-rest";

type Member={id:string;full_name:string};
type Service={id:string;name:string};
type Restriction={id:string;member_id:string;service_id:string|null;weekday:number|null;start_time:string|null;end_time:string|null;reason:string;active:boolean};
const days=["","Δευτέρα","Τρίτη","Τετάρτη","Πέμπτη","Παρασκευή","Σάββατο","Κυριακή"];
export default function RestrictionSettings(){
 const [members,setMembers]=useState<Member[]>([]),[services,setServices]=useState<Service[]>([]),[rows,setRows]=useState<Restriction[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const token=()=>localStorage.getItem("basement_access_token")||"";
 const load=useCallback(async()=>{const [m,s,r]=await Promise.all([api("/rest/v1/members?select=id,full_name&active=eq.true&order=full_name",token()),api("/rest/v1/services?select=id,name&active=eq.true&order=name",token()),api("/rest/v1/booking_restrictions?select=*&order=created_at.desc",token())]);if(m.ok)setMembers(await m.json());if(s.ok)setServices(await s.json());if(r.ok)setRows(await r.json())},[]);
 useEffect(()=>{void load()},[load]);
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form);setBusy(true);setMessage("");const body={member_id:f.get("member_id"),service_id:f.get("service_id")||null,weekday:f.get("weekday")?Number(f.get("weekday")):null,start_time:f.get("start_time")||null,end_time:f.get("end_time")||null,reason:f.get("reason")||"",active:true};const r=await api("/rest/v1/booking_restrictions",token(),{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify(body)});setBusy(false);if(r.ok){form.reset();setMessage("Ο περιορισμός αποθηκεύτηκε.");await load()}else{const d=await r.json().catch(()=>({}));setMessage(d.message||"Δεν αποθηκεύτηκε ο περιορισμός.")}}
 async function remove(id:string){setBusy(true);const r=await api(`/rest/v1/booking_restrictions?id=eq.${id}`,token(),{method:"DELETE"});setBusy(false);if(r.ok){setMessage("Ο περιορισμός αφαιρέθηκε.");await load()}else setMessage("Δεν αφαιρέθηκε ο περιορισμός.")}
 return <section className="settings-section restriction-settings"><header><h3>Περιορισμοί συγκεκριμένων μελών</h3><p>Μπλοκάρεις μέλος από συγκεκριμένη υπηρεσία, ημέρα ή ώρα. Κενά πεδία σημαίνουν «όλες».</p></header>{message&&<p className="notice">{message}</p>}<form className="restriction-form" onSubmit={add}><label>Μέλος<select name="member_id" required><option value="">Επίλεξε</option>{members.map(m=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select></label><label>Υπηρεσία<select name="service_id"><option value="">Όλες</option>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Ημέρα<select name="weekday"><option value="">Όλες</option>{days.slice(1).map((d,i)=><option value={i+1} key={d}>{d}</option>)}</select></label><label>Από<input type="time" name="start_time"/></label><label>Έως<input type="time" name="end_time"/></label><label>Λόγος<input name="reason" placeholder="π.χ. μόνο πρωινά"/></label><button disabled={busy}>＋ Προσθήκη</button></form><div className="restriction-list">{rows.map(r=><article key={r.id}><span><b>{members.find(m=>m.id===r.member_id)?.full_name||"Μέλος"}</b><small>{services.find(s=>s.id===r.service_id)?.name||"Όλες οι υπηρεσίες"} · {r.weekday?days[r.weekday]:"Όλες οι ημέρες"} · {r.start_time?.slice(0,5)||"όλη μέρα"}{r.end_time?`–${r.end_time.slice(0,5)}`:""}{r.reason?` · ${r.reason}`:""}</small></span><button type="button" disabled={busy} onClick={()=>void remove(r.id)}>Αφαίρεση</button></article>)}</div></section>;
}
