"use client";
import {useEffect,useState} from "react";
import {api} from "../../lib/supabase-rest";

type Service={id:string;name:string;duration_minutes:number;default_capacity:number;online_booking_enabled:boolean;waiting_list_enabled:boolean;active:boolean};
type Kind="toggle"|"number"|"time"|"date"|"text"|"select";
type Def={key:string;label:string;kind:Kind;options?:string[];help?:string};
type Values=Record<string,string|number|boolean>;
const D:Record<string,Def[]>={
  business:[
    {key:"businessName",label:"Όνομα επιχείρησης",kind:"text"},{key:"businessEmail",label:"Email",kind:"text"},{key:"businessPhone",label:"Τηλέφωνο",kind:"text"},{key:"currency",label:"Νόμισμα / μονάδα πακέτου",kind:"select",options:["Συνεδρίες","Ευρώ (€)"]},{key:"timeFormat",label:"Μορφή ώρας",kind:"select",options:["24 ώρες","12 ώρες"]},{key:"gdprConsent",label:"Αποδοχή όρων και GDPR",kind:"toggle"}
  ],bookings:[
    {key:"bookingMinHours",label:"Ελάχιστες ώρες πριν από νέα κράτηση",kind:"number"},{key:"bookingMaxDays",label:"Μέγιστες ημέρες κράτησης στο μέλλον",kind:"number"},{key:"maxAvailableDate",label:"Μέγιστη διαθέσιμη ημερομηνία",kind:"date"},{key:"cancelMinMinutes",label:"Ελάχιστα λεπτά πριν από ακύρωση",kind:"number"},{key:"lateCancelAllowedCount",label:"Επιτρεπόμενες εκπρόθεσμες ακυρώσεις",kind:"number"},{key:"moveMinHours",label:"Ελάχιστες ώρες πριν από μεταφορά",kind:"number"},{key:"previousDayDeadline",label:"Προθεσμία κράτησης για επόμενη ημέρα",kind:"time"},{key:"reminderHours",label:"Ώρες πριν από υπενθύμιση",kind:"number"},{key:"lateCancelNoCredit",label:"Εκπρόθεσμη ακύρωση χωρίς επιστροφή συνεδρίας",kind:"toggle"},{key:"disableCustomerMove",label:"Απενεργοποίηση μεταφοράς από μέλη",kind:"toggle"},{key:"openingTime",label:"Έναρξη ωραρίου",kind:"time"},{key:"closingTime",label:"Λήξη ωραρίου",kind:"time"},{key:"pauseBookings",label:"Παύση όλων των νέων κρατήσεων",kind:"toggle"},{key:"activeCustomersOnly",label:"Κρατήσεις μόνο από ενεργά μέλη",kind:"toggle"},{key:"existingCustomerBooking",label:"Κράτηση ως υπάρχον μέλος",kind:"toggle"},{key:"newCustomerBooking",label:"Κράτηση ως νέο μέλος",kind:"toggle"},{key:"guestBooking",label:"Κράτηση χωρίς λογαριασμό",kind:"toggle"},{key:"showAvailableSpots",label:"Εμφάνιση διαθέσιμων θέσεων",kind:"toggle"},{key:"termsPage",label:"Όροι πριν από την κράτηση",kind:"toggle"},{key:"bookingMessages",label:"Μηνύματα κατά την κράτηση",kind:"toggle"}
  ],calendar:[
    {key:"customCalendar",label:"Custom προβολή ημερολογίου",kind:"toggle"},{key:"adminNotes",label:"Σημειώσεις μόνο για διαχειριστή",kind:"toggle"},{key:"colorPerService",label:"Χρώμα ανά υπηρεσία",kind:"toggle"},{key:"lastNameFirst",label:"Να εμφανίζεται πρώτα το επώνυμο",kind:"toggle"},{key:"showEndTime",label:"Εμφάνιση ώρας λήξης",kind:"toggle"},{key:"showStaffAsNote",label:"Εμφάνιση γυμναστή ως σημείωση",kind:"toggle"},{key:"hideZeroCustomer",label:"Απόκρυψη πλήρων ωρών από μέλη",kind:"toggle"},{key:"hideZeroAdmin",label:"Απόκρυψη πλήρων ωρών από διαχειριστή",kind:"toggle"},{key:"showServiceName",label:"Εμφάνιση ονόματος υπηρεσίας",kind:"toggle"},{key:"dependentAvailability",label:"Εξαρτημένη διαθεσιμότητα χωρίς επικάλυψη",kind:"toggle"},{key:"overlapAvailability",label:"Επικαλυπτόμενη διαθεσιμότητα",kind:"toggle"},{key:"hatchUnavailable",label:"Διαγράμμιση μη διαθέσιμων ωρών",kind:"toggle"},{key:"hatchAvailable",label:"Διαγράμμιση διαθέσιμων ωρών",kind:"toggle"},{key:"fixedPositions",label:"Ενεργοποίηση σταθερών θέσεων",kind:"toggle"},{key:"fixedPositionsAffectCapacity",label:"Οι σταθερές θέσεις επηρεάζουν τη διαθεσιμότητα",kind:"toggle"},{key:"hideFixedPositions",label:"Απόκρυψη σταθερών θέσεων",kind:"toggle"},{key:"slotDurationMode",label:"Διάρκεια slot",kind:"select",options:["Ανάλογα με την υπηρεσία","10 λεπτά","20 λεπτά","30 λεπτά","40 λεπτά","60 λεπτά"]},{key:"checkIn",label:"Check-in μελών",kind:"toggle"},{key:"chooseStaffOnMove",label:"Επιλογή γυμναστή στη μεταφορά",kind:"toggle"},{key:"changeServiceOnMove",label:"Αλλαγή υπηρεσίας στη μεταφορά",kind:"toggle"},{key:"moveToPastAdmin",label:"Μεταφορά στο παρελθόν από διαχειριστή",kind:"toggle"},{key:"keepStatusOnMove",label:"Η μεταφορά δεν αλλάζει την κατάσταση",kind:"toggle"}
  ],automation:[
    {key:"autoComplete",label:"Αυτόματη ολοκλήρωση ραντεβού",kind:"toggle"},{key:"autoConfirm",label:"Αυτόματη επιβεβαίωση κράτησης",kind:"toggle"},{key:"unconfirmedToWaitlist",label:"Μη επιβεβαιωμένες κρατήσεις σε αναμονή",kind:"toggle"},{key:"oneReminderPerDay",label:"Μία υπενθύμιση ανά ημέρα",kind:"toggle"},{key:"remindersEnabled",label:"Αποστολή υπενθυμίσεων",kind:"toggle"},{key:"customEditedColor",label:"Ξεχωριστό χρώμα επεξεργασμένης κράτησης",kind:"toggle"},{key:"paidColor",label:"Ξεχωριστό χρώμα πληρωμένης κράτησης",kind:"toggle"},{key:"paidDate",label:"Καταγραφή ημερομηνίας πληρωμής",kind:"toggle"},{key:"adminVisibilityDays",label:"Ημέρες ιστορικού διαχειριστή",kind:"number"},{key:"staffScheduleLink",label:"Σύνδεσμος προγράμματος γυμναστή",kind:"toggle"},{key:"staffScheduleNote",label:"Σημείωση στο πρόγραμμα γυμναστή",kind:"toggle"},{key:"questionnaires",label:"Ερωτηματολόγια υπηρεσιών",kind:"toggle"},{key:"incomeTools",label:"Διαχείριση εσόδων/εξόδων",kind:"toggle"}
  ],waitlist:[
    {key:"waitlistEnabled",label:"Ενεργοποίηση λίστας αναμονής",kind:"toggle"},{key:"autoConfirmWaitlist",label:"Αυτόματη επιβεβαίωση πρώτου μέλους",kind:"toggle"},{key:"waitlistConfirmationHours",label:"Ώρες για επιβεβαίωση θέσης",kind:"number"},{key:"overLimitToWaitlist",label:"Κρατήσεις πάνω από το όριο μπαίνουν σε αναμονή",kind:"toggle"},{key:"waitlistUpdateLink",label:"Αυτόματος σύνδεσμος ενημέρωσης",kind:"toggle"},{key:"skipNewCustomerChecks",label:"Παράλειψη ελέγχων για νέα μέλη",kind:"toggle"},{key:"waitlistLimit",label:"Μέγιστες θέσεις αναμονής ανά μέλος",kind:"number"}
  ],subscriptions:[
    {key:"creditsRequired",label:"Απαραίτητες διαθέσιμες συνεδρίες",kind:"toggle"},{key:"bookingsWithoutCredits",label:"Κρατήσεις χωρίς συνεδρίες",kind:"number"},{key:"newCustomerOutsideSubscription",label:"Νέα μέλη χωρίς ενεργή συνδρομή",kind:"toggle"},{key:"autoConfirmExisting",label:"Αυτόματη επιβεβαίωση ενεργών μελών",kind:"toggle"},{key:"serviceSubscriptionDates",label:"Ημερομηνίες συνδρομής ανά υπηρεσία",kind:"toggle"},{key:"blockAfterExpiry",label:"Απαγόρευση μετά τη λήξη",kind:"toggle"},{key:"maxAutoExtendDays",label:"Μέγιστη αυτόματη παράταση (ημέρες)",kind:"number"},{key:"expiryReminderDays",label:"Υπενθύμιση λήξης πριν από Χ ημέρες",kind:"number"},{key:"creditsReminder",label:"Υπενθύμιση όταν απομένουν Χ συνεδρίες",kind:"number"},{key:"maxBookingsPerPeriod",label:"Μέγιστες κρατήσεις ανά περίοδο (0 = χωρίς όριο)",kind:"number"},{key:"ignoreCancelledInLimit",label:"Οι ακυρωμένες δεν μετράνε στο όριο",kind:"toggle"},{key:"ignoreMovedInLimit",label:"Οι μεταφερμένες δεν μετράνε στο όριο",kind:"toggle"},{key:"allowDoubleBooking",label:"Να επιτρέπονται διπλές κρατήσεις",kind:"toggle"},{key:"cancelMoveLimit",label:"Όριο ακυρώσεων/μεταφορών",kind:"number"},{key:"adminExceedsLimits",label:"Ο διαχειριστής υπερβαίνει τα όρια",kind:"toggle"},{key:"noShowLimit",label:"Όριο απουσιών",kind:"number"},{key:"noShowUnlockCost",label:"Συνεδρίες για ξεκλείδωμα",kind:"number"},{key:"subscriptionOnly",label:"Περιορισμοί μόνο μέσα στη συνδρομή",kind:"toggle"},{key:"holidayRestrictions",label:"Περιορισμοί σε αργίες",kind:"toggle"},{key:"serviceBookingLimits",label:"Διαφορετικά όρια ανά υπηρεσία",kind:"toggle"},{key:"restrictedCustomers",label:"Περιορισμός συγκεκριμένων μελών/ωρών",kind:"toggle"},{key:"freeAbsences",label:"Δωρεάν απουσίες",kind:"number"}
  ]
};
const initial:Values={};
for(const defs of Object.values(D))for(const d of defs)initial[d.key]=d.kind==="toggle"?!["pauseBookings","guestBooking","newCustomerBooking","hideZeroAdmin","fixedPositions","fixedPositionsAffectCapacity","hideFixedPositions","hatchAvailable","incomeTools","questionnaires","allowDoubleBooking","restrictedCustomers"].includes(d.key):d.kind==="number"?({bookingMinHours:2.5,bookingMaxDays:14,cancelMinMinutes:30,moveMinHours:3,reminderHours:3.5,adminVisibilityDays:60,waitlistConfirmationHours:3,waitlistLimit:2,expiryReminderDays:2,creditsReminder:1}[d.key]??0):d.kind==="time"?(d.key==="openingTime"?"08:30":d.key==="closingTime"?"22:30":"23:00"):d.options?.[0]||"";
Object.assign(initial,{businessName:"BASEMENT HEALTH CLUB",currency:"Συνεδρίες",timeFormat:"24 ώρες"});
const nav=[['business','Επιχείρηση'],['bookings','Κρατήσεις'],['calendar','Ημερολόγιο'],['automation','Αυτοματισμοί'],['waitlist','Αναμονή'],['subscriptions','Συνδρομές & όρια'],['services','Υπηρεσίες']];

export default function SettingsPanel({owner,profile}:{owner:boolean;profile:{full_name:string|null;role:string}}){
 const [values,setValues]=useState<Values>(initial),[services,setServices]=useState<Service[]>([]),[tab,setTab]=useState('bookings'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const token=()=>localStorage.getItem('basement_access_token')||''; const set=(k:string,v:string|number|boolean)=>setValues(x=>({...x,[k]:v}));
 useEffect(()=>{void(async()=>{try{const [a,b]=await Promise.all([api('/rest/v1/app_settings?key=eq.control_center_settings&select=value',token()),api('/rest/v1/services?select=id,name,duration_minutes,default_capacity,online_booking_enabled,waiting_list_enabled,active&order=name',token())]);if(!a.ok||!b.ok)throw 0;const rows=await a.json();setValues({...initial,...(rows[0]?.value||{})});setServices(await b.json())}catch{setMessage('Δεν φορτώθηκαν οι ρυθμίσεις.')}})()},[]);
 async function save(){setBusy(true);setMessage('');const r=await api('/rest/v1/app_settings?on_conflict=key',token(),{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({key:'control_center_settings',value:values,updated_at:new Date().toISOString()})});setBusy(false);setMessage(r.ok?'Οι ρυθμίσεις αποθηκεύτηκαν και εφαρμόστηκαν.':'Δεν αποθηκεύτηκαν οι ρυθμίσεις.')}
 const updateService=(id:string,key:keyof Service,value:unknown)=>setServices(x=>x.map(s=>s.id===id?{...s,[key]:value}:s));
 async function saveService(s:Service){setBusy(true);const r=await api(`/rest/v1/services?id=eq.${s.id}`,token(),{method:'PATCH',body:JSON.stringify({duration_minutes:+s.duration_minutes,default_capacity:+s.default_capacity,online_booking_enabled:s.online_booking_enabled,waiting_list_enabled:s.waiting_list_enabled,active:s.active})});setBusy(false);setMessage(r.ok?`Αποθηκεύτηκε: ${s.name}`:'Δεν αποθηκεύτηκε η υπηρεσία.')}
 if(!owner)return <div className="coming-panel"><h3>Ο λογαριασμός σου</h3><p>{profile.full_name} · {profile.role}</p></div>;
 const control=(d:Def)=>d.kind==='toggle'?<button type="button" role="switch" aria-checked={!!values[d.key]} className={values[d.key]?'setting-switch on':'setting-switch'} onClick={()=>set(d.key,!values[d.key])}><i/><em>{values[d.key]?'Ενεργό':'Ανενεργό'}</em></button>:d.kind==='select'?<select value={String(values[d.key])} onChange={e=>set(d.key,e.target.value)}>{d.options?.map(o=><option key={o}>{o}</option>)}</select>:<input type={d.kind} min={d.kind==='number'?0:undefined} value={String(values[d.key])} onChange={e=>set(d.key,d.kind==='number'?Number(e.target.value):e.target.value)}/>;
 return <div className="settings-center"><div className="panel-title settings-heading"><div><span className="kicker">ΡΥΘΜΙΣΕΙΣ</span><h2>Κέντρο ρυθμίσεων</h2><p>Όλες οι λειτουργίες του Basement σε ένα σημείο.</p></div><button className="save-settings" disabled={busy} onClick={()=>void save()}>{busy?'Αποθήκευση…':'Αποθήκευση όλων'}</button></div>{message&&<p className="notice">{message}</p>}
 <nav className="settings-nav">{nav.map(([id,label])=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {tab!=='services'?<section className="settings-section"><header><h3>{nav.find(x=>x[0]===tab)?.[1]}</h3><p>Οι αλλαγές ισχύουν μετά την αποθήκευση.</p></header><div className="settings-fields">{D[tab].map(d=><label className="setting-row" key={d.key}><span><b>{d.label}</b>{d.help&&<small>{d.help}</small>}</span>{control(d)}</label>)}</div></section>:<section className="settings-section"><header><h3>Υπηρεσίες</h3><p>Διάρκεια, θέσεις και online λειτουργίες.</p></header><div className="service-settings">{services.map(s=><article key={s.id}><div><h4>{s.name}</h4><label className="check"><input type="checkbox" checked={s.active} onChange={e=>updateService(s.id,'active',e.target.checked)}/> Ενεργή</label></div><label>Διάρκεια<input type="number" min="1" value={s.duration_minutes} onChange={e=>updateService(s.id,'duration_minutes',+e.target.value)}/></label><label>Θέσεις<input type="number" min="1" value={s.default_capacity} onChange={e=>updateService(s.id,'default_capacity',+e.target.value)}/></label><label className="check"><input type="checkbox" checked={s.online_booking_enabled} onChange={e=>updateService(s.id,'online_booking_enabled',e.target.checked)}/> Online</label><label className="check"><input type="checkbox" checked={s.waiting_list_enabled} onChange={e=>updateService(s.id,'waiting_list_enabled',e.target.checked)}/> Αναμονή</label><button disabled={busy} onClick={()=>void saveService(s)}>Αποθήκευση</button></article>)}</div></section>}
 <div className="settings-save-bar"><span>{Object.values(D).flat().length} διαθέσιμες ρυθμίσεις</span><button disabled={busy} onClick={()=>void save()}>{busy?'Αποθήκευση…':'Αποθήκευση όλων'}</button></div></div>;
}
